CC26xx Driver Library: setup.c File Reference
setup.c File Reference
#include "../inc/hw_types.h"
#include "../inc/hw_memmap.h"
#include "../inc/hw_adi.h"
#include "../inc/hw_adi_2_refsys.h"
#include "../inc/hw_adi_3_refsys.h"
#include "../inc/hw_adi_4_aux.h"
#include "../inc/hw_aon_ioc.h"
#include "../inc/hw_aon_pmctl.h"
#include "../inc/hw_aon_rtc.h"
#include "../inc/hw_ddi_0_osc.h"
#include "../inc/hw_ccfg.h"
#include "../inc/hw_fcfg1.h"
#include "../inc/hw_flash.h"
#include "../inc/hw_prcm.h"
#include "../inc/hw_vims.h"
#include "aux_sysif.h"
#include "chipinfo.h"
#include "setup.h"
#include "setup_rom.h"
Macros
#define ADI_4_AUX_O_LPMBIAS 0x0000000E
#define ADI_4_AUX_LPMBIAS_LPM_TRIM_IOUT_M 0x0000003F
#define ADI_4_AUX_LPMBIAS_LPM_TRIM_IOUT_S 0
#define ADI_4_AUX_COMP_LPM_BIAS_WIDTH_TRIM_M 0x00000038
#define ADI_4_AUX_COMP_LPM_BIAS_WIDTH_TRIM_S 3
#define CPU_DELAY_MICRO_SECONDS(x) CPUdelay(((uint32_t)(((x) * 48.0) / 5.0)) - 1)
Functions
static void TrimAfterColdReset (void)
Trims to be applied when coming from PIN_RESET.
static void TrimAfterColdResetWakeupFromShutDown (uint32_t ui32Fcfg1Revision)
Trims to be applied when coming from SHUTDOWN (also called when coming from PIN_RESET).
static void TrimAfterColdResetWakeupFromShutDownWakeupFromPowerDown (void)
Trims to be applied when coming from POWER_DOWN (also called when coming from SHUTDOWN and PIN_RESET).
void SetupTrimDevice (void)
Performs the necessary trim of the device which is not done in boot code.
static void Step_RCOSCHF_CTRIM (uint32_t toCode)
static void Step_VBG (int32_t targetSigned)
Macro Definition Documentation
#define ADI_4_AUX_COMP_LPM_BIAS_WIDTH_TRIM_M 0x00000038
Referenced by TrimAfterColdResetWakeupFromShutDown().
#define ADI_4_AUX_COMP_LPM_BIAS_WIDTH_TRIM_S 3
Referenced by TrimAfterColdResetWakeupFromShutDown().
#define ADI_4_AUX_LPMBIAS_LPM_TRIM_IOUT_M 0x0000003F
Referenced by TrimAfterColdResetWakeupFromShutDown().
#define ADI_4_AUX_LPMBIAS_LPM_TRIM_IOUT_S 0
Referenced by TrimAfterColdResetWakeupFromShutDown().
#define ADI_4_AUX_O_LPMBIAS 0x0000000E
Referenced by TrimAfterColdResetWakeupFromShutDown().
#define CPU_DELAY_MICRO_SECONDS (x) CPUdelay(((uint32_t)(((x) * 48.0) / 5.0)) - 1)
Function Documentation
static void Step_RCOSCHF_CTRIM (uint32_t toCode) static
Referenced by TrimAfterColdResetWakeupFromShutDown().
 {
     uint32_t currentRcoscHfCtlReg ;
     uint32_t currentTrim          ;
     currentRcoscHfCtlReg = HWREGH( AUX_DDI0_OSC_BASE + DDI_0_OSC_O_RCOSCHFCTL );
     currentTrim = ((( currentRcoscHfCtlReg & DDI_0_OSC_RCOSCHFCTL_RCOSCHF_CTRIM_M ) >>
                                              DDI_0_OSC_RCOSCHFCTL_RCOSCHF_CTRIM_S ) ^ 0xC0 );
     while ( toCode != currentTrim ) {
         HWREG( AON_RTC_BASE + AON_RTC_O_SYNCLF );   // Wait for next edge on SCLK_LF (positive or negative)
         if ( toCode > currentTrim ) currentTrim++;
         else                        currentTrim--;
         HWREGH( AUX_DDI0_OSC_BASE + DDI_0_OSC_O_RCOSCHFCTL ) =
             ( currentRcoscHfCtlReg  & ~DDI_0_OSC_RCOSCHFCTL_RCOSCHF_CTRIM_M ) |
             (( currentTrim ^ 0xC0 ) << DDI_0_OSC_RCOSCHFCTL_RCOSCHF_CTRIM_S );
     }
 }
static void Step_VBG (int32_t targetSigned) static
Referenced by TrimAfterColdResetWakeupFromShutDown().
 {
     // VBG (ANA_TRIM[5:0]=TRIMTEMP --> ADI_3_REFSYS:REFSYSCTL3.TRIM_VBG)
     uint32_t refSysCtl3Reg ;
     int32_t  currentSigned ;
     do {
         refSysCtl3Reg = HWREGB( ADI3_BASE + ADI_3_REFSYS_O_REFSYSCTL3 );
         currentSigned =
             (((int32_t)( refSysCtl3Reg << ( 32 - ADI_3_REFSYS_REFSYSCTL3_TRIM_VBG_W - ADI_3_REFSYS_REFSYSCTL3_TRIM_VBG_S )))
                                        >> ( 32 - ADI_3_REFSYS_REFSYSCTL3_TRIM_VBG_W ));
         HWREG( AON_RTC_BASE + AON_RTC_O_SYNCLF );   // Wait for next edge on SCLK_LF (positive or negative)
         if ( targetSigned != currentSigned ) {
             if ( targetSigned > currentSigned ) currentSigned++;
             else                                currentSigned--;
             HWREGB( ADI3_BASE + ADI_3_REFSYS_O_REFSYSCTL3 ) =
                 ( refSysCtl3Reg & ~( ADI_3_REFSYS_REFSYSCTL3_BOD_BG_TRIM_EN | ADI_3_REFSYS_REFSYSCTL3_TRIM_VBG_M )) |
                 ((((uint32_t)currentSigned) << ADI_3_REFSYS_REFSYSCTL3_TRIM_VBG_S ) & ADI_3_REFSYS_REFSYSCTL3_TRIM_VBG_M );
             HWREGB( ADI3_BASE + ADI_3_REFSYS_O_REFSYSCTL3 ) |= ADI_3_REFSYS_REFSYSCTL3_BOD_BG_TRIM_EN;  // Bit set by doing a read modify write
         }
     } while ( targetSigned != currentSigned );
 }
static void TrimAfterColdReset (void) static
Trims to be applied when coming from PIN_RESET.
Returns
None
Referenced by SetupTrimDevice().
 {
     // Currently no specific trim for Cold Reset
 }
static void TrimAfterColdResetWakeupFromShutDown (uint32_t ui32Fcfg1Revision) static
Trims to be applied when coming from SHUTDOWN (also called when coming from PIN_RESET).
Parameters
ui32Fcfg1Revision
Returns
None
Referenced by SetupTrimDevice().
 {
     uint32_t   ccfg_ModeConfReg  ;
     // Check in CCFG for alternative DCDC setting
     if (( HWREG( CCFG_BASE + CCFG_O_SIZE_AND_DIS_FLAGS ) & CCFG_SIZE_AND_DIS_FLAGS_DIS_ALT_DCDC_SETTING ) == 0 ) {
         // ADI_3_REFSYS:DCDCCTL5[3]  (=DITHER_EN) = CCFG_MODE_CONF_1[19]   (=ALT_DCDC_DITHER_EN)
         // ADI_3_REFSYS:DCDCCTL5[2:0](=IPEAK    ) = CCFG_MODE_CONF_1[18:16](=ALT_DCDC_IPEAK    )
         // Using a single 4-bit masked write since layout is equal for both source and destination
         HWREGB( ADI3_BASE + ADI_O_MASK4B + ( ADI_3_REFSYS_O_DCDCCTL5 * 2 )) = ( 0xF0 |
             ( HWREG( CCFG_BASE + CCFG_O_MODE_CONF_1 ) >> CCFG_MODE_CONF_1_ALT_DCDC_IPEAK_S ));
     }
     // TBD-Agama - Temporarily removed for Agama
     // read the MODE_CONF register in CCFG
     ccfg_ModeConfReg = HWREG( CCFG_BASE + CCFG_O_MODE_CONF );
     // First part of trim done after cold reset and wakeup from shutdown:
     // -Adjust the VDDR_TRIM_SLEEP value.
     // -Configure DCDC.
     SetupAfterColdResetWakeupFromShutDownCfg1( ccfg_ModeConfReg );
     // Second part of trim done after cold reset and wakeup from shutdown:
     // -Configure XOSC.
 #if ( CCFG_BASE == CCFG_BASE_DEFAULT )
     SetupAfterColdResetWakeupFromShutDownCfg2( ui32Fcfg1Revision, ccfg_ModeConfReg );
 #else
     NOROM_SetupAfterColdResetWakeupFromShutDownCfg2( ui32Fcfg1Revision, ccfg_ModeConfReg );
 #endif
     // Special shadow register trim propagation on first batch of devices
     {
         uint32_t ui32EfuseData ;
         uint32_t orgResetCtl   ;
         // Get VTRIM_COARSE and VTRIM_DIG from EFUSE shadow register OSC_BIAS_LDO_TRIM
         ui32EfuseData = HWREG( FCFG1_BASE + FCFG1_O_SHDW_OSC_BIAS_LDO_TRIM );
         Step_RCOSCHF_CTRIM(( ui32EfuseData &
             FCFG1_SHDW_OSC_BIAS_LDO_TRIM_RCOSCHF_CTRIM_M ) >>
             FCFG1_SHDW_OSC_BIAS_LDO_TRIM_RCOSCHF_CTRIM_S ) ;
         // Write to register SOCLDO_0_1 (addr offset 3) bits[7:4] (VTRIM_COARSE) and
         // bits[3:0] (VTRIM_DIG) in ADI_2_REFSYS. Direct write can be used since
         // all register bit fields are trimmed.
         HWREGB(ADI2_BASE + ADI_O_DIR + ADI_2_REFSYS_O_SOCLDOCTL1) =
             ((((ui32EfuseData & FCFG1_SHDW_OSC_BIAS_LDO_TRIM_VTRIM_COARSE_M) >>
                FCFG1_SHDW_OSC_BIAS_LDO_TRIM_VTRIM_COARSE_S) <<
               ADI_2_REFSYS_SOCLDOCTL1_VTRIM_COARSE_S) |
              (((ui32EfuseData & FCFG1_SHDW_OSC_BIAS_LDO_TRIM_VTRIM_DIG_M) >>
                FCFG1_SHDW_OSC_BIAS_LDO_TRIM_VTRIM_DIG_S) <<
               ADI_2_REFSYS_SOCLDOCTL1_VTRIM_DIG_S));
         // Write to register CTLSOCREFSYS0 (addr offset 0) bits[4:0] (TRIMIREF) in
         // ADI_2_REFSYS. Avoid using masked write access since bit field spans
         // nibble boundary. Direct write can be used since this is the only defined
         // bit field in this register.
         HWREGB(ADI2_BASE + ADI_O_DIR + ADI_2_REFSYS_O_REFSYSCTL0) =
             (((ui32EfuseData & FCFG1_SHDW_OSC_BIAS_LDO_TRIM_TRIMIREF_M) >>
               FCFG1_SHDW_OSC_BIAS_LDO_TRIM_TRIMIREF_S) <<
              ADI_2_REFSYS_REFSYSCTL0_TRIM_IREF_S);
         // Write to register CTLSOCREFSYS2 (addr offset 4) bits[7:4] (TRIMMAG) in
         // ADI_3_REFSYS
         HWREGH(ADI3_BASE + ADI_O_MASK8B + (ADI_3_REFSYS_O_REFSYSCTL2 << 1)) =
             (ADI_3_REFSYS_REFSYSCTL2_TRIM_VREF_M << 8) |
             (((ui32EfuseData & FCFG1_SHDW_OSC_BIAS_LDO_TRIM_TRIMMAG_M) >>
               FCFG1_SHDW_OSC_BIAS_LDO_TRIM_TRIMMAG_S) <<
              ADI_3_REFSYS_REFSYSCTL2_TRIM_VREF_S);
         // Get TRIMBOD_EXTMODE or TRIMBOD_INTMODE from EFUSE shadow register in FCFG1
         ui32EfuseData = HWREG( FCFG1_BASE + FCFG1_O_SHDW_ANA_TRIM );
         orgResetCtl = ( HWREG( AON_PMCTL_BASE + AON_PMCTL_O_RESETCTL ) & ~AON_PMCTL_RESETCTL_MCU_WARM_RESET_M );
         HWREG( AON_PMCTL_BASE + AON_PMCTL_O_RESETCTL ) =
             ( orgResetCtl & ~( AON_PMCTL_RESETCTL_CLK_LOSS_EN  |
                                AON_PMCTL_RESETCTL_VDD_LOSS_EN  |
                                AON_PMCTL_RESETCTL_VDDR_LOSS_EN |
                                AON_PMCTL_RESETCTL_VDDS_LOSS_EN   ));
         HWREG( AON_RTC_BASE + AON_RTC_O_SYNC ); // Wait for xxx_LOSS_EN setting to propagate
         // The VDDS_BOD trim and the VDDR trim is already stepped up to max/HH if "CC1352 boost mode" is requested.
         // See function SetupAfterColdResetWakeupFromShutDownCfg1() in setup_rom.c for details.
         if ((( ccfg_ModeConfReg & CCFG_MODE_CONF_VDDR_EXT_LOAD  ) != 0 ) ||
             (( ccfg_ModeConfReg & CCFG_MODE_CONF_VDDS_BOD_LEVEL ) == 0 )    )
         {
             if(HWREG(AON_PMCTL_BASE + AON_PMCTL_O_PWRCTL) &
                     AON_PMCTL_PWRCTL_EXT_REG_MODE)
             {
                 // Apply VDDS BOD trim value
                 // Write to register CTLSOCREFSYS1 (addr offset 3) bit[7:3] (TRIMBOD)
                 // in ADI_3_REFSYS
                 HWREGH(ADI3_BASE + ADI_O_MASK8B + (ADI_3_REFSYS_O_REFSYSCTL1 << 1)) =
                     (ADI_3_REFSYS_REFSYSCTL1_TRIM_VDDS_BOD_M << 8) |
                     (((ui32EfuseData & FCFG1_SHDW_ANA_TRIM_TRIMBOD_EXTMODE_M) >>
                       FCFG1_SHDW_ANA_TRIM_TRIMBOD_EXTMODE_S) <<
                      ADI_3_REFSYS_REFSYSCTL1_TRIM_VDDS_BOD_S);
             }
             else
             {
                 // Apply VDDS BOD trim value
                 // Write to register CTLSOCREFSYS1 (addr offset 3) bit[7:3] (TRIMBOD)
                 // in ADI_3_REFSYS
                 HWREGH(ADI3_BASE + ADI_O_MASK8B + (ADI_3_REFSYS_O_REFSYSCTL1 << 1)) =
                     (ADI_3_REFSYS_REFSYSCTL1_TRIM_VDDS_BOD_M << 8) |
                     (((ui32EfuseData & FCFG1_SHDW_ANA_TRIM_TRIMBOD_INTMODE_M) >>
                       FCFG1_SHDW_ANA_TRIM_TRIMBOD_INTMODE_S) <<
                      ADI_3_REFSYS_REFSYSCTL1_TRIM_VDDS_BOD_S);
             }
             // Load the new VDDS_BOD setting
             HWREGB( ADI3_BASE + ADI_3_REFSYS_O_REFSYSCTL3 ) &= ~ADI_3_REFSYS_REFSYSCTL3_BOD_BG_TRIM_EN; // Bit clear by doing a read modify write
             HWREGB( ADI3_BASE + ADI_3_REFSYS_O_REFSYSCTL3 ) |= ADI_3_REFSYS_REFSYSCTL3_BOD_BG_TRIM_EN;  // Bit set by doing a read modify write
             SetupStepVddrTrimTo(( ui32EfuseData &
                 FCFG1_SHDW_ANA_TRIM_VDDR_TRIM_M ) >>
                 FCFG1_SHDW_ANA_TRIM_VDDR_TRIM_S ) ;
         }
         // VBG (ANA_TRIM[5:0]=TRIMTEMP --> ADI_3_REFSYS:REFSYSCTL3.TRIM_VBG)
         Step_VBG(((int32_t)( ui32EfuseData << ( 32 - FCFG1_SHDW_ANA_TRIM_TRIMTEMP_W - FCFG1_SHDW_ANA_TRIM_TRIMTEMP_S )))
                                            >> ( 32 - FCFG1_SHDW_ANA_TRIM_TRIMTEMP_W ));
         // Wait two more LF edges before restoring xxx_LOSS_EN settings
         HWREG( AON_RTC_BASE + AON_RTC_O_SYNCLF );  // Wait for next edge on SCLK_LF (positive or negative)
         HWREG( AON_RTC_BASE + AON_RTC_O_SYNCLF );  // Wait for next edge on SCLK_LF (positive or negative)
         HWREG( AON_PMCTL_BASE + AON_PMCTL_O_RESETCTL ) = orgResetCtl;
         HWREG( AON_RTC_BASE + AON_RTC_O_SYNC );    // Wait for xxx_LOSS_EN setting to propagate
     }
     {
         uint32_t  trimReg        ;
         uint32_t  ui32TrimValue  ;
         //--- Propagate the LPM_BIAS trim ---
         trimReg = HWREG( FCFG1_BASE + FCFG1_O_DAC_BIAS_CNF );
         ui32TrimValue = (( trimReg & FCFG1_DAC_BIAS_CNF_LPM_TRIM_IOUT_M ) >>
                                      FCFG1_DAC_BIAS_CNF_LPM_TRIM_IOUT_S ) ;
         HWREGB( AUX_ADI4_BASE + ADI_4_AUX_O_LPMBIAS ) = (( ui32TrimValue << ADI_4_AUX_LPMBIAS_LPM_TRIM_IOUT_S ) &
                                                                             ADI_4_AUX_LPMBIAS_LPM_TRIM_IOUT_M ) ;
         // Set LPM_BIAS_BACKUP_EN according to FCFG1 configuration
         if ( trimReg & FCFG1_DAC_BIAS_CNF_LPM_BIAS_BACKUP_EN ) {
             HWREGB( ADI3_BASE + ADI_O_SET + ADI_3_REFSYS_O_AUX_DEBUG ) = ADI_3_REFSYS_AUX_DEBUG_LPM_BIAS_BACKUP_EN;
         } else {
             HWREGB( ADI3_BASE + ADI_O_CLR + ADI_3_REFSYS_O_AUX_DEBUG ) = ADI_3_REFSYS_AUX_DEBUG_LPM_BIAS_BACKUP_EN;
         }
         // Set LPM_BIAS_WIDTH_TRIM according to FCFG1 configuration
         {
             uint32_t widthTrim = (( trimReg & FCFG1_DAC_BIAS_CNF_LPM_BIAS_WIDTH_TRIM_M ) >> FCFG1_DAC_BIAS_CNF_LPM_BIAS_WIDTH_TRIM_S );
             HWREGH( AUX_ADI4_BASE + ADI_O_MASK8B + ( ADI_4_AUX_O_COMP * 2 )) = // Set LPM_BIAS_WIDTH_TRIM = 3
                 (( ADI_4_AUX_COMP_LPM_BIAS_WIDTH_TRIM_M << 8         ) |       // Set mask (bits to be written) in [15:8]
                  ( widthTrim << ADI_4_AUX_COMP_LPM_BIAS_WIDTH_TRIM_S )   );    // Set value (in correct bit pos) in [7:0]
         }
     }
     // Third part of trim done after cold reset and wakeup from shutdown:
     // -Configure HPOSC.
     // -Setup the LF clock.
 #if ( CCFG_BASE == CCFG_BASE_DEFAULT )
     SetupAfterColdResetWakeupFromShutDownCfg3( ccfg_ModeConfReg );
 #else
     NOROM_SetupAfterColdResetWakeupFromShutDownCfg3( ccfg_ModeConfReg );
 #endif
     // Set AUX into power down active mode
     AUXSYSIFOpModeChange( AUX_SYSIF_OPMODE_TARGET_PDA );
     // Disable EFUSE clock
     HWREGBITW( FLASH_BASE + FLASH_O_CFG, FLASH_CFG_DIS_EFUSECLK_BITN ) = 1;
 }
static void TrimAfterColdResetWakeupFromShutDownWakeupFromPowerDown (void) static
Trims to be applied when coming from POWER_DOWN (also called when coming from SHUTDOWN and PIN_RESET).
Returns
None
Referenced by SetupTrimDevice().
 {
     // Currently no specific trim for Powerdown
 }