/*
 * DO NOT MODIFY. This file is automatically generated during the pre-build
 *                step by the lib_search utility
 */

"C:\TI\simplelink_cc26x2_sdk_2_20_00_36\source\ti\ble5stack\blelib\cc26x2r1\ctrl\hci_xcxx.a"
"C:\TI\simplelink_cc26x2_sdk_2_20_00_36\source\ti\ble5stack\blelib\cc26x2r1\ctrl\ll_xcxx.a"
"C:\TI\simplelink_cc26x2_sdk_2_20_00_36\source\ti\ble5stack\blelib\cc26x2r1\hci_tl\hci_tl_none.a"
"C:\TI\simplelink_cc26x2_sdk_2_20_00_36\source\ti\ble5stack\blelib\cc26x2r1\host\att_xcxx.a"
"C:\TI\simplelink_cc26x2_sdk_2_20_00_36\source\ti\ble5stack\blelib\cc26x2r1\host\gap_xcxx.a"
"C:\TI\simplelink_cc26x2_sdk_2_20_00_36\source\ti\ble5stack\blelib\cc26x2r1\host\gatt_xcxx.a"
"C:\TI\simplelink_cc26x2_sdk_2_20_00_36\source\ti\ble5stack\blelib\cc26x2r1\host\l2cap_xcxx.a"
"C:\TI\simplelink_cc26x2_sdk_2_20_00_36\source\ti\ble5stack\blelib\cc26x2r1\host\profiles_xcxx.a"
"C:\TI\simplelink_cc26x2_sdk_2_20_00_36\source\ti\ble5stack\blelib\cc26x2r1\host\smp_xcxx.a"
"C:\TI\simplelink_cc26x2_sdk_2_20_00_36\source\ti\ble5stack\blelib\cc26x2r1\host\sm_xcxx.a"
