CC26xx Driver Library: sha2.c File Reference
sha2.c File Reference
#include "sha2.h"
Functions
static uint32_t SHA2ExecuteHash (const uint8_t *message, uint8_t *resultDigest, uint32_t *intermediateDigest, uint32_t totalMsgLength, uint32_t messageLength, uint32_t hashAlgorithm, bool initialHash, bool finalHash)
void SHA2StartDMAOperation (uint8_t *channel0Addr, uint32_t channel0Length, uint8_t *channel1Addr, uint32_t channel1Length)
Start a crypto DMA operation.
uint32_t SHA2WaitForIRQFlags (uint32_t irqFlags)
Poll the interrupt status register and clear when done.
uint32_t SHA2ComputeInitialHash (const uint8_t *message, uint32_t *intermediateDigest, uint32_t hashAlgorithm, uint32_t initialMessageLength)
Start a new SHA-2 hash operation.
uint32_t SHA2ComputeIntermediateHash (const uint8_t *message, uint32_t *intermediateDigest, uint32_t hashAlgorithm, uint32_t intermediateMessageLength)
Resume a SHA-2 hash operation but do not finalize it.
uint32_t SHA2ComputeFinalHash (const uint8_t *message, uint8_t *resultDigest, uint32_t *intermediateDigest, uint32_t totalMsgLength, uint32_t messageLength, uint32_t hashAlgorithm)
Resume a SHA-2 hash operation and finalize it.
uint32_t SHA2ComputeHash (const uint8_t *message, uint8_t *resultDigest, uint32_t totalMsgLength, uint32_t hashAlgorithm)
Start a SHA-2 hash operation and return the finalized digest.
Function Documentation
static uint32_t SHA2ExecuteHash (const uint8_t * message, uint8_t * resultDigest, uint32_t * intermediateDigest, uint32_t totalMsgLength, uint32_t messageLength, uint32_t hashAlgorithm, bool initialHash, bool finalHash) static
Referenced by SHA2ComputeFinalHash(), SHA2ComputeHash(), SHA2ComputeInitialHash(), and SHA2ComputeIntermediateHash().
 {
     uint8_t digestLength = 0;
     uint32_t dmaAlgorithmSelect = 0;
     SHA2ClearDigestAvailableFlag();
     switch (hashAlgorithm) {
         case SHA2_MODE_SELECT_SHA224:
             digestLength = SHA2_SHA224_DIGEST_LENGTH_BYTES;
             dmaAlgorithmSelect = SHA2_ALGSEL_SHA256;
             break;
         case SHA2_MODE_SELECT_SHA256:
             digestLength = SHA2_SHA256_DIGEST_LENGTH_BYTES;
             dmaAlgorithmSelect = SHA2_ALGSEL_SHA256;
             break;
         case SHA2_MODE_SELECT_SHA384:
             digestLength = SHA2_SHA384_DIGEST_LENGTH_BYTES;
             dmaAlgorithmSelect = SHA2_ALGSEL_SHA512;
             break;
         case SHA2_MODE_SELECT_SHA512:
             digestLength = SHA2_SHA512_DIGEST_LENGTH_BYTES;
             dmaAlgorithmSelect = SHA2_ALGSEL_SHA512;
             break;
         default:
             return SHA2_INVALID_ALGORITHM;
     }
     if (initialHash && finalHash) {
         // The empty string is a perfectly valid message. It obviously has a length of 0. The DMA cannot
         // handle running with a transfer length of 0. This workaround depends on the hash engine adding the
         // trailing 1 bit and 0-padding bits after the DMAtransfer is complete and not in the DMA itself.
         // totalMsgLength is purposefully not altered as it is appended to the end of the message during finalization
         // and determines how many padding-bytes are added.
         // Altering totalMsgLength would alter the final hash digest.
         // Because totalMsgLength specifies that the message is of length 0, the content of the byte loaded
         // through the DMA is irrelevant. It is overwritten internally in the hash engine.
         messageLength = messageLength ? messageLength : 1;
     }
     // Setting the incorrect number of bits here leads to the calculation of the correct result
     // but a failure to read them out.
     // The tag bit is set to read out the digest via DMA rather than through the slave interface.
     SHA2SelectAlgorithm(dmaAlgorithmSelect | (resultDigest ? SHA2_ALGSEL_TAG : 0));
     SHA2IntClear(SHA2_DMA_IN_DONE | SHA2_RESULT_RDY);
     SHA2IntEnable(SHA2_DMA_IN_DONE | SHA2_RESULT_RDY);
     HWREG(CRYPTO_BASE + CRYPTO_O_HASHMODE) = hashAlgorithm | (initialHash ? CRYPTO_HASHMODE_NEW_HASH_M : 0);
     // Only load the intermediate digest if requested.
     if (intermediateDigest && !initialHash) {
         SHA2SetDigest(intermediateDigest, digestLength);
     }
     // If this is the final hash, finalization is required. This means appending a 1 bit, padding the message until this section
     // is 448 bytes long, and adding the 64 bit total length of the message in bits. Thankfully, this is all done in hardware.
     if (finalHash) {
         // This specific length must be specified in bits not bytes.
         SHA2SetMessageLength(totalMsgLength * 8);
         HWREG(CRYPTO_BASE + CRYPTO_O_HASHIOBUFCTRL) = CRYPTO_HASHIOBUFCTRL_PAD_DMA_MESSAGE_M;
     }
     // The cast is fine in this case. SHA2StartDMAOperation channel one serves as input and no one does
     // hash operations in-place.
     SHA2StartDMAOperation((uint8_t *)message, messageLength,  resultDigest, digestLength);
     return SHA2_SUCCESS;
 }