TI Thread API Documentation: examples/platform/alarm.c File Reference
alarm.c File Reference
Functions
void Alarm_handler (union sigval val)
uint32_t otPlatAlarmMilliGetNow (void)
void otPlatAlarmMilliStartAt (otInstance *aInstance, uint32_t aT0, uint32_t aDt)
void otPlatAlarmMilliStop (otInstance *aInstance)
void platformAlarmInit (void)
void platformAlarmProcess (otInstance *aInstance)
Variables
static bool Alarm_running = false
static uint32_t Alarm_time = 0
static uint32_t Alarm_time0 = 0
static timer_t Alarm_timerid = 0
Function Documentation
Alarm_handler()
void Alarm_handler (union sigval val)
Handler for the POSIX clock callback.
References platformAlarmSignal().
Referenced by platformAlarmInit().
otPlatAlarmMilliGetNow()
uint32_t otPlatAlarmMilliGetNow (void)
Function documented in platform/alarm-milli.h
Referenced by otPlatAlarmMilliStartAt(), otPlatDiagAlarmCallback(), PlatDiag_processTransmit(), and platformAlarmProcess().
otPlatAlarmMilliStartAt()
void otPlatAlarmMilliStartAt (otInstance * aInstance, uint32_t aT0, uint32_t aDt)
Function documented in platform/alarm-milli.h
References Alarm_running, Alarm_time, Alarm_time0, Alarm_timerid, otPlatAlarmMilliGetNow(), and platformAlarmSignal().
Referenced by otPlatDiagAlarmCallback(), and PlatDiag_processTransmit().
otPlatAlarmMilliStop()
void otPlatAlarmMilliStop (otInstance * aInstance)
Function documented in platform/alarm-milli.h
References Alarm_running, and Alarm_timerid.
Referenced by PlatDiag_processTransmit().
platformAlarmInit()
void platformAlarmInit (void)
Function documented in platform.h
References Alarm_handler(), Alarm_running, and Alarm_timerid.
Referenced by PlatformInit().
platformAlarmProcess()
void platformAlarmProcess (otInstance * aInstance)
Function documented in platform.h
References Alarm_running, Alarm_time, Alarm_time0, Alarm_timerid, otPlatAlarmMilliGetNow(), otPlatDiagModeGet(), and platformAlarmSignal().
Referenced by OtStack_task().
Variable Documentation
Alarm_running
bool Alarm_running = false static
Referenced by otPlatAlarmMilliStartAt(), otPlatAlarmMilliStop(), platformAlarmInit(), and platformAlarmProcess().
Alarm_time
uint32_t Alarm_time = 0 static
Referenced by otPlatAlarmMilliStartAt(), and platformAlarmProcess().
Alarm_time0
uint32_t Alarm_time0 = 0 static
Referenced by otPlatAlarmMilliStartAt(), and platformAlarmProcess().
Alarm_timerid
timer_t Alarm_timerid = 0 static
Referenced by otPlatAlarmMilliStartAt(), otPlatAlarmMilliStop(), platformAlarmInit(), and platformAlarmProcess().
© Copyright 1995-2018, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale