TI Thread API Documentation: examples/sensors/bme280.c File Reference
bme280.c File Reference
Functions
double bme280_compensate_humidity_double (s32 v_uncom_humidity_s32)
Reads actual humidity from uncompensated humidity.
u32 bme280_compensate_humidity_int32 (s32 v_uncomp_humidity_s32)
Reads actual humidity from uncompensated humidity.
u16 bme280_compensate_humidity_int32_sixteen_bit_output (s32 v_uncomp_humidity_s32)
Reads actual humidity from uncompensated humidity.
double bme280_compensate_pressure_double (s32 v_uncom_pressure_s32)
Reads actual pressure from uncompensated pressure.
u32 bme280_compensate_pressure_int32 (s32 v_uncomp_pressure_s32)
Reads actual pressure from uncompensated pressure.
u32 bme280_compensate_pressure_int64 (s32 v_uncom_pressure_s32)
Reads actual pressure from uncompensated pressure.
u32 bme280_compensate_pressure_int64_twentyfour_bit_output (s32 v_uncom_pressure_s32)
Reads actual pressure from uncompensated pressure.
double bme280_compensate_temperature_double (s32 v_uncom_temperature_s32)
Reads actual temperature from uncompensated temperature.
s32 bme280_compensate_temperature_int32 (s32 v_uncomp_temperature_s32)
Reads actual temperature from uncompensated temperature.
s16 bme280_compensate_temperature_int32_sixteen_bit_output (s32 v_uncomp_temperature_s32)
Reads actual temperature from uncompensated temperature.
BME280_RETURN_FUNCTION_TYPE bme280_compute_wait_time (u8 *v_delaytime_u8)
Computing waiting time for sensor data read.
BME280_RETURN_FUNCTION_TYPE bme280_get_calib_param (void)
This API is used to calibration parameters used for calculation in the registers.
BME280_RETURN_FUNCTION_TYPE bme280_get_filter (u8 *v_value_u8)
This API is used to reads filter setting in the register 0xF5 bit 3 and 4.
BME280_RETURN_FUNCTION_TYPE bme280_get_forced_uncomp_pressure_temperature_humidity (s32 *v_uncom_pressure_s32, s32 *v_uncom_temperature_s32, s32 *v_uncom_humidity_s32)
This API used to read uncompensated temperature,pressure and humidity in forced mode.
BME280_RETURN_FUNCTION_TYPE bme280_get_oversamp_humidity (u8 *v_value_u8)
This API is used to get the humidity oversampling setting in the register 0xF2 bits from 0 to 2.
BME280_RETURN_FUNCTION_TYPE bme280_get_oversamp_pressure (u8 *v_value_u8)
This API is used to get the pressure oversampling setting in the register 0xF4 bits from 2 to 4.
BME280_RETURN_FUNCTION_TYPE bme280_get_oversamp_temperature (u8 *v_value_u8)
This API is used to get the temperature oversampling setting in the register 0xF4 bits from 5 to 7.
BME280_RETURN_FUNCTION_TYPE bme280_get_power_mode (u8 *v_power_mode_u8)
This API used to get the Operational Mode from the sensor in the register 0xF4 bit 0 and 1.
BME280_RETURN_FUNCTION_TYPE bme280_get_spi3 (u8 *v_enable_disable_u8)
This API used to get the sensor SPI mode(communication type) in the register 0xF5 bit 0.
BME280_RETURN_FUNCTION_TYPE bme280_get_standby_durn (u8 *v_standby_durn_u8)
This API used to Read the standby duration time from the sensor in the register 0xF5 bit 5 to 7.
BME280_RETURN_FUNCTION_TYPE bme280_init (struct bme280_t *bme280)
This function is used for initialize the bus read and bus write functions and assign the chip id and I2C address of the BME280 sensor chip id is read in the register 0xD0 bit from 0 to 7.
BME280_RETURN_FUNCTION_TYPE bme280_read_pressure_temperature_humidity (u32 *v_pressure_u32, s32 *v_temperature_s32, u32 *v_humidity_u32)
This API used to read true pressure, temperature and humidity.
BME280_RETURN_FUNCTION_TYPE bme280_read_register (u8 v_addr_u8, u8 *v_data_u8, u8 v_len_u8)
This API reads the data from the given register.
BME280_RETURN_FUNCTION_TYPE bme280_read_uncomp_humidity (s32 *v_uncomp_humidity_s32)
This API is used to read uncompensated humidity. in the registers 0xF7, 0xF8 and 0xF9.
BME280_RETURN_FUNCTION_TYPE bme280_read_uncomp_pressure (s32 *v_uncomp_pressure_s32)
This API is used to read uncompensated pressure. in the registers 0xF7, 0xF8 and 0xF9.
BME280_RETURN_FUNCTION_TYPE bme280_read_uncomp_pressure_temperature_humidity (s32 *v_uncomp_pressure_s32, s32 *v_uncomp_temperature_s32, s32 *v_uncomp_humidity_s32)
This API used to read uncompensated pressure,temperature and humidity.
BME280_RETURN_FUNCTION_TYPE bme280_read_uncomp_temperature (s32 *v_uncomp_temperature_s32)
This API is used to read uncompensated temperature in the registers 0xFA, 0xFB and 0xFC.
BME280_RETURN_FUNCTION_TYPE bme280_set_filter (u8 v_value_u8)
This API is used to write filter setting in the register 0xF5 bit 3 and 4.
BME280_RETURN_FUNCTION_TYPE bme280_set_oversamp_humidity (u8 v_value_u8)
This API is used to set the humidity oversampling setting in the register 0xF2 bits from 0 to 2.
BME280_RETURN_FUNCTION_TYPE bme280_set_oversamp_pressure (u8 v_value_u8)
This API is used to set the pressure oversampling setting in the register 0xF4 bits from 2 to 4.
BME280_RETURN_FUNCTION_TYPE bme280_set_oversamp_temperature (u8 v_value_u8)
This API is used to set the temperature oversampling setting in the register 0xF4 bits from 5 to 7.
BME280_RETURN_FUNCTION_TYPE bme280_set_power_mode (u8 v_power_mode_u8)
This API used to set the Operational Mode from the sensor in the register 0xF4 bit 0 and 1.
BME280_RETURN_FUNCTION_TYPE bme280_set_soft_rst (void)
Used to reset the sensor The value 0xB6 is written to the 0xE0 register the device is reset using the complete power-on-reset procedure.
BME280_RETURN_FUNCTION_TYPE bme280_set_spi3 (u8 v_enable_disable_u8)
This API used to set the sensor SPI mode(communication type) in the register 0xF5 bit 0.
BME280_RETURN_FUNCTION_TYPE bme280_set_standby_durn (u8 v_standby_durn_u8)
This API used to write the standby duration time from the sensor in the register 0xF5 bit 5 to 7.
BME280_RETURN_FUNCTION_TYPE bme280_write_register (u8 v_addr_u8, u8 *v_data_u8, u8 v_len_u8)
This API write the data to the given register.
Variables
static struct bme280_t * p_bme280
Function Documentation
bme280_compensate_humidity_double()
double bme280_compensate_humidity_double (s32 v_uncom_humidity_s32)
Reads actual humidity from uncompensated humidity.
Note
returns the value in relative humidity (rH)
Output value of "42.12" equals 42.12 rH
Parameters
v_uncom_humidity_s32 : value of uncompensated humidity
Returns
Return the actual humidity in floating point
References BME280_INIT_VALUE, BME280_INVALID_DATA, bme280_t::cal_param, bme280_calibration_param_t::dig_H1, bme280_calibration_param_t::dig_H2, bme280_calibration_param_t::dig_H3, bme280_calibration_param_t::dig_H4, bme280_calibration_param_t::dig_H5, bme280_calibration_param_t::dig_H6, and bme280_calibration_param_t::t_fine.
bme280_compensate_humidity_int32()
u32 bme280_compensate_humidity_int32 (s32 v_uncomp_humidity_s32)
Reads actual humidity from uncompensated humidity.
Note
Returns the value in rH as unsigned 32bit integer in Q22.10 format(22 integer 10 fractional bits).
An output value of 42313 represents 42313 / 1024 = 41.321 rH
Parameters
v_uncomp_humidity_s32 value of uncompensated humidity
Returns
Return the actual relative humidity output as u32
References BME280_INIT_VALUE, BME280_SHIFT_BIT_POSITION_BY_04_BITS, BME280_SHIFT_BIT_POSITION_BY_07_BITS, BME280_SHIFT_BIT_POSITION_BY_10_BITS, BME280_SHIFT_BIT_POSITION_BY_11_BITS, BME280_SHIFT_BIT_POSITION_BY_12_BITS, BME280_SHIFT_BIT_POSITION_BY_14_BITS, BME280_SHIFT_BIT_POSITION_BY_15_BITS, BME280_SHIFT_BIT_POSITION_BY_20_BITS, bme280_t::cal_param, bme280_calibration_param_t::dig_H1, bme280_calibration_param_t::dig_H2, bme280_calibration_param_t::dig_H3, bme280_calibration_param_t::dig_H4, bme280_calibration_param_t::dig_H5, bme280_calibration_param_t::dig_H6, and bme280_calibration_param_t::t_fine.
Referenced by bme280_compensate_humidity_int32_sixteen_bit_output(), bme280_data_readout_template(), and bme280_read_pressure_temperature_humidity().
bme280_compensate_humidity_int32_sixteen_bit_output()
u16 bme280_compensate_humidity_int32_sixteen_bit_output (s32 v_uncomp_humidity_s32)
Reads actual humidity from uncompensated humidity.
Note
Returns the value in rH as unsigned 16bit integer
An output value of 42313 represents 42313/512 = 82.643 rH
Parameters
v_uncomp_humidity_s32 value of uncompensated humidity
Returns
Return the actual relative humidity output as u16
References bme280_compensate_humidity_int32(), BME280_INIT_VALUE, and BME280_SHIFT_BIT_POSITION_BY_01_BIT.
bme280_compensate_pressure_double()
double bme280_compensate_pressure_double (s32 v_uncom_pressure_s32)
Reads actual pressure from uncompensated pressure.
Note
Returns pressure in Pa as double.
Output value of "96386.2" equals 96386.2 Pa = 963.862 hPa.
Parameters
v_uncom_pressure_s32 : value of uncompensated pressure
Returns
Return the actual pressure in floating point
References BME280_INIT_VALUE, BME280_INVALID_DATA, bme280_t::cal_param, bme280_calibration_param_t::dig_P1, bme280_calibration_param_t::dig_P2, bme280_calibration_param_t::dig_P3, bme280_calibration_param_t::dig_P4, bme280_calibration_param_t::dig_P5, bme280_calibration_param_t::dig_P6, bme280_calibration_param_t::dig_P7, bme280_calibration_param_t::dig_P8, bme280_calibration_param_t::dig_P9, and bme280_calibration_param_t::t_fine.
bme280_compensate_pressure_int32()
u32 bme280_compensate_pressure_int32 (s32 v_uncomp_pressure_s32)
Reads actual pressure from uncompensated pressure.
Note
Returns the value in Pascal(Pa) Output value of "96386" equals 96386 Pa = 963.86 hPa = 963.86 millibar
Parameters
v_uncomp_pressure_s32 : value of uncompensated pressure
Returns
Return the actual pressure output as u32
References BME280_INIT_VALUE, BME280_INVALID_DATA, BME280_SHIFT_BIT_POSITION_BY_01_BIT, BME280_SHIFT_BIT_POSITION_BY_02_BITS, BME280_SHIFT_BIT_POSITION_BY_03_BITS, BME280_SHIFT_BIT_POSITION_BY_04_BITS, BME280_SHIFT_BIT_POSITION_BY_11_BITS, BME280_SHIFT_BIT_POSITION_BY_12_BITS, BME280_SHIFT_BIT_POSITION_BY_13_BITS, BME280_SHIFT_BIT_POSITION_BY_15_BITS, BME280_SHIFT_BIT_POSITION_BY_16_BITS, BME280_SHIFT_BIT_POSITION_BY_18_BITS, bme280_t::cal_param, bme280_calibration_param_t::dig_P1, bme280_calibration_param_t::dig_P2, bme280_calibration_param_t::dig_P3, bme280_calibration_param_t::dig_P4, bme280_calibration_param_t::dig_P5, bme280_calibration_param_t::dig_P6, bme280_calibration_param_t::dig_P7, bme280_calibration_param_t::dig_P8, bme280_calibration_param_t::dig_P9, and bme280_calibration_param_t::t_fine.
Referenced by bme280_data_readout_template(), and bme280_read_pressure_temperature_humidity().
bme280_compensate_pressure_int64()
u32 bme280_compensate_pressure_int64 (s32 v_uncom_pressure_s32)
Reads actual pressure from uncompensated pressure.
Note
Returns the value in Pa as unsigned 32 bit integer in Q24.8 format (24 integer bits and 8 fractional bits).
Output value of "24674867" represents 24674867 / 256 = 96386.2 Pa = 963.862 hPa
Parameters
v_uncom_pressure_s32 : value of uncompensated temperature
Returns
Return the actual pressure in u32
References BME280_INIT_VALUE, BME280_INVALID_DATA, BME280_SHIFT_BIT_POSITION_BY_04_BITS, BME280_SHIFT_BIT_POSITION_BY_08_BITS, BME280_SHIFT_BIT_POSITION_BY_12_BITS, BME280_SHIFT_BIT_POSITION_BY_13_BITS, BME280_SHIFT_BIT_POSITION_BY_17_BITS, BME280_SHIFT_BIT_POSITION_BY_19_BITS, BME280_SHIFT_BIT_POSITION_BY_25_BITS, BME280_SHIFT_BIT_POSITION_BY_31_BITS, BME280_SHIFT_BIT_POSITION_BY_33_BITS, BME280_SHIFT_BIT_POSITION_BY_35_BITS, BME280_SHIFT_BIT_POSITION_BY_47_BITS, bme280_t::cal_param, bme280_calibration_param_t::dig_P1, bme280_calibration_param_t::dig_P2, bme280_calibration_param_t::dig_P3, bme280_calibration_param_t::dig_P4, bme280_calibration_param_t::dig_P5, bme280_calibration_param_t::dig_P6, bme280_calibration_param_t::dig_P7, bme280_calibration_param_t::dig_P8, bme280_calibration_param_t::dig_P9, and bme280_calibration_param_t::t_fine.
Referenced by bme280_compensate_pressure_int64_twentyfour_bit_output().
bme280_compensate_pressure_int64_twentyfour_bit_output()
u32 bme280_compensate_pressure_int64_twentyfour_bit_output (s32 v_uncom_pressure_s32)
Reads actual pressure from uncompensated pressure.
Note
Returns the value in Pa.
Output value of "12337434"
represents 12337434 / 128 = 96386.2 Pa = 963.862 hPa
Parameters
v_uncom_pressure_s32 : value of uncompensated pressure
Returns
the actual pressure in u32
References bme280_compensate_pressure_int64(), BME280_INIT_VALUE, and BME280_SHIFT_BIT_POSITION_BY_01_BIT.
bme280_compensate_temperature_double()
double bme280_compensate_temperature_double (s32 v_uncom_temperature_s32)
Reads actual temperature from uncompensated temperature.
Note
returns the value in Degree centigrade
Output value of "51.23" equals 51.23 DegC.
Parameters
v_uncom_temperature_s32 : value of uncompensated temperature
Returns
Return the actual temperature in floating point
References BME280_INIT_VALUE, bme280_t::cal_param, bme280_calibration_param_t::dig_T1, bme280_calibration_param_t::dig_T2, bme280_calibration_param_t::dig_T3, bme280_calibration_param_t::t_fine, and temperature.
bme280_compensate_temperature_int32()
s32 bme280_compensate_temperature_int32 (s32 v_uncomp_temperature_s32)
Reads actual temperature from uncompensated temperature.
Note
Returns the value in 0.01 degree Centigrade Output value of "5123" equals 51.23 DegC.
Parameters
v_uncomp_temperature_s32 : value of uncompensated temperature
Returns
Returns the actual temperature
References BME280_INIT_VALUE, BME280_SHIFT_BIT_POSITION_BY_01_BIT, BME280_SHIFT_BIT_POSITION_BY_03_BITS, BME280_SHIFT_BIT_POSITION_BY_04_BITS, BME280_SHIFT_BIT_POSITION_BY_08_BITS, BME280_SHIFT_BIT_POSITION_BY_11_BITS, BME280_SHIFT_BIT_POSITION_BY_12_BITS, BME280_SHIFT_BIT_POSITION_BY_14_BITS, bme280_t::cal_param, bme280_calibration_param_t::dig_T1, bme280_calibration_param_t::dig_T2, bme280_calibration_param_t::dig_T3, bme280_calibration_param_t::t_fine, and temperature.
Referenced by bme280_compensate_temperature_int32_sixteen_bit_output(), bme280_data_readout_template(), and bme280_read_pressure_temperature_humidity().
bme280_compensate_temperature_int32_sixteen_bit_output()
s16 bme280_compensate_temperature_int32_sixteen_bit_output (s32 v_uncomp_temperature_s32)
Reads actual temperature from uncompensated temperature.
Note
Returns the value with 500LSB/DegC centred around 24 DegC output value of "5123" equals(5123/500)+24 = 34.246DegC
Parameters
v_uncomp_temperature_s32 value of uncompensated temperature
Returns
Return the actual temperature as s16 output
References bme280_compensate_temperature_int32(), BME280_INIT_VALUE, BME280_SHIFT_BIT_POSITION_BY_08_BITS, bme280_t::cal_param, bme280_calibration_param_t::t_fine, and temperature.
bme280_compute_wait_time()
BME280_RETURN_FUNCTION_TYPE bme280_compute_wait_time (u8 * v_delaytime_u8)
Computing waiting time for sensor data read.
Parameters
v_delaytime_u8 : The value of delay time for force mode
Return values
0 -> Success
References BME280_RETURN_FUNCTION_TYPE, BME280_SHIFT_BIT_POSITION_BY_01_BIT, bme280_t::oversamp_humidity, bme280_t::oversamp_pressure, bme280_t::oversamp_temperature, SUCCESS, T_INIT_MAX, T_MEASURE_PER_OSRS_MAX, T_SETUP_HUMIDITY_MAX, and T_SETUP_PRESSURE_MAX.
Referenced by bme280_get_forced_uncomp_pressure_temperature_humidity().
bme280_get_calib_param()
BME280_RETURN_FUNCTION_TYPE bme280_get_calib_param (void)
This API is used to calibration parameters used for calculation in the registers.
parameter Register address bit
dig_T1 0x88 and 0x89 from 0 : 7 to 8: 15
dig_T2 0x8A and 0x8B from 0 : 7 to 8: 15
dig_T3 0x8C and 0x8D from 0 : 7 to 8: 15
dig_P1 0x8E and 0x8F from 0 : 7 to 8: 15
dig_P2 0x90 and 0x91 from 0 : 7 to 8: 15
dig_P3 0x92 and 0x93 from 0 : 7 to 8: 15
dig_P4 0x94 and 0x95 from 0 : 7 to 8: 15
dig_P5 0x96 and 0x97 from 0 : 7 to 8: 15
dig_P6 0x98 and 0x99 from 0 : 7 to 8: 15
dig_P7 0x9A and 0x9B from 0 : 7 to 8: 15
dig_P8 0x9C and 0x9D from 0 : 7 to 8: 15
dig_P9 0x9E and 0x9F from 0 : 7 to 8: 15
dig_H1 0xA1 from 0 to 7
dig_H2 0xE1 and 0xE2 from 0 : 7 to 8: 15
dig_H3 0xE3 from 0 to 7
Returns
results of bus communication function
Return values
0 -> Success
-1 -> Error
References BME280_CALIB_DATA_SIZE, BME280_HUMIDITY_CALIB_DATA_LENGTH, BME280_HUMIDITY_CALIB_DIG_H1, BME280_HUMIDITY_CALIB_DIG_H2_LSB, BME280_HUMIDITY_CALIB_DIG_H2_LSB_REG, BME280_HUMIDITY_CALIB_DIG_H2_MSB, BME280_HUMIDITY_CALIB_DIG_H3, BME280_HUMIDITY_CALIB_DIG_H4_LSB, BME280_HUMIDITY_CALIB_DIG_H4_MSB, BME280_HUMIDITY_CALIB_DIG_H5_MSB, BME280_HUMIDITY_CALIB_DIG_H6, BME280_INIT_VALUE, BME280_MASK_DIG_H4, BME280_NULL, BME280_PRESSURE_CALIB_DIG_P1_LSB, BME280_PRESSURE_CALIB_DIG_P1_MSB, BME280_PRESSURE_CALIB_DIG_P2_LSB, BME280_PRESSURE_CALIB_DIG_P2_MSB, BME280_PRESSURE_CALIB_DIG_P3_LSB, BME280_PRESSURE_CALIB_DIG_P3_MSB, BME280_PRESSURE_CALIB_DIG_P4_LSB, BME280_PRESSURE_CALIB_DIG_P4_MSB, BME280_PRESSURE_CALIB_DIG_P5_LSB, BME280_PRESSURE_CALIB_DIG_P5_MSB, BME280_PRESSURE_CALIB_DIG_P6_LSB, BME280_PRESSURE_CALIB_DIG_P6_MSB, BME280_PRESSURE_CALIB_DIG_P7_LSB, BME280_PRESSURE_CALIB_DIG_P7_MSB, BME280_PRESSURE_CALIB_DIG_P8_LSB, BME280_PRESSURE_CALIB_DIG_P8_MSB, BME280_PRESSURE_CALIB_DIG_P9_LSB, BME280_PRESSURE_CALIB_DIG_P9_MSB, BME280_PRESSURE_TEMPERATURE_CALIB_DATA_LENGTH, BME280_RETURN_FUNCTION_TYPE, BME280_SHIFT_BIT_POSITION_BY_04_BITS, BME280_SHIFT_BIT_POSITION_BY_08_BITS, BME280_TEMPERATURE_CALIB_DIG_T1_LSB, BME280_TEMPERATURE_CALIB_DIG_T1_LSB_REG, BME280_TEMPERATURE_CALIB_DIG_T1_MSB, BME280_TEMPERATURE_CALIB_DIG_T2_LSB, BME280_TEMPERATURE_CALIB_DIG_T2_MSB, BME280_TEMPERATURE_CALIB_DIG_T3_LSB, BME280_TEMPERATURE_CALIB_DIG_T3_MSB, bme280_t::cal_param, bme280_t::dev_addr, bme280_calibration_param_t::dig_H1, bme280_calibration_param_t::dig_H2, bme280_calibration_param_t::dig_H3, bme280_calibration_param_t::dig_H4, bme280_calibration_param_t::dig_H5, bme280_calibration_param_t::dig_H6, bme280_calibration_param_t::dig_P1, bme280_calibration_param_t::dig_P2, bme280_calibration_param_t::dig_P3, bme280_calibration_param_t::dig_P4, bme280_calibration_param_t::dig_P5, bme280_calibration_param_t::dig_P6, bme280_calibration_param_t::dig_P7, bme280_calibration_param_t::dig_P8, bme280_calibration_param_t::dig_P9, bme280_calibration_param_t::dig_T1, bme280_calibration_param_t::dig_T2, bme280_calibration_param_t::dig_T3, E_BME280_NULL_PTR, and ERROR.
Referenced by bme280_init().
bme280_get_filter()
BME280_RETURN_FUNCTION_TYPE bme280_get_filter (u8 * v_value_u8)
This API is used to reads filter setting in the register 0xF5 bit 3 and 4.
Parameters
v_value_u8 : The value of IIR filter coefficient
value Filter coefficient
0x00 BME280_FILTER_COEFF_OFF
0x01 BME280_FILTER_COEFF_2
0x02 BME280_FILTER_COEFF_4
0x03 BME280_FILTER_COEFF_8
0x04 BME280_FILTER_COEFF_16
Returns
results of bus communication function
Return values
0 -> Success
-1 -> Error
References BME280_CONFIG_REG_FILTER__REG, BME280_GEN_READ_WRITE_DATA_LENGTH, BME280_GET_BITSLICE, BME280_INIT_VALUE, BME280_NULL, BME280_RETURN_FUNCTION_TYPE, bme280_t::dev_addr, E_BME280_NULL_PTR, and ERROR.
bme280_get_forced_uncomp_pressure_temperature_humidity()
BME280_RETURN_FUNCTION_TYPE bme280_get_forced_uncomp_pressure_temperature_humidity (s32 * v_uncom_pressure_s32, s32 * v_uncom_temperature_s32, s32 * v_uncom_humidity_s32)
This API used to read uncompensated temperature,pressure and humidity in forced mode.
Parameters
v_uncom_pressure_s32 The value of uncompensated pressure
v_uncom_temperature_s32 The value of uncompensated temperature
v_uncom_humidity_s32 The value of uncompensated humidity
Returns
results of bus communication function
Return values
0 -> Success
-1 -> Error
References BME280_3MS_DELAY, bme280_compute_wait_time(), BME280_CONFIG_REG, BME280_CTRL_HUMIDITY_REG, BME280_CTRL_MEAS_REG, BME280_FORCED_MODE, BME280_GEN_READ_WRITE_DATA_LENGTH, bme280_get_power_mode(), BME280_INIT_VALUE, BME280_NULL, bme280_read_register(), bme280_read_uncomp_pressure_temperature_humidity(), BME280_RETURN_FUNCTION_TYPE, BME280_SET_BITSLICE, bme280_set_soft_rst(), BME280_SLEEP_MODE, bme280_write_register(), bme280_t::config_reg, bme280_t::ctrl_hum_reg, bme280_t::ctrl_meas_reg, bme280_t::delay_msec, E_BME280_NULL_PTR, and ERROR.
bme280_get_oversamp_humidity()
BME280_RETURN_FUNCTION_TYPE bme280_get_oversamp_humidity (u8 * v_value_u8)
This API is used to get the humidity oversampling setting in the register 0xF2 bits from 0 to 2.
value Humidity oversampling
0x00 Skipped
0x01 BME280_OVERSAMP_1X
0x02 BME280_OVERSAMP_2X
0x03 BME280_OVERSAMP_4X
0x04 BME280_OVERSAMP_8X
0x05,0x06 and 0x07 BME280_OVERSAMP_16X
Parameters
v_value_u8 : The value of humidity over sampling
Returns
results of bus communication function
Return values
0 -> Success
-1 -> Error
References BME280_CTRL_HUMIDITY_REG_OVERSAMP_HUMIDITY__REG, BME280_GEN_READ_WRITE_DATA_LENGTH, BME280_GET_BITSLICE, BME280_INIT_VALUE, BME280_NULL, BME280_RETURN_FUNCTION_TYPE, bme280_t::dev_addr, E_BME280_NULL_PTR, ERROR, and bme280_t::oversamp_humidity.
bme280_get_oversamp_pressure()
BME280_RETURN_FUNCTION_TYPE bme280_get_oversamp_pressure (u8 * v_value_u8)
This API is used to get the pressure oversampling setting in the register 0xF4 bits from 2 to 4.
value Pressure oversampling
0x00 Skipped
0x01 BME280_OVERSAMP_1X
0x02 BME280_OVERSAMP_2X
0x03 BME280_OVERSAMP_4X
0x04 BME280_OVERSAMP_8X
0x05,0x06 and 0x07 BME280_OVERSAMP_16X
Parameters
v_value_u8 : The value of pressure oversampling
Returns
results of bus communication function
Return values
0 -> Success
-1 -> Error
References BME280_CTRL_MEAS_REG_OVERSAMP_PRESSURE__REG, BME280_GEN_READ_WRITE_DATA_LENGTH, BME280_GET_BITSLICE, BME280_INIT_VALUE, BME280_NULL, BME280_RETURN_FUNCTION_TYPE, bme280_t::dev_addr, E_BME280_NULL_PTR, ERROR, and bme280_t::oversamp_pressure.
bme280_get_oversamp_temperature()
BME280_RETURN_FUNCTION_TYPE bme280_get_oversamp_temperature (u8 * v_value_u8)
This API is used to get the temperature oversampling setting in the register 0xF4 bits from 5 to 7.
value Temperature oversampling
0x00 Skipped
0x01 BME280_OVERSAMP_1X
0x02 BME280_OVERSAMP_2X
0x03 BME280_OVERSAMP_4X
0x04 BME280_OVERSAMP_8X
0x05,0x06 and 0x07 BME280_OVERSAMP_16X
Parameters
v_value_u8 : The value of temperature over sampling
Returns
results of bus communication function
Return values
0 -> Success
-1 -> Error
References BME280_CTRL_MEAS_REG_OVERSAMP_TEMPERATURE__REG, BME280_GEN_READ_WRITE_DATA_LENGTH, BME280_GET_BITSLICE, BME280_INIT_VALUE, BME280_NULL, BME280_RETURN_FUNCTION_TYPE, bme280_t::dev_addr, E_BME280_NULL_PTR, ERROR, and bme280_t::oversamp_temperature.
bme280_get_power_mode()
BME280_RETURN_FUNCTION_TYPE bme280_get_power_mode (u8 * v_power_mode_u8)
This API used to get the Operational Mode from the sensor in the register 0xF4 bit 0 and 1.
Parameters
v_power_mode_u8 : The value of power mode
value mode
0x00 BME280_SLEEP_MODE
0x01 and 0x02 BME280_FORCED_MODE
0x03 BME280_NORMAL_MODE
Returns
results of bus communication function
Return values
0 -> Success
-1 -> Error
References BME280_CTRL_MEAS_REG_POWER_MODE__REG, BME280_GEN_READ_WRITE_DATA_LENGTH, BME280_GET_BITSLICE, BME280_INIT_VALUE, BME280_NULL, BME280_RETURN_FUNCTION_TYPE, bme280_t::dev_addr, E_BME280_NULL_PTR, and ERROR.
Referenced by bme280_get_forced_uncomp_pressure_temperature_humidity(), bme280_set_filter(), bme280_set_oversamp_humidity(), bme280_set_oversamp_pressure(), bme280_set_oversamp_temperature(), bme280_set_power_mode(), bme280_set_spi3(), and bme280_set_standby_durn().
bme280_get_spi3()
BME280_RETURN_FUNCTION_TYPE bme280_get_spi3 (u8 * v_enable_disable_u8)
This API used to get the sensor SPI mode(communication type) in the register 0xF5 bit 0.
Parameters
v_enable_disable_u8 : The value of SPI enable
value Description
0 Disable
1 Enable
Returns
results of bus communication function
Return values
0 -> Success
-1 -> Error
References BME280_CONFIG_REG_SPI3_ENABLE__REG, BME280_GEN_READ_WRITE_DATA_LENGTH, BME280_GET_BITSLICE, BME280_INIT_VALUE, BME280_NULL, BME280_RETURN_FUNCTION_TYPE, bme280_t::dev_addr, E_BME280_NULL_PTR, and ERROR.
bme280_get_standby_durn()
BME280_RETURN_FUNCTION_TYPE bme280_get_standby_durn (u8 * v_standby_durn_u8)
This API used to Read the standby duration time from the sensor in the register 0xF5 bit 5 to 7.
Parameters
v_standby_durn_u8 : The value of standby duration time value.
value standby duration
0x00 BME280_STANDBY_TIME_1_MS
0x01 BME280_STANDBY_TIME_63_MS
0x02 BME280_STANDBY_TIME_125_MS
0x03 BME280_STANDBY_TIME_250_MS
0x04 BME280_STANDBY_TIME_500_MS
0x05 BME280_STANDBY_TIME_1000_MS
0x06 BME280_STANDBY_TIME_2000_MS
0x07 BME280_STANDBY_TIME_4000_MS
Returns
results of bus communication function
Return values
0 -> Success
-1 -> Error
References BME280_CONFIG_REG_TSB__REG, BME280_GEN_READ_WRITE_DATA_LENGTH, BME280_GET_BITSLICE, BME280_INIT_VALUE, BME280_NULL, BME280_RETURN_FUNCTION_TYPE, bme280_t::dev_addr, E_BME280_NULL_PTR, and ERROR.
Referenced by bme280_data_readout_template().
bme280_init()
BME280_RETURN_FUNCTION_TYPE bme280_init (struct bme280_t * bme280)
This function is used for initialize the bus read and bus write functions and assign the chip id and I2C address of the BME280 sensor chip id is read in the register 0xD0 bit from 0 to 7.
Parameters
bme280 structure pointer.
Note
While changing the parameter of the bme280_t
consider the following point: Changing the reference value of the parameter will changes the local copy or local reference make sure your changes will not affect the reference value of the parameter (Better case don't change the reference value of the parameter)
Returns
results of bus communication function
Return values
0 -> Success
-1 -> Error
References bme280, BME280_CHIP_ID, BME280_CHIP_ID_READ_COUNT, BME280_CHIP_ID_READ_FAIL, BME280_CHIP_ID_READ_SUCCESS, BME280_CHIP_ID_REG, BME280_GEN_READ_WRITE_DATA_LENGTH, bme280_get_calib_param(), BME280_INIT_VALUE, BME280_REGISTER_READ_DELAY, BME280_RETURN_FUNCTION_TYPE, bme280_t::chip_id, bme280_t::delay_msec, bme280_t::dev_addr, and ERROR.
Referenced by bme280_data_readout_template().
bme280_read_pressure_temperature_humidity()
BME280_RETURN_FUNCTION_TYPE bme280_read_pressure_temperature_humidity (u32 * v_pressure_u32, s32 * v_temperature_s32, u32 * v_humidity_u32)
This API used to read true pressure, temperature and humidity.
Parameters
v_pressure_u32 : The value of compensated pressure.
v_temperature_s32 : The value of compensated temperature.
v_humidity_u32 : The value of compensated humidity.
Returns
results of bus communication function
Return values
0 -> Success
-1 -> Error
References bme280_compensate_humidity_int32(), bme280_compensate_pressure_int32(), bme280_compensate_temperature_int32(), BME280_INIT_VALUE, BME280_NULL, bme280_read_uncomp_pressure_temperature_humidity(), BME280_RETURN_FUNCTION_TYPE, E_BME280_NULL_PTR, and ERROR.
Referenced by bme280_data_readout_template(), coapHandleAmbTemp(), coapHandleHumidity(), and coapHandlePressure().
bme280_read_register()
BME280_RETURN_FUNCTION_TYPE bme280_read_register (u8 v_addr_u8, u8 * v_data_u8, u8 v_len_u8)
This API reads the data from the given register.
Parameters
v_addr_u8 -> Address of the register
v_data_u8 -> The data from the register
v_len_u8 -> no of bytes to read
Returns
results of bus communication function
Return values
0 -> Success
-1 -> Error
References BME280_NULL, BME280_RETURN_FUNCTION_TYPE, bme280_t::dev_addr, E_BME280_NULL_PTR, and ERROR.
Referenced by bme280_get_forced_uncomp_pressure_temperature_humidity(), bme280_set_filter(), bme280_set_oversamp_humidity(), bme280_set_oversamp_pressure(), bme280_set_oversamp_temperature(), bme280_set_power_mode(), bme280_set_spi3(), and bme280_set_standby_durn().
bme280_read_uncomp_humidity()
BME280_RETURN_FUNCTION_TYPE bme280_read_uncomp_humidity (s32 * v_uncomp_humidity_s32)
This API is used to read uncompensated humidity. in the registers 0xF7, 0xF8 and 0xF9.
Note
0xFD -> MSB -> bit from 0 to 7
0xFE -> LSB -> bit from 0 to 7
Parameters
v_uncomp_humidity_s32 : The value of uncompensated humidity
Returns
results of bus communication function
Return values
0 -> Success
-1 -> Error
References BME280_HUMIDITY_DATA_LENGTH, BME280_HUMIDITY_DATA_SIZE, BME280_HUMIDITY_LSB_DATA, BME280_HUMIDITY_MSB_DATA, BME280_HUMIDITY_MSB_REG, BME280_INIT_VALUE, BME280_NULL, BME280_RETURN_FUNCTION_TYPE, BME280_SHIFT_BIT_POSITION_BY_08_BITS, bme280_t::dev_addr, E_BME280_NULL_PTR, and ERROR.
Referenced by bme280_data_readout_template().
bme280_read_uncomp_pressure()
BME280_RETURN_FUNCTION_TYPE bme280_read_uncomp_pressure (s32 * v_uncomp_pressure_s32)
This API is used to read uncompensated pressure. in the registers 0xF7, 0xF8 and 0xF9.
Note
0xF7 -> MSB -> bit from 0 to 7
0xF8 -> LSB -> bit from 0 to 7
0xF9 -> LSB -> bit from 4 to 7
Parameters
v_uncomp_pressure_s32 : The value of uncompensated pressure
Returns
results of bus communication function
Return values
0 -> Success
-1 -> Error
References BME280_INIT_VALUE, BME280_NULL, BME280_PRESSURE_DATA_LENGTH, BME280_PRESSURE_DATA_SIZE, BME280_PRESSURE_LSB_DATA, BME280_PRESSURE_MSB_DATA, BME280_PRESSURE_MSB_REG, BME280_PRESSURE_XLSB_DATA, BME280_RETURN_FUNCTION_TYPE, BME280_SHIFT_BIT_POSITION_BY_04_BITS, BME280_SHIFT_BIT_POSITION_BY_12_BITS, bme280_t::dev_addr, E_BME280_NULL_PTR, and ERROR.
Referenced by bme280_data_readout_template().
bme280_read_uncomp_pressure_temperature_humidity()
BME280_RETURN_FUNCTION_TYPE bme280_read_uncomp_pressure_temperature_humidity (s32 * v_uncomp_pressure_s32, s32 * v_uncomp_temperature_s32, s32 * v_uncomp_humidity_s32)
This API used to read uncompensated pressure,temperature and humidity.
Parameters
v_uncomp_pressure_s32 The value of uncompensated pressure.
v_uncomp_temperature_s32 The value of uncompensated temperature
v_uncomp_humidity_s32 The value of uncompensated humidity.
Returns
results of bus communication function
Return values
0 -> Success
-1 -> Error
References BME280_ALL_DATA_FRAME_LENGTH, BME280_DATA_FRAME_HUMIDITY_LSB_BYTE, BME280_DATA_FRAME_HUMIDITY_MSB_BYTE, BME280_DATA_FRAME_PRESSURE_LSB_BYTE, BME280_DATA_FRAME_PRESSURE_MSB_BYTE, BME280_DATA_FRAME_PRESSURE_XLSB_BYTE, BME280_DATA_FRAME_SIZE, BME280_DATA_FRAME_TEMPERATURE_LSB_BYTE, BME280_DATA_FRAME_TEMPERATURE_MSB_BYTE, BME280_DATA_FRAME_TEMPERATURE_XLSB_BYTE, BME280_INIT_VALUE, BME280_NULL, BME280_PRESSURE_MSB_REG, BME280_RETURN_FUNCTION_TYPE, BME280_SHIFT_BIT_POSITION_BY_04_BITS, BME280_SHIFT_BIT_POSITION_BY_08_BITS, BME280_SHIFT_BIT_POSITION_BY_12_BITS, bme280_t::dev_addr, E_BME280_NULL_PTR, and ERROR.
Referenced by bme280_data_readout_template(), bme280_get_forced_uncomp_pressure_temperature_humidity(), and bme280_read_pressure_temperature_humidity().
bme280_read_uncomp_temperature()
BME280_RETURN_FUNCTION_TYPE bme280_read_uncomp_temperature (s32 * v_uncomp_temperature_s32)
This API is used to read uncompensated temperature in the registers 0xFA, 0xFB and 0xFC.
Note
0xFA -> MSB -> bit from 0 to 7
0xFB -> LSB -> bit from 0 to 7
0xFC -> LSB -> bit from 4 to 7
Parameters
v_uncomp_temperature_s32 : The value of uncompensated temperature
Returns
results of bus communication function
Return values
0 -> Success
-1 -> Error
References BME280_INIT_VALUE, BME280_NULL, BME280_RETURN_FUNCTION_TYPE, BME280_SHIFT_BIT_POSITION_BY_04_BITS, BME280_SHIFT_BIT_POSITION_BY_12_BITS, BME280_TEMPERATURE_DATA_LENGTH, BME280_TEMPERATURE_DATA_SIZE, BME280_TEMPERATURE_LSB_DATA, BME280_TEMPERATURE_MSB_DATA, BME280_TEMPERATURE_MSB_REG, BME280_TEMPERATURE_XLSB_DATA, bme280_t::dev_addr, E_BME280_NULL_PTR, and ERROR.
Referenced by bme280_data_readout_template().
bme280_set_filter()
BME280_RETURN_FUNCTION_TYPE bme280_set_filter (u8 v_value_u8)
This API is used to write filter setting in the register 0xF5 bit 3 and 4.
Parameters
v_value_u8 : The value of IIR filter coefficient
value Filter coefficient
0x00 BME280_FILTER_COEFF_OFF
0x01 BME280_FILTER_COEFF_2
0x02 BME280_FILTER_COEFF_4
0x03 BME280_FILTER_COEFF_8
0x04 BME280_FILTER_COEFF_16
Returns
results of bus communication function
Return values
0 -> Success
-1 -> Error
References BME280_3MS_DELAY, BME280_CONFIG_REG, BME280_CONFIG_REG_FILTER__REG, BME280_CTRL_HUMIDITY_REG, BME280_CTRL_MEAS_REG, BME280_GEN_READ_WRITE_DATA_LENGTH, bme280_get_power_mode(), BME280_INIT_VALUE, BME280_NULL, bme280_read_register(), BME280_RETURN_FUNCTION_TYPE, BME280_SET_BITSLICE, bme280_set_soft_rst(), BME280_SLEEP_MODE, bme280_write_register(), bme280_t::config_reg, bme280_t::ctrl_hum_reg, bme280_t::ctrl_meas_reg, bme280_t::delay_msec, bme280_t::dev_addr, E_BME280_NULL_PTR, and ERROR.
bme280_set_oversamp_humidity()
BME280_RETURN_FUNCTION_TYPE bme280_set_oversamp_humidity (u8 v_value_u8)
This API is used to set the humidity oversampling setting in the register 0xF2 bits from 0 to 2.
value Humidity oversampling
0x00 Skipped
0x01 BME280_OVERSAMP_1X
0x02 BME280_OVERSAMP_2X
0x03 BME280_OVERSAMP_4X
0x04 BME280_OVERSAMP_8X
0x05,0x06 and 0x07 BME280_OVERSAMP_16X
Parameters
v_value_u8 : The value of humidity over sampling
Note
The "BME280_CTRL_HUMIDITY_REG_OVERSAMP_HUMIDITY" register sets the humidity data acquisition options of the device.
changes to this registers only become effective after a write operation to "BME280_CTRL_MEAS_REG" register.
In the code automated reading and writing of "BME280_CTRL_HUMIDITY_REG_OVERSAMP_HUMIDITY"
register first set the "BME280_CTRL_HUMIDITY_REG_OVERSAMP_HUMIDITY" and then read and write the "BME280_CTRL_MEAS_REG" register in the function.
Returns
results of bus communication function
Return values
0 -> Success
-1 -> Error
References BME280_3MS_DELAY, BME280_CONFIG_REG, BME280_CTRL_HUMIDITY_REG, BME280_CTRL_HUMIDITY_REG_OVERSAMP_HUMIDITY__REG, BME280_CTRL_MEAS_REG, BME280_GEN_READ_WRITE_DATA_LENGTH, bme280_get_power_mode(), BME280_INIT_VALUE, BME280_NULL, bme280_read_register(), BME280_RETURN_FUNCTION_TYPE, BME280_SET_BITSLICE, bme280_set_soft_rst(), BME280_SLEEP_MODE, bme280_write_register(), bme280_t::config_reg, bme280_t::ctrl_hum_reg, bme280_t::ctrl_meas_reg, bme280_t::delay_msec, bme280_t::dev_addr, E_BME280_NULL_PTR, ERROR, and bme280_t::oversamp_humidity.
Referenced by bme280_data_readout_template().
bme280_set_oversamp_pressure()
BME280_RETURN_FUNCTION_TYPE bme280_set_oversamp_pressure (u8 v_value_u8)
This API is used to set the pressure oversampling setting in the register 0xF4 bits from 2 to 4.
value Pressure oversampling
0x00 Skipped
0x01 BME280_OVERSAMP_1X
0x02 BME280_OVERSAMP_2X
0x03 BME280_OVERSAMP_4X
0x04 BME280_OVERSAMP_8X
0x05,0x06 and 0x07 BME280_OVERSAMP_16X
Parameters
v_value_u8 : The value of pressure oversampling
Returns
results of bus communication function
Return values
0 -> Success
-1 -> Error
References BME280_3MS_DELAY, BME280_CONFIG_REG, BME280_CTRL_HUMIDITY_REG, BME280_CTRL_MEAS_REG, BME280_CTRL_MEAS_REG_OVERSAMP_PRESSURE__REG, BME280_GEN_READ_WRITE_DATA_LENGTH, bme280_get_power_mode(), BME280_INIT_VALUE, BME280_NULL, bme280_read_register(), BME280_RETURN_FUNCTION_TYPE, BME280_SET_BITSLICE, bme280_set_soft_rst(), BME280_SLEEP_MODE, bme280_write_register(), bme280_t::config_reg, bme280_t::ctrl_hum_reg, bme280_t::ctrl_meas_reg, bme280_t::delay_msec, bme280_t::dev_addr, E_BME280_NULL_PTR, ERROR, and bme280_t::oversamp_pressure.
Referenced by bme280_data_readout_template().
bme280_set_oversamp_temperature()
BME280_RETURN_FUNCTION_TYPE bme280_set_oversamp_temperature (u8 v_value_u8)
This API is used to set the temperature oversampling setting in the register 0xF4 bits from 5 to 7.
value Temperature oversampling
0x00 Skipped
0x01 BME280_OVERSAMP_1X
0x02 BME280_OVERSAMP_2X
0x03 BME280_OVERSAMP_4X
0x04 BME280_OVERSAMP_8X
0x05,0x06 and 0x07 BME280_OVERSAMP_16X
Parameters
v_value_u8 : The value of temperature over sampling
Returns
results of bus communication function
Return values
0 -> Success
-1 -> Error
References BME280_3MS_DELAY, BME280_CONFIG_REG, BME280_CTRL_HUMIDITY_REG, BME280_CTRL_MEAS_REG, BME280_CTRL_MEAS_REG_OVERSAMP_TEMPERATURE__REG, BME280_GEN_READ_WRITE_DATA_LENGTH, bme280_get_power_mode(), BME280_INIT_VALUE, BME280_NULL, bme280_read_register(), BME280_RETURN_FUNCTION_TYPE, BME280_SET_BITSLICE, bme280_set_soft_rst(), BME280_SLEEP_MODE, bme280_write_register(), bme280_t::config_reg, bme280_t::ctrl_hum_reg, bme280_t::ctrl_meas_reg, bme280_t::delay_msec, bme280_t::dev_addr, E_BME280_NULL_PTR, ERROR, and bme280_t::oversamp_temperature.
Referenced by bme280_data_readout_template().
bme280_set_power_mode()
BME280_RETURN_FUNCTION_TYPE bme280_set_power_mode (u8 v_power_mode_u8)
This API used to set the Operational Mode from the sensor in the register 0xF4 bit 0 and 1.
Parameters
v_power_mode_u8 : The value of power mode
value mode
0x00 BME280_SLEEP_MODE
0x01 and 0x02 BME280_FORCED_MODE
0x03 BME280_NORMAL_MODE
Returns
results of bus communication function
Return values
0 -> Success
-1 -> Error
References BME280_3MS_DELAY, BME280_CONFIG_REG, BME280_CTRL_HUMIDITY_REG, BME280_CTRL_MEAS_REG, BME280_CTRL_MEAS_REG_POWER_MODE__REG, BME280_GEN_READ_WRITE_DATA_LENGTH, bme280_get_power_mode(), BME280_INIT_VALUE, BME280_NORMAL_MODE, BME280_NULL, bme280_read_register(), BME280_RETURN_FUNCTION_TYPE, BME280_SET_BITSLICE, bme280_set_soft_rst(), BME280_SLEEP_MODE, bme280_write_register(), bme280_t::config_reg, bme280_t::ctrl_hum_reg, bme280_t::ctrl_meas_reg, bme280_t::delay_msec, bme280_t::dev_addr, E_BME280_NULL_PTR, E_BME280_OUT_OF_RANGE, and ERROR.
Referenced by bme280_data_readout_template(), and initBME().
bme280_set_soft_rst()
BME280_RETURN_FUNCTION_TYPE bme280_set_soft_rst (void)
Used to reset the sensor The value 0xB6 is written to the 0xE0 register the device is reset using the complete power-on-reset procedure.
Note
Soft reset can be easily set using bme280_set_softreset().
Usage Hint : bme280_set_softreset()
Returns
results of bus communication function
Return values
0 -> Success
-1 -> Error
References BME280_GEN_READ_WRITE_DATA_LENGTH, BME280_NULL, BME280_RETURN_FUNCTION_TYPE, BME280_RST_REG, BME280_SOFT_RESET_CODE, bme280_t::dev_addr, E_BME280_NULL_PTR, and ERROR.
Referenced by bme280_get_forced_uncomp_pressure_temperature_humidity(), bme280_set_filter(), bme280_set_oversamp_humidity(), bme280_set_oversamp_pressure(), bme280_set_oversamp_temperature(), bme280_set_power_mode(), bme280_set_spi3(), and bme280_set_standby_durn().
bme280_set_spi3()
BME280_RETURN_FUNCTION_TYPE bme280_set_spi3 (u8 v_enable_disable_u8)
This API used to set the sensor SPI mode(communication type) in the register 0xF5 bit 0.
Parameters
v_enable_disable_u8 : The value of SPI enable
value Description
0 Disable
1 Enable
Returns
results of bus communication function
Return values
0 -> Success
-1 -> Error
References BME280_3MS_DELAY, BME280_CONFIG_REG, BME280_CONFIG_REG_SPI3_ENABLE__REG, BME280_CTRL_HUMIDITY_REG, BME280_CTRL_MEAS_REG, BME280_GEN_READ_WRITE_DATA_LENGTH, bme280_get_power_mode(), BME280_INIT_VALUE, BME280_NULL, bme280_read_register(), BME280_RETURN_FUNCTION_TYPE, BME280_SET_BITSLICE, bme280_set_soft_rst(), BME280_SLEEP_MODE, bme280_write_register(), bme280_t::config_reg, bme280_t::ctrl_hum_reg, bme280_t::ctrl_meas_reg, bme280_t::delay_msec, bme280_t::dev_addr, E_BME280_NULL_PTR, and ERROR.
bme280_set_standby_durn()
BME280_RETURN_FUNCTION_TYPE bme280_set_standby_durn (u8 v_standby_durn_u8)
This API used to write the standby duration time from the sensor in the register 0xF5 bit 5 to 7.
Parameters
v_standby_durn_u8 : The value of standby duration time value.
value standby duration
0x00 BME280_STANDBY_TIME_1_MS
0x01 BME280_STANDBY_TIME_63_MS
0x02 BME280_STANDBY_TIME_125_MS
0x03 BME280_STANDBY_TIME_250_MS
0x04 BME280_STANDBY_TIME_500_MS
0x05 BME280_STANDBY_TIME_1000_MS
0x06 BME280_STANDBY_TIME_2000_MS
0x07 BME280_STANDBY_TIME_4000_MS
Note
Normal mode comprises an automated perpetual cycling between an (active) Measurement period and an (inactive) standby period.
The standby time is determined by the contents of the register t_sb. Standby time can be set using BME280_STANDBY_TIME_125_MS.
Usage Hint : bme280_set_standby_durn(BME280_STANDBY_TIME_125_MS)
Returns
results of bus communication function
Return values
0 -> Success
-1 -> Error
References BME280_3MS_DELAY, BME280_CONFIG_REG, BME280_CONFIG_REG_TSB__REG, BME280_CTRL_HUMIDITY_REG, BME280_CTRL_MEAS_REG, BME280_GEN_READ_WRITE_DATA_LENGTH, bme280_get_power_mode(), BME280_INIT_VALUE, BME280_NULL, bme280_read_register(), BME280_RETURN_FUNCTION_TYPE, BME280_SET_BITSLICE, bme280_set_soft_rst(), BME280_SLEEP_MODE, bme280_write_register(), bme280_t::config_reg, bme280_t::ctrl_hum_reg, bme280_t::ctrl_meas_reg, bme280_t::delay_msec, bme280_t::dev_addr, E_BME280_NULL_PTR, and ERROR.
Referenced by bme280_data_readout_template().
bme280_write_register()
BME280_RETURN_FUNCTION_TYPE bme280_write_register (u8 v_addr_u8, u8 * v_data_u8, u8 v_len_u8)
This API write the data to the given register.
Parameters
v_addr_u8 -> Address of the register
v_data_u8 -> The data from the register
v_len_u8 -> no of bytes to read
Returns
results of bus communication function
Return values
0 -> Success
-1 -> Error
References BME280_NULL, BME280_RETURN_FUNCTION_TYPE, bme280_t::dev_addr, E_BME280_NULL_PTR, and ERROR.
Referenced by bme280_get_forced_uncomp_pressure_temperature_humidity(), bme280_set_filter(), bme280_set_oversamp_humidity(), bme280_set_oversamp_pressure(), bme280_set_oversamp_temperature(), bme280_set_power_mode(), bme280_set_spi3(), and bme280_set_standby_durn().
Variable Documentation
p_bme280
struct bme280_t* p_bme280 static
pointer to BME280
© Copyright 1995-2018, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale