TI Thread API Documentation: examples/sensors/bme280_support.c File Reference
bme280_support.c File Reference
Macros
#define BME280_ADDRESS_INDEX 2
#define BME280_API
#define BME280_DATA_INDEX 1
#define DebugP_ASSERT_ENABLED 0
#define DebugP_LOG_ENABLED 0
#define I2C_BUFFER_LEN 8
Functions
s32 bme280_data_readout_template (I2C_Handle i2cHndl)
void BME280_delay_msek (u32 msek)
s8 BME280_I2C_bus_read (u8 dev_addr, u8 reg_addr, u8 *reg_data, u8 cnt)
s8 BME280_I2C_bus_write (u8 dev_addr, u8 reg_addr, u8 *reg_data, u8 cnt)
s8 I2C_routine (void)
Variables
struct bme280_t bme280
static I2C_Handle i2cHandle = NULL
Macro Definition Documentation
BME280_ADDRESS_INDEX
#define BME280_ADDRESS_INDEX 2
BME280_API
#define BME280_API
BME280_DATA_INDEX
#define BME280_DATA_INDEX 1
Referenced by BME280_I2C_bus_write().
DebugP_ASSERT_ENABLED
#define DebugP_ASSERT_ENABLED 0
DebugP_LOG_ENABLED
#define DebugP_LOG_ENABLED 0
I2C_BUFFER_LEN
#define I2C_BUFFER_LEN 8
Referenced by BME280_I2C_bus_write().
Function Documentation
bme280_data_readout_template()
s32 bme280_data_readout_template (I2C_Handle i2cHndl)
References bme280, bme280_compensate_humidity_int32(), bme280_compensate_pressure_int32(), bme280_compensate_temperature_int32(), bme280_get_standby_durn(), bme280_init(), BME280_INIT_VALUE, BME280_NORMAL_MODE, BME280_OVERSAMP_1X, BME280_OVERSAMP_2X, BME280_OVERSAMP_4X, bme280_read_pressure_temperature_humidity(), bme280_read_uncomp_humidity(), bme280_read_uncomp_pressure(), bme280_read_uncomp_pressure_temperature_humidity(), bme280_read_uncomp_temperature(), bme280_set_oversamp_humidity(), bme280_set_oversamp_pressure(), bme280_set_oversamp_temperature(), bme280_set_power_mode(), bme280_set_standby_durn(), BME280_SLEEP_MODE, BME280_STANDBY_TIME_1_MS, ERROR, I2C_routine(), and i2cHandle.
Referenced by initBME().
BME280_delay_msek()
void BME280_delay_msek (u32 msek)
Referenced by I2C_routine().
BME280_I2C_bus_read()
s8 BME280_I2C_bus_read (u8 dev_addr, u8 reg_addr, u8 * reg_data, u8 cnt)
References bme280_t::dev_addr, and i2cHandle.
Referenced by I2C_routine().
BME280_I2C_bus_write()
s8 BME280_I2C_bus_write (u8 dev_addr, u8 reg_addr, u8 * reg_data, u8 cnt)
References BME280_DATA_INDEX, BME280_INIT_VALUE, bme280_t::dev_addr, I2C_BUFFER_LEN, and i2cHandle.
Referenced by I2C_routine().
I2C_routine()
s8 I2C_routine (void)
References bme280, BME280_delay_msek(), BME280_I2C_ADDRESS2, BME280_I2C_bus_read(), BME280_I2C_bus_write(), BME280_INIT_VALUE, bme280_t::delay_msec, and bme280_t::dev_addr.
Referenced by bme280_data_readout_template().
Variable Documentation
bme280
struct bme280_t bme280
Referenced by bme280_data_readout_template(), bme280_init(), and I2C_routine().
i2cHandle
I2C_Handle i2cHandle = NULL static
Referenced by bme280_data_readout_template(), BME280_I2C_bus_read(), BME280_I2C_bus_write(), OPT3001_init(), OPT3001_open(), taskInit(), TMP007_getObjTempLimit(), TMP007_init(), and TMP007_open().
© Copyright 1995-2018, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale