TI Thread API Documentation: examples/cli/cli.c File Reference
cli.c File Reference
Functions
void * cli_task (void *arg0)
void cli_taskCreate (void)
void otPlatLog (otLogLevel aLogLevel, otLogRegion aLogRegion, const char *aFormat,...)
static void resetPriority (void)
Variables
static char cli_stack [TASK_CONFIG_CLI_TASK_STACK_SIZE]
Function Documentation
cli_task()
void * cli_task (void * arg0)
Main thread starting the CLI example within OpenThread.
References OtInstance_get(), OtRtosApi_lock(), OtRtosApi_unlock(), and resetPriority().
Referenced by cli_taskCreate().
cli_taskCreate()
void cli_taskCreate (void)
Documented in task_config.h.
References cli_stack, cli_task(), and TASK_CONFIG_CLI_TASK_STACK_SIZE.
Referenced by main().
otPlatLog()
void otPlatLog (otLogLevel aLogLevel, otLogRegion aLogRegion, const char * aFormat, ...)
References OtRtosApi_lock(), and OtRtosApi_unlock().
Referenced by otPlatDiagAlarmCallback(), and otPlatDiagRadioReceived().
resetPriority()
static void resetPriority (void) static
Return thread priority after initialization.
References TASK_CONFIG_CLI_TASK_PRIORITY.
Referenced by cli_task().
Variable Documentation
cli_stack
char cli_stack[TASK_CONFIG_CLI_TASK_STACK_SIZE] static
Referenced by cli_taskCreate().
© Copyright 1995-2018, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale