TI Thread API Documentation: examples/cli/otstack.c File Reference
otstack.c File Reference
Macros
#define OT_STACK_EVENT_SIGNAL_ALARM_PROCESS Event_Id_00
#define OT_STACK_EVENT_SIGNAL_ALARMU_PROCESS Event_Id_05
#define OT_STACK_EVENT_SIGNAL_RADIO_PROCESS Event_Id_01
#define OT_STACK_EVENT_SIGNAL_RANDOM_PROCESS Event_Id_04
#define OT_STACK_EVENT_SIGNAL_TASLETS_PENDING Event_Id_02
#define OT_STACK_EVENT_SIGNAL_UART_PROCESS Event_Id_03
Functions
otInstance * OtInstance_get (void)
void * OtStack_task (void *arg0)
void OtStack_taskCreate (void)
void otTaskletsSignalPending (otInstance *aInstance)
void platformAlarmMicroSignal ()
void platformAlarmSignal ()
void platformRadioSignal ()
void platformRandomSignal (void)
void platformUartSignal ()
static void resetPriority (void)
Variables
static Event_Struct OtStack_events
static otInstance * OtStack_instance
static char OtStack_stack [TASK_CONFIG_OT_TASK_STACK_SIZE]
Macro Definition Documentation
OT_STACK_EVENT_SIGNAL_ALARM_PROCESS
#define OT_STACK_EVENT_SIGNAL_ALARM_PROCESS Event_Id_00
Referenced by OtStack_task(), and platformAlarmSignal().
OT_STACK_EVENT_SIGNAL_ALARMU_PROCESS
#define OT_STACK_EVENT_SIGNAL_ALARMU_PROCESS Event_Id_05
Referenced by OtStack_task(), and platformAlarmMicroSignal().
OT_STACK_EVENT_SIGNAL_RADIO_PROCESS
#define OT_STACK_EVENT_SIGNAL_RADIO_PROCESS Event_Id_01
Referenced by OtStack_task(), and platformRadioSignal().
OT_STACK_EVENT_SIGNAL_RANDOM_PROCESS
#define OT_STACK_EVENT_SIGNAL_RANDOM_PROCESS Event_Id_04
Referenced by OtStack_task(), and platformRandomSignal().
OT_STACK_EVENT_SIGNAL_TASLETS_PENDING
#define OT_STACK_EVENT_SIGNAL_TASLETS_PENDING Event_Id_02
Referenced by OtStack_task(), and otTaskletsSignalPending().
OT_STACK_EVENT_SIGNAL_UART_PROCESS
#define OT_STACK_EVENT_SIGNAL_UART_PROCESS Event_Id_03
Referenced by OtStack_task(), and platformUartSignal().
Function Documentation
OtInstance_get()
otInstance* OtInstance_get (void)
Documented in otsupport/otinstance.h.
Referenced by cli_task(), DoorLock_task(), ncp_task(), processEvents(), Shade_task(), TempSensor_task(), tempSensorReport(), and Thermostat_task().
OtStack_task()
void * OtStack_task (void * arg0)
Main processing thread for OpenThread Stack.
References OT_STACK_EVENT_SIGNAL_ALARM_PROCESS, OT_STACK_EVENT_SIGNAL_ALARMU_PROCESS, OT_STACK_EVENT_SIGNAL_RADIO_PROCESS, OT_STACK_EVENT_SIGNAL_RANDOM_PROCESS, OT_STACK_EVENT_SIGNAL_TASLETS_PENDING, OT_STACK_EVENT_SIGNAL_UART_PROCESS, OtRtosApi_init(), OtRtosApi_lock(), OtRtosApi_unlock(), OtStack_events, OtStack_instance, platformAlarmMicroProcess(), platformAlarmProcess(), PlatformInit(), platformRadioProcess(), platformRandomProcess(), platformUartProcess(), and resetPriority().
Referenced by OtStack_taskCreate().
OtStack_taskCreate()
void OtStack_taskCreate (void)
Documented in task_config.h.
Referenced by main().
otTaskletsSignalPending()
void otTaskletsSignalPending (otInstance * aInstance)
Callback from OpenThread stack to indicate tasklets are pending processing.
References OT_STACK_EVENT_SIGNAL_TASLETS_PENDING, and OtStack_events.
platformAlarmMicroSignal()
void platformAlarmMicroSignal (void)
Callback from the alarm module indicating need for processing.
Referenced by AlarmMicro_handler(), otPlatAlarmMicroStartAt(), and platformAlarmMicroProcess().
platformAlarmSignal()
void platformAlarmSignal (void)
Callback from the alarm module indicating need for processing.
Referenced by Alarm_handler(), otPlatAlarmMilliStartAt(), and platformAlarmProcess().
platformRadioSignal()
void platformRadioSignal (void)
Callback from the radio module indicating need for processing.
platformRandomSignal()
void platformRandomSignal (void)
Callback from the random generator module indicating need for processing.
Referenced by getRandom().
platformUartSignal()
void platformUartSignal (void)
Callback from the alarm module indicating need for processing.
Referenced by uartReadCallback(), and uartWriteCallback().
resetPriority()
static void resetPriority (void) static
Return thread priority after initialization.
References TASK_CONFIG_OT_TASK_PRIORITY.
Referenced by OtStack_task().
Variable Documentation
OtStack_events
Event_Struct OtStack_events static
Referenced by OtStack_task(), otTaskletsSignalPending(), platformAlarmMicroSignal(), platformAlarmSignal(), platformRadioSignal(), platformRandomSignal(), and platformUartSignal().
OtStack_instance
otInstance* OtStack_instance static
Referenced by OtInstance_get(), and OtStack_task().
OtStack_stack
char OtStack_stack[TASK_CONFIG_OT_TASK_STACK_SIZE] static
Referenced by OtStack_taskCreate().
© Copyright 1995-2018, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale