TI Thread API Documentation: examples/nv/crc.h File Reference
crc.h File Reference
Detailed Description
Functions and types for CRC checks.
Width = 8
Poly = 0x97
XorIn = 0x00
ReflectIn = False
XorOut = 0x00
ReflectOut = False
Algorithm = table-driven
This file defines the functions crc_init(), crc_update() and crc_finalize().
The crc_init() function returns the inital crc value and must be called before the first call to crc_update(). Similarly, the crc_finalize() function must be called after the last call to crc_update(), before the crc is being used. is being used.
The crc_update() function can be called any number of times (including zero times) in between the crc_init() and crc_finalize() calls.
This pseudo-code shows an example usage of the API:
crc_t crc;
unsigned char data[MAX_DATA_LEN];
size_t data_len;
crc = crc_init();
while ((data_len = read_data(data, MAX_DATA_LEN)) > 0) {
    crc = crc_update(crc, data, data_len);
}
crc = crc_finalize(crc);
Macros
#define CRC_ALGO_TABLE_DRIVEN 1
Typedefs
typedef uint8_t crc_t
Functions
static crc_t crc_finalize (crc_t crc)
static crc_t crc_init (void)
crc_t crc_update (crc_t crc, const void *data, size_t data_len)
Macro Definition Documentation
CRC_ALGO_TABLE_DRIVEN
#define CRC_ALGO_TABLE_DRIVEN 1
The definition of the used algorithm.
This is not used anywhere in the generated code, but it may be used by the application code to call algorithm-specific code, if desired.
Typedef Documentation
crc_t
typedef uint8_t crc_t
The type of the CRC values.
This type must be big enough to contain at least 8 bits.
Function Documentation
crc_finalize()
static crc_t crc_finalize (crc_t crc) inline static
Calculate the final crc value.
Parameters
[in] crc The current crc value.
Returns
The final crc value.
crc_init()
static crc_t crc_init (void) inline static
Calculate the initial crc value.
Returns
The initial crc value.
References crc_update().
crc_update()
crc_t crc_update (crc_t crc, const void * data, size_t data_len)
Update the crc value with new data.
Parameters
[in] crc The current crc value.
[in] data Pointer to a buffer of data_len bytes.
[in] data_len Number of bytes in the data buffer.
Returns
The updated crc value.
References crc_table.
Referenced by crc_init(), NVOCTP_doNVCRC(), and NVOCTP_doRAMCRC().
© Copyright 1995-2018, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale