TI Thread API Documentation: examples/platform/diag.c File Reference
diag.c File Reference
Macros
#define PLAT_DIAG_TX_INTERFRAME 100
#define PLAT_DIAG_TX_PACKETSIZE 30
Functions
void otPlatDiagAlarmCallback (otInstance *aInstance)
void otPlatDiagChannelSet (uint8_t aChannel)
bool otPlatDiagModeGet ()
void otPlatDiagModeSet (bool aMode)
void otPlatDiagProcess (otInstance *aInstance, int argc, char *argv[], char *aOutput, size_t aOutputMaxLen)
void otPlatDiagRadioReceived (otInstance *aInstance, otRadioFrame *aFrame, otError aError)
void otPlatDiagTxPowerSet (int8_t aTxPower)
unsigned int PlatDiag_calculatePER (void)
otError PlatDiag_parseLong (char *aArgVector, long *aValue)
otError PlatDiag_processReceive (otInstance *aInstance, int argc, char *argv[], char *aOutput, size_t aOutputMaxLen)
otError PlatDiag_processShield (otInstance *aInstance, int argc, char *argv[], char *aOutput, size_t aOutputMaxLen)
otError PlatDiag_processTone (otInstance *aInstance, int argc, char *argv[], char *aOutput, size_t aOutputMaxLen)
otError PlatDiag_processTransmit (otInstance *aInstance, int argc, char *argv[], char *aOutput, size_t aOutputMaxLen)
Variables
static uint8_t PlatDiag_channel
static bool PlatDiag_diagEnabled = false
static bool PlatDiag_rxEnabled = false
static uint16_t PlatDiag_rxExpectedSeqNo
static uint16_t PlatDiag_rxFrameCount
static uint16_t PlatDiag_rxLostFrames
static uint16_t PlatDiag_rxNokCount
static uint16_t PlatDiag_rxReceivedCount
static bool PlatDiag_txEnabled = false
static uint16_t PlatDiag_txFrameCount
static uint16_t PlatDiag_txFrameSize
static uint32_t PlatDiag_txPeriod
static uint16_t PlatDiag_txSentCount
Macro Definition Documentation
PLAT_DIAG_TX_INTERFRAME
#define PLAT_DIAG_TX_INTERFRAME 100
Default interframe spacing used for transmission command.
Referenced by PlatDiag_processTransmit().
PLAT_DIAG_TX_PACKETSIZE
#define PLAT_DIAG_TX_PACKETSIZE 30
Default packet size used for transmission command.
Referenced by PlatDiag_processTransmit().
Function Documentation
otPlatDiagAlarmCallback()
void otPlatDiagAlarmCallback (otInstance * aInstance)
Documented in <openthread/platform/diag.h>
References otPlatAlarmMilliGetNow(), otPlatAlarmMilliStartAt(), otPlatLog(), PlatDiag_channel, PlatDiag_txEnabled, PlatDiag_txFrameCount, PlatDiag_txFrameSize, PlatDiag_txPeriod, and PlatDiag_txSentCount.
otPlatDiagChannelSet()
void otPlatDiagChannelSet (uint8_t aChannel)
Documented in <openthread/platform/diag.h>
References PlatDiag_channel.
otPlatDiagModeGet()
bool otPlatDiagModeGet ()
Documented in <openthread/platform/diag.h>
References PlatDiag_diagEnabled.
Referenced by platformAlarmProcess().
otPlatDiagModeSet()
void otPlatDiagModeSet (bool aMode)
Documented in <openthread/platform/diag.h>
References PlatDiag_diagEnabled.
otPlatDiagProcess()
void otPlatDiagProcess (otInstance * aInstance, int argc, char * argv[], char * aOutput, size_t aOutputMaxLen)
Documented in <openthread/platform/diag.h>
References PlatDiag_processReceive(), PlatDiag_processShield(), PlatDiag_processTone(), and PlatDiag_processTransmit().
otPlatDiagRadioReceived()
void otPlatDiagRadioReceived (otInstance * aInstance, otRadioFrame * aFrame, otError aError)
Documented in <openthread/platform/diag.h>
References otPlatLog(), PlatDiag_rxEnabled, PlatDiag_rxExpectedSeqNo, PlatDiag_rxFrameCount, PlatDiag_rxLostFrames, PlatDiag_rxNokCount, and PlatDiag_rxReceivedCount.
otPlatDiagTxPowerSet()
void otPlatDiagTxPowerSet (int8_t aTxPower)
Documented in <openthread/platform/diag.h>
PlatDiag_calculatePER()
unsigned int PlatDiag_calculatePER (void)
Helper function to calculate the Packet Error Rate.
PER value based on PlatDiag_rxFrameCount PlatDiag_rxReceivedCount PlatDiag_rxNokCount and PlatDiag_rxLostFrames.
Returns
Packet Error Rate.
References PlatDiag_rxFrameCount, PlatDiag_rxLostFrames, PlatDiag_rxNokCount, and PlatDiag_rxReceivedCount.
Referenced by PlatDiag_processReceive().
PlatDiag_parseLong()
otError PlatDiag_parseLong (char * aArgVector, long * aValue)
Helper function to parse strings into long variables and mark errors.
Parameters
[in] aArgVector C string to parse.
[out] aValue address of long container.
Return values
OT_ERROR_NONE The string was parsed correctly.
OT_ERROR_PARSE The string was not formatted correctly.
Referenced by PlatDiag_processReceive(), PlatDiag_processShield(), and PlatDiag_processTransmit().
PlatDiag_processReceive()
otError PlatDiag_processReceive (otInstance * aInstance, int argc, char * argv[], char * aOutput, size_t aOutputMaxLen)
Process the diag receive command.
Parameters
[in] aInstance OpenThread instance structure.
[in] argc Count of command arguments.
[in] argv Array of command arguments.
[out] aOutput Output buffer used for user interaction.
[in] aOutputMaxLen Size of the Output buffer.
Returns
Error value from parsing or executing the command.
References PlatDiag_calculatePER(), PlatDiag_diagEnabled, PlatDiag_parseLong(), PlatDiag_rxEnabled, PlatDiag_rxExpectedSeqNo, PlatDiag_rxFrameCount, PlatDiag_rxLostFrames, PlatDiag_rxNokCount, PlatDiag_rxReceivedCount, and PlatDiag_txEnabled.
Referenced by otPlatDiagProcess().
PlatDiag_processShield()
otError PlatDiag_processShield (otInstance * aInstance, int argc, char * argv[], char * aOutput, size_t aOutputMaxLen)
Process the diag shield command.
Parameters
[in] aInstance OpenThread instance structure.
[in] argc Count of command arguments.
[in] argv Array of command arguments.
[out] aOutput Output buffer used for user interaction.
[in] aOutputMaxLen Size of the Output buffer.
Returns
Error value from parsing or executing the command.
References PlatDiag_parseLong(), rfCoreDiagChannelDisable(), and rfCoreDiagChannelEnable().
Referenced by otPlatDiagProcess().
PlatDiag_processTone()
otError PlatDiag_processTone (otInstance * aInstance, int argc, char * argv[], char * aOutput, size_t aOutputMaxLen)
Process the diag tone command.
Parameters
[in] aInstance OpenThread instance structure.
[in] argc Count of command arguments.
[in] argv Array of command arguments.
[out] aOutput Output buffer used for user interaction.
[in] aOutputMaxLen Size of the Output buffer.
Returns
Error value from parsing or executing the command.
References otPlatDiagRadioToneStart(), otPlatDiagRadioToneStop(), and PlatDiag_diagEnabled.
Referenced by otPlatDiagProcess().
PlatDiag_processTransmit()
otError PlatDiag_processTransmit (otInstance * aInstance, int argc, char * argv[], char * aOutput, size_t aOutputMaxLen)
Process the diag transmit command.
Parameters
[in] aInstance OpenThread instance structure.
[in] argc Count of command arguments.
[in] argv Array of command arguments.
[out] aOutput Output buffer used for user interaction.
[in] aOutputMaxLen Size of the Output buffer.
Returns
Error value from parsing or executing the command.
References otPlatAlarmMilliGetNow(), otPlatAlarmMilliStartAt(), otPlatAlarmMilliStop(), PLAT_DIAG_TX_INTERFRAME, PLAT_DIAG_TX_PACKETSIZE, PlatDiag_diagEnabled, PlatDiag_parseLong(), PlatDiag_rxEnabled, PlatDiag_txEnabled, PlatDiag_txFrameCount, PlatDiag_txFrameSize, PlatDiag_txPeriod, and PlatDiag_txSentCount.
Referenced by otPlatDiagProcess().
Variable Documentation
PlatDiag_channel
uint8_t PlatDiag_channel static
Current channel set by diag channel.
Referenced by otPlatDiagAlarmCallback(), and otPlatDiagChannelSet().
PlatDiag_diagEnabled
bool PlatDiag_diagEnabled = false static
Diagnostics mode variables.
Referenced by otPlatDiagModeGet(), otPlatDiagModeSet(), PlatDiag_processReceive(), PlatDiag_processTone(), and PlatDiag_processTransmit().
PlatDiag_rxEnabled
bool PlatDiag_rxEnabled = false static
Referenced by otPlatDiagRadioReceived(), PlatDiag_processReceive(), and PlatDiag_processTransmit().
PlatDiag_rxExpectedSeqNo
uint16_t PlatDiag_rxExpectedSeqNo static
diag receive variables.
Referenced by otPlatDiagRadioReceived(), and PlatDiag_processReceive().
PlatDiag_rxFrameCount
uint16_t PlatDiag_rxFrameCount static
Referenced by otPlatDiagRadioReceived(), PlatDiag_calculatePER(), and PlatDiag_processReceive().
PlatDiag_rxLostFrames
uint16_t PlatDiag_rxLostFrames static
Referenced by otPlatDiagRadioReceived(), PlatDiag_calculatePER(), and PlatDiag_processReceive().
PlatDiag_rxNokCount
uint16_t PlatDiag_rxNokCount static
Referenced by otPlatDiagRadioReceived(), PlatDiag_calculatePER(), and PlatDiag_processReceive().
PlatDiag_rxReceivedCount
uint16_t PlatDiag_rxReceivedCount static
Referenced by otPlatDiagRadioReceived(), PlatDiag_calculatePER(), and PlatDiag_processReceive().
PlatDiag_txEnabled
bool PlatDiag_txEnabled = false static
Referenced by otPlatDiagAlarmCallback(), PlatDiag_processReceive(), and PlatDiag_processTransmit().
PlatDiag_txFrameCount
uint16_t PlatDiag_txFrameCount static
Referenced by otPlatDiagAlarmCallback(), and PlatDiag_processTransmit().
PlatDiag_txFrameSize
uint16_t PlatDiag_txFrameSize static
Referenced by otPlatDiagAlarmCallback(), and PlatDiag_processTransmit().
PlatDiag_txPeriod
uint32_t PlatDiag_txPeriod static
diag transmit variables.
Referenced by otPlatDiagAlarmCallback(), and PlatDiag_processTransmit().
PlatDiag_txSentCount
uint16_t PlatDiag_txSentCount static
Referenced by otPlatDiagAlarmCallback(), and PlatDiag_processTransmit().
© Copyright 1995-2018, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale