TI Thread API Documentation: examples/doorlock/doorlock.h File Reference
doorlock.h File Reference
Macros
#define DOORLOCK_STATE_LOCK "lock"
#define DOORLOCK_STATE_UNLOCK "unlock"
#define DOORLOCK_STATE_URI "doorlock/lockstate"
#define DOORLOCK_URI "doorlock/"
Enumerations
enum DoorLock_evt {
DoorLock_evtLock = Event_Id_00, DoorLock_evtUnlock = Event_Id_01, DoorLock_evtNwkSetup = Event_Id_02, DoorLock_evtKeyLeft = Event_Id_03,
DoorLock_evtKeyRight = Event_Id_04, DoorLock_evtNwkJoined = Event_Id_05, DoorLock_evtNwkJoinFailure = Event_Id_06
}
Functions
void DoorLock_postEvt (DoorLock_evt event)
Posts an event to the Door Lock task.
Macro Definition Documentation
DOORLOCK_STATE_LOCK
#define DOORLOCK_STATE_LOCK "lock"
Referenced by coapHandleServer().
DOORLOCK_STATE_UNLOCK
#define DOORLOCK_STATE_UNLOCK "unlock"
Referenced by coapHandleServer().
DOORLOCK_STATE_URI
#define DOORLOCK_STATE_URI "doorlock/lockstate"
DOORLOCK_URI
#define DOORLOCK_URI "doorlock/"
Enumeration Type Documentation
DoorLock_evt
enum DoorLock_evt
Door lock events.
Enumerator
DoorLock_evtLock
DoorLock_evtUnlock
DoorLock_evtNwkSetup
DoorLock_evtKeyLeft
DoorLock_evtKeyRight
DoorLock_evtNwkJoined
DoorLock_evtNwkJoinFailure
Function Documentation
DoorLock_postEvt()
void DoorLock_postEvt (DoorLock_evt event)
Posts an event to the Door Lock task.
Parameters
event event to post.
Returns
None
References doorLockEvents.
Referenced by coapHandleServer(), processKeyChangeCB(), and processOtStackEvents().
© Copyright 1995-2018, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale