TI Thread API Documentation: examples/thermostat/graphicext.h File Reference
graphicext.h File Reference
Data Structures
struct GraphicExt_sprite_t
Functions
void GraphicExt_animateBackground (Graphics_Image *frames, uint8_t startFrame, uint8_t endFrame, bool continuous)
Displays an animation by switching through different frames.
void GraphicExt_drawSprites (GraphicExt_sprite_t *spriteList, uint8_t spriteListLen, bool overlayBackground)
Draws a list of sprites on the screen.
void GraphicExt_initAnimationModule (Display_Handle *lcdHandle, Event_Struct *appEventStruct, uint32_t regEventID, uint32_t frameDuration)
Set up the animation timer.
void GraphicExt_processEvt (void)
Process an animation event.
void GraphicExt_stopAnimate (void)
Stops a continuous animation.
Function Documentation
GraphicExt_animateBackground()
void GraphicExt_animateBackground (Graphics_Image * frames, uint8_t startFrame, uint8_t endFrame, bool continuous)
Displays an animation by switching through different frames.
Parameters
frames array of frames to be displayed.
startFrame index of the initial frame to start the animation.
endFrame index of the last frame to be displayed.
continuous if true it will keep displaying the animation until GraphicExt_stopAnimate is called, otherwise the animation will be displayed once.
Returns
None
Documented in graphicext.h
References backgroundFrames, contAnimation, currentEndFrame, currentFrame, currentStartFrame, GraphicExt_flushFrame(), and lcdHdl.
Referenced by processEvents(), and updateThermostatMode().
GraphicExt_drawSprites()
void GraphicExt_drawSprites (GraphicExt_sprite_t * spriteList, uint8_t spriteListLen, bool overlayBackground)
Draws a list of sprites on the screen.
Parameters
spriteList list of sprites to be drawn on screen.
spriteListLen length of sprite list.
overlayBackground if true it will draw the sprites on top of the current background set by GraphicExt_animateBackground, otherwise the background will be white.
Returns
None
Documented in graphicext.h
References GraphicExt_flushSprites(), lcdHdl, listLength, and overlayBack.
Referenced by flushLcd().
GraphicExt_initAnimationModule()
void GraphicExt_initAnimationModule (Display_Handle * lcdHandle, Event_Struct * appEventStruct, uint32_t regEventID, uint32_t frameDuration)
Set up the animation timer.
Parameters
frameDuration time in milliseconds per each frame.
Returns
None
Documented in graphicext.h
References animationClkHandle, animationClkStruct, eventStruct, GraphicExt_timerCallBack(), graphicsEvent, lcdHandle, and lcdHdl.
Referenced by Thermostat_task().
GraphicExt_processEvt()
void GraphicExt_processEvt (void)
Process an animation event.
Returns
None
Documented in graphicext.h
References GraphicExt_flushFrame(), and lcdHdl.
Referenced by processEvents().
GraphicExt_stopAnimate()
void GraphicExt_stopAnimate (void)
Stops a continuous animation.
Returns
None
Documented in graphicext.h
References animationClkHandle.
© Copyright 1995-2018, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale