TI Thread API Documentation: examples/thermostat/graphicext.c File Reference
graphicext.c File Reference
Functions
void GraphicExt_animateBackground (Graphics_Image *frames, uint8_t startFrame, uint8_t endFrame, bool continuous)
Displays an animation by switching through different frames.
void GraphicExt_drawSprites (GraphicExt_sprite_t *spriteList, uint8_t spriteListLen, bool overlayBackground)
Draws a list of sprites on the screen.
static void GraphicExt_flushFrame (Graphics_Context *context)
Flush the sprites after being drawn by GraphicExt_drawSprites.
static void GraphicExt_flushSprites (Graphics_Context *context)
Flush the sprites after being drawn by GraphicExt_drawSprites.
void GraphicExt_initAnimationModule (Display_Handle *lcdHandle, Event_Struct *appEventStruct, uint32_t regEventID, uint32_t frameDuration)
Set up the animation timer.
void GraphicExt_processEvt (void)
Process an animation event.
static bool GraphicExt_spInRange (uint8_t yPos, GraphicExt_sprite_t *sprite)
Determines if a sprite is within range.
void GraphicExt_stopAnimate (void)
Stops a continuous animation.
static void GraphicExt_timerCallBack (UArg a0)
Callback function for the timer timeout.
Variables
static Clock_Handle animationClkHandle
static Clock_Struct animationClkStruct
static Graphics_Image * backgroundFrames = NULL
static bool contAnimation = false
static uint8_t currentEndFrame
static uint8_t currentFrame
static uint8_t currentStartFrame
static Event_Struct * eventStruct
static uint32_t graphicsEvent
static Display_Handle * lcdHdl
static uint8_t listLength
static bool overlayBack = false
static const uint32_t spriteImgPalette []
static GraphicExt_sprite_t * sprites = NULL
Function Documentation
GraphicExt_animateBackground()
void GraphicExt_animateBackground (Graphics_Image * frames, uint8_t startFrame, uint8_t endFrame, bool continuous)
Displays an animation by switching through different frames.
Documented in graphicext.h
References backgroundFrames, contAnimation, currentEndFrame, currentFrame, currentStartFrame, GraphicExt_flushFrame(), and lcdHdl.
Referenced by processEvents(), and updateThermostatMode().
GraphicExt_drawSprites()
void GraphicExt_drawSprites (GraphicExt_sprite_t * spriteList, uint8_t spriteListLen, bool overlayBackground)
Draws a list of sprites on the screen.
Documented in graphicext.h
References GraphicExt_flushSprites(), lcdHdl, listLength, and overlayBack.
Referenced by flushLcd().
GraphicExt_flushFrame()
static void GraphicExt_flushFrame (Graphics_Context * context) static
Flush the sprites after being drawn by GraphicExt_drawSprites.
Parameters
context LCD Graphics context.
Returns
None
References animationClkHandle, backgroundFrames, contAnimation, currentEndFrame, currentFrame, currentStartFrame, GraphicExt_flushSprites(), and overlayBack.
Referenced by GraphicExt_animateBackground(), and GraphicExt_processEvt().
GraphicExt_flushSprites()
static void GraphicExt_flushSprites (Graphics_Context * context) static
Flush the sprites after being drawn by GraphicExt_drawSprites.
Parameters
context LCD Graphics context.
Returns
None
References backgroundFrames, currentFrame, GraphicExt_spInRange(), GraphicExt_sprite_t::image, listLength, overlayBack, GraphicExt_sprite_t::posX, GraphicExt_sprite_t::posY, and spriteImgPalette.
Referenced by GraphicExt_drawSprites(), and GraphicExt_flushFrame().
GraphicExt_initAnimationModule()
void GraphicExt_initAnimationModule (Display_Handle * lcdHandle, Event_Struct * appEventStruct, uint32_t regEventID, uint32_t frameDuration)
Set up the animation timer.
Documented in graphicext.h
References animationClkHandle, animationClkStruct, eventStruct, GraphicExt_timerCallBack(), graphicsEvent, lcdHandle, and lcdHdl.
Referenced by Thermostat_task().
GraphicExt_processEvt()
void GraphicExt_processEvt (void)
Process an animation event.
Documented in graphicext.h
References GraphicExt_flushFrame(), and lcdHdl.
Referenced by processEvents().
GraphicExt_spInRange()
static bool GraphicExt_spInRange (uint8_t yPos, GraphicExt_sprite_t * sprite) static
Determines if a sprite is within range.
Parameters
yPos Y possition.
sprite Sprite to be compared vs yPos.
Returns
None
References GraphicExt_sprite_t::image, and GraphicExt_sprite_t::posY.
Referenced by GraphicExt_flushSprites().
GraphicExt_stopAnimate()
void GraphicExt_stopAnimate (void)
Stops a continuous animation.
Documented in graphicext.h
References animationClkHandle.
GraphicExt_timerCallBack()
static void GraphicExt_timerCallBack (UArg a0) static
Callback function for the timer timeout.
Parameters
a0 Argument passed to CB if set when timer is initialized.
Returns
None
References eventStruct, and graphicsEvent.
Referenced by GraphicExt_initAnimationModule().
Variable Documentation
animationClkHandle
Clock_Handle animationClkHandle static
Referenced by GraphicExt_flushFrame(), GraphicExt_initAnimationModule(), and GraphicExt_stopAnimate().
animationClkStruct
Clock_Struct animationClkStruct static
Referenced by GraphicExt_initAnimationModule().
backgroundFrames
Graphics_Image* backgroundFrames = NULL static
Referenced by GraphicExt_animateBackground(), GraphicExt_flushFrame(), and GraphicExt_flushSprites().
contAnimation
bool contAnimation = false static
Referenced by GraphicExt_animateBackground(), and GraphicExt_flushFrame().
currentEndFrame
uint8_t currentEndFrame static
Referenced by GraphicExt_animateBackground(), and GraphicExt_flushFrame().
currentFrame
uint8_t currentFrame static
Referenced by GraphicExt_animateBackground(), GraphicExt_flushFrame(), and GraphicExt_flushSprites().
currentStartFrame
uint8_t currentStartFrame static
Referenced by GraphicExt_animateBackground(), and GraphicExt_flushFrame().
eventStruct
Event_Struct* eventStruct static
Referenced by GraphicExt_initAnimationModule(), and GraphicExt_timerCallBack().
graphicsEvent
uint32_t graphicsEvent static
Referenced by GraphicExt_initAnimationModule(), and GraphicExt_timerCallBack().
lcdHdl
Display_Handle* lcdHdl static
Referenced by GraphicExt_animateBackground(), GraphicExt_drawSprites(), GraphicExt_initAnimationModule(), and GraphicExt_processEvt().
listLength
uint8_t listLength static
Referenced by GraphicExt_drawSprites(), and GraphicExt_flushSprites().
overlayBack
bool overlayBack = false static
Referenced by GraphicExt_drawSprites(), GraphicExt_flushFrame(), and GraphicExt_flushSprites().
spriteImgPalette
const uint32_t spriteImgPalette[] static
Initial value:
=
{
    0x000000,   0xffffff
}
Referenced by GraphicExt_flushSprites().
sprites
GraphicExt_sprite_t* sprites = NULL static
© Copyright 1995-2018, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale