TI Thread API Documentation: examples/ncp/ncp.c File Reference
ncp.c File Reference
Functions
void * ncp_task (void *arg0)
void ncp_taskCreate (void)
void otPlatLog (otLogLevel aLogLevel, otLogRegion aLogRegion, const char *aFormat,...)
static void resetPriority (void)
Variables
static char ncp_stack [TASK_CONFIG_NCP_TASK_STACK_SIZE]
Function Documentation
ncp_task()
void * ncp_task (void * arg0)
Main thread starting the NCP example within OpenThread.
References OtInstance_get(), OtRtosApi_lock(), OtRtosApi_unlock(), and resetPriority().
Referenced by ncp_taskCreate().
ncp_taskCreate()
void ncp_taskCreate (void)
Create the task for the ncp application.
References ncp_stack, ncp_task(), and TASK_CONFIG_NCP_TASK_STACK_SIZE.
Referenced by main().
otPlatLog()
void otPlatLog (otLogLevel aLogLevel, otLogRegion aLogRegion, const char * aFormat, ...)
References OtRtosApi_lock(), and OtRtosApi_unlock().
resetPriority()
static void resetPriority (void) static
Return thread priority after initialization.
References TASK_CONFIG_NCP_TASK_PRIORITY.
Referenced by ncp_task().
Variable Documentation
ncp_stack
char ncp_stack[TASK_CONFIG_NCP_TASK_STACK_SIZE] static
Referenced by ncp_taskCreate().
© Copyright 1995-2018, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale