TI Thread API Documentation: examples/nv/nvoctp.h File Reference
nvoctp.h File Reference
Data Structures
struct NVOCTP_diag_t
Macros
#define NVOCTP_EXCEPTION(pg, err)
#define NVOCTP_NVID_DIAG {NVINTF_SYSID_NVDRVR, 1, 0}
Functions
void NVOCTP_loadApiPtrs (NVINTF_nvFuncts_t *pfn)
void NVOCTP_loadApiPtrsExt (NVINTF_nvFuncts_t *pfn)
void NVOCTP_loadApiPtrsMin (NVINTF_nvFuncts_t *pfn)
void NVOCTP_setCheckVoltage (void *funcPtr)
Macro Definition Documentation
NVOCTP_EXCEPTION
#define NVOCTP_EXCEPTION (pg, err)
Referenced by NVOCTP_findItem(), and NVOCTP_initNvApi().
NVOCTP_NVID_DIAG
#define NVOCTP_NVID_DIAG {NVINTF_SYSID_NVDRVR, 1, 0}
Function Documentation
NVOCTP_loadApiPtrs()
void NVOCTP_loadApiPtrs (NVINTF_nvFuncts_t * pfn)
References nvintf_nvfuncts_t::compactNV, nvintf_nvfuncts_t::createItem, nvintf_nvfuncts_t::deleteItem, nvintf_nvfuncts_t::doNext, nvintf_nvfuncts_t::getItemLen, nvintf_nvfuncts_t::initNV, nvintf_nvfuncts_t::lockNV, NVOCTP_compactNvApi(), NVOCTP_createItemApi(), NVOCTP_deleteItemApi(), NVOCTP_getItemLenApi(), NVOCTP_initNvApi(), NVOCTP_readItemApi(), NVOCTP_writeItemApi(), nvintf_nvfuncts_t::readItem, nvintf_nvfuncts_t::unlockNV, and nvintf_nvfuncts_t::writeItem.
NVOCTP_loadApiPtrsExt()
void NVOCTP_loadApiPtrsExt (NVINTF_nvFuncts_t * pfn)
References nvintf_nvfuncts_t::compactNV, nvintf_nvfuncts_t::createItem, nvintf_nvfuncts_t::deleteItem, nvintf_nvfuncts_t::doNext, nvintf_nvfuncts_t::getItemLen, nvintf_nvfuncts_t::initNV, nvintf_nvfuncts_t::lockNV, NVOCTP_compactNvApi(), NVOCTP_createItemApi(), NVOCTP_deleteItemApi(), NVOCTP_doNextApi(), NVOCTP_getItemLenApi(), NVOCTP_initNvApi(), NVOCTP_lockNvApi(), NVOCTP_readItemApi(), NVOCTP_unlockNvApi(), NVOCTP_writeItemApi(), nvintf_nvfuncts_t::readItem, nvintf_nvfuncts_t::unlockNV, and nvintf_nvfuncts_t::writeItem.
Referenced by otPlatSettingsInit().
NVOCTP_loadApiPtrsMin()
void NVOCTP_loadApiPtrsMin (NVINTF_nvFuncts_t * pfn)
References nvintf_nvfuncts_t::compactNV, nvintf_nvfuncts_t::createItem, nvintf_nvfuncts_t::deleteItem, nvintf_nvfuncts_t::doNext, nvintf_nvfuncts_t::getItemLen, nvintf_nvfuncts_t::initNV, nvintf_nvfuncts_t::lockNV, NVOCTP_compactNvApi(), NVOCTP_initNvApi(), NVOCTP_readItemApi(), NVOCTP_writeItemApi(), nvintf_nvfuncts_t::readItem, nvintf_nvfuncts_t::unlockNV, and nvintf_nvfuncts_t::writeItem.
NVOCTP_setCheckVoltage()
void NVOCTP_setCheckVoltage (void * funcPtr)
References NVOCTP_voltCheckFptr.
© Copyright 1995-2018, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale