TI Thread API Documentation: examples/nv/nvoctp.c File Reference
nvoctp.c File Reference
Data Structures
struct NVOCTP_itemHdr_t
struct NVOCTP_itemWrp_t
struct NVOCTP_pageHdr_t
Macros
#define FLASH_PAGE_SIZE 0x2000
#define NVOCTP_ACTIVEIDBIT 0x2
#define NVOCTP_ALERT(cond, message)
#define NVOCTP_ASSERT(cond, message)
#define NVOCTP_CMPRID(s, i, b)
#define NVOCTP_CRCONREAD 1
#define NVOCTP_ERASEDBYTE 0xFF
#define NVOCTP_ERASEDWORD 0xFFFFFFFF
#define NVOCTP_FINDANY 1
#define NVOCTP_FINDITMID 3
#define NVOCTP_FINDSTRICT 4
#define NVOCTP_FINDSYSID 2
#define NVOCTP_FLASHACCESS(err)
#define NVOCTP_FLASHOFFSET(base, pg, ofs)
#define NVOCTP_FOLLOWBIT 0x4
#define NVOCTP_HDRCRCINC 5
#define NVOCTP_HDRSIGOFS 6
#define NVOCTP_HDRVLDOFS 5
#define NVOCTP_ITEMHDREND (NVOCTP_ITEMHDRLEN - 1)
#define NVOCTP_ITEMHDRLEN 7
#define NVOCTP_LOCK() IArg key = GateMutexPri_enter(NVOCTP_gMutexPri);
#define NVOCTP_MAXCYCLE 0xFE
#define NVOCTP_MAXITEMID 0x03FF
#define NVOCTP_MAXLEN 0x0FFF
#define NVOCTP_MAXSUBID 0x03FF
#define NVOCTP_MAXSYSID 0x003F
#define NVOCTP_MINCYCLE 0x01
#define NVOCTP_NULLPAGE 0
#define NVOCTP_NVS_INDEX 0
#define NVOCTP_ONEBYTE 1
#define NVOCTP_PGACTIVE 0xA5
#define NVOCTP_PGCLEAR 0xFF
#define NVOCTP_PGDATAEND (FLASH_PAGE_SIZE - 1)
#define NVOCTP_PGDATALEN (FLASH_PAGE_SIZE - NVOCTP_PGHDRLEN)
#define NVOCTP_PGDATAOFS (NVOCTP_PGHDRLEN)
#define NVOCTP_PGERASED 0xB7
#define NVOCTP_PGHDRCYC 1
#define NVOCTP_PGHDRLEN (sizeof(NVOCTP_pageHdr_t))
#define NVOCTP_PGHDROFS 0
#define NVOCTP_PGHDRPST 0
#define NVOCTP_PGHDRSIG 3
#define NVOCTP_PGHDRVER 2
#define NVOCTP_PGXFER 0x24
#define NVOCTP_SIGNATURE 0x96
#define NVOCTP_SMALLITEM 12
#define NVOCTP_UNLOCK(err)
#define NVOCTP_VALIDIDBIT 0x1
#define NVOCTP_VERSION 0x02
#define NVOCTP_XFERBLKMAX 32
Typedefs
typedef uint8_t cmpIH_t[NVOCTP_ITEMHDRLEN]
Functions
static uint8_t NVOCTP_checkItem (NVINTF_itemID_t *id, uint16_t len, NVOCTP_itemHdr_t *iHdr, uint8_t flag)
static uint8_t NVOCTP_compactNvApi (uint16_t min)
static int16_t NVOCTP_compactPage (uint8_t srcPg)
static void NVOCTP_copyItem (uint8_t xPg, uint16_t sOfs, uint16_t dOfs, uint16_t len)
static uint8_t NVOCTP_createItemApi (NVINTF_itemID_t id, uint32_t len, void *buf)
static uint8_t NVOCTP_deleteItemApi (NVINTF_itemID_t id)
static uint8_t NVOCTP_doNextApi (NVINTF_nvProxy_t *prx)
static uint8_t NVOCTP_doNVCRC (uint8_t pg, uint16_t ofs, uint16_t len, uint8_t crc)
static uint8_t NVOCTP_doRAMCRC (uint8_t *input, uint16_t len, uint8_t crc)
static uint8_t NVOCTP_erase (uint8_t dstPg)
static int16_t NVOCTP_findItem (uint8_t pg, uint16_t ofs, uint32_t cid, uint8_t flag)
static uint16_t NVOCTP_findOffset (uint8_t pg, uint16_t ofs)
static uint32_t NVOCTP_getItemLenApi (NVINTF_itemID_t id)
static uint8_t NVOCTP_initNvApi (void *param)
void NVOCTP_loadApiPtrs (NVINTF_nvFuncts_t *pfn)
void NVOCTP_loadApiPtrsExt (NVINTF_nvFuncts_t *pfn)
void NVOCTP_loadApiPtrsMin (NVINTF_nvFuncts_t *pfn)
static IArg NVOCTP_lockNvApi (void)
Global function to lock the NV semaphore.
static uint8_t NVOCTP_newItem (NVOCTP_itemHdr_t *iHdr, uint8_t *pBuf)
static void NVOCTP_read (uint8_t pg, uint16_t off, uint8_t *pBuf, uint16_t len)
static uint8_t NVOCTP_readByte (uint8_t pg, uint16_t ofs)
static void NVOCTP_readHeader (uint8_t pg, uint16_t ofs, NVOCTP_itemHdr_t *iHdr)
static uint8_t NVOCTP_readItem (NVOCTP_itemHdr_t *iHdr, uint16_t ofs, uint16_t len, void *pBuf)
static uint8_t NVOCTP_readItemApi (NVINTF_itemID_t id, uint16_t ofs, uint16_t len, void *buf)
void NVOCTP_setCheckVoltage (void *funcPtr)
static void NVOCTP_setItemInactive (uint16_t hOfs)
static void NVOCTP_setPageActive (uint8_t pg)
static void NVOCTP_unlockNvApi (IArg)
static uint8_t NVOCTP_verifyCRC (uint16_t iOfs, uint16_t len, uint8_t crc)
static uint8_t NVOCTP_write (uint8_t dstPg, uint16_t off, uint8_t *pBuf, uint16_t len)
static void NVOCTP_writeByte (uint8_t pg, uint16_t ofs, uint8_t bwv)
static void NVOCTP_writeItem (NVOCTP_itemHdr_t *iHdr, uint8_t dstPg, uint8_t *pBuf)
static uint8_t NVOCTP_writeItemApi (NVINTF_itemID_t id, uint16_t len, void *buf)
Variables
static uint8_t NVOCTP_activePg
static uint8_t NVOCTP_failF = NVINTF_NOTREADY
static uint8_t NVOCTP_failW
static GateMutexPri_Handle NVOCTP_gMutexPri
static uint8_t NVOCTP_itemBuffer [NVOCTP_SMALLITEM]
static uint8_t NVOCTP_nvBegPage
static uint8_t NVOCTP_nvEndPage
static NVS_Attrs NVOCTP_nvsAttrs
static NVS_Handle NVOCTP_nvsHandle
static uint8_t NVOCTP_pgCycle
static uint16_t NVOCTP_pgOff
static bool(* NVOCTP_voltCheckFptr)(void)
Macro Definition Documentation
FLASH_PAGE_SIZE
#define FLASH_PAGE_SIZE 0x2000
Referenced by NVOCTP_compactNvApi(), NVOCTP_compactPage(), NVOCTP_doNextApi(), NVOCTP_initNvApi(), NVOCTP_newItem(), and NVOCTP_writeItem().
NVOCTP_ACTIVEIDBIT
#define NVOCTP_ACTIVEIDBIT 0x2
Referenced by NVOCTP_compactPage(), NVOCTP_findItem(), NVOCTP_readHeader(), NVOCTP_setItemInactive(), and NVOCTP_writeItem().
NVOCTP_ALERT
#define NVOCTP_ALERT (cond, message)
Referenced by NVOCTP_checkItem(), NVOCTP_compactNvApi(), NVOCTP_compactPage(), NVOCTP_createItemApi(), NVOCTP_deleteItemApi(), NVOCTP_doNextApi(), NVOCTP_erase(), NVOCTP_findItem(), NVOCTP_initNvApi(), NVOCTP_newItem(), NVOCTP_readHeader(), NVOCTP_verifyCRC(), NVOCTP_write(), and NVOCTP_writeItem().
NVOCTP_ASSERT
#define NVOCTP_ASSERT (cond, message)
Referenced by NVOCTP_checkItem(), NVOCTP_compactPage(), NVOCTP_findItem(), NVOCTP_initNvApi(), and NVOCTP_writeItem().
NVOCTP_CMPRID
#define NVOCTP_CMPRID (s, i, b)
Value:
((uint32_t)((((((s) & NVOCTP_MAXSYSID) << 12)   | \
                                            ((i) & NVOCTP_MAXITEMID)) << 12) | \
                                            ((b) & NVOCTP_MAXSUBID)))
Referenced by NVOCTP_checkItem(), NVOCTP_compactPage(), NVOCTP_doNextApi(), and NVOCTP_readHeader().
NVOCTP_CRCONREAD
#define NVOCTP_CRCONREAD 1
Referenced by NVOCTP_readItem().
NVOCTP_ERASEDBYTE
#define NVOCTP_ERASEDBYTE 0xFF
Referenced by NVOCTP_findOffset(), and NVOCTP_writeItem().
NVOCTP_ERASEDWORD
#define NVOCTP_ERASEDWORD 0xFFFFFFFF
Referenced by NVOCTP_findOffset().
NVOCTP_FINDANY
#define NVOCTP_FINDANY 1
Referenced by NVOCTP_doNextApi(), and NVOCTP_findItem().
NVOCTP_FINDITMID
#define NVOCTP_FINDITMID 3
Referenced by NVOCTP_doNextApi(), and NVOCTP_findItem().
NVOCTP_FINDSTRICT
#define NVOCTP_FINDSTRICT 4
Referenced by NVOCTP_createItemApi(), NVOCTP_deleteItemApi(), NVOCTP_findItem(), NVOCTP_getItemLenApi(), NVOCTP_readItemApi(), and NVOCTP_writeItemApi().
NVOCTP_FINDSYSID
#define NVOCTP_FINDSYSID 2
Referenced by NVOCTP_doNextApi(), and NVOCTP_findItem().
NVOCTP_FLASHACCESS
#define NVOCTP_FLASHACCESS (err)
Value:
{if (NVOCTP_voltCheckFptr)\
    { if (!NVOCTP_voltCheckFptr()) { err = NVINTF_LOWPOWER;}}}
Referenced by NVOCTP_erase(), NVOCTP_write(), and NVOCTP_writeItemApi().
NVOCTP_FLASHOFFSET
#define NVOCTP_FLASHOFFSET (base, pg, ofs)
Value:
((uint32_t)\
        (((pg) << 13) + (ofs) - (uint32_t)(base)))
Referenced by NVOCTP_erase(), NVOCTP_read(), and NVOCTP_write().
NVOCTP_FOLLOWBIT
#define NVOCTP_FOLLOWBIT 0x4
Referenced by NVOCTP_findItem(), and NVOCTP_readHeader().
NVOCTP_HDRCRCINC
#define NVOCTP_HDRCRCINC 5
Referenced by NVOCTP_verifyCRC(), and NVOCTP_writeItem().
NVOCTP_HDRSIGOFS
#define NVOCTP_HDRSIGOFS 6
NVOCTP_HDRVLDOFS
#define NVOCTP_HDRVLDOFS 5
Referenced by NVOCTP_setItemInactive().
NVOCTP_ITEMHDREND
#define NVOCTP_ITEMHDREND (NVOCTP_ITEMHDRLEN - 1)
NVOCTP_ITEMHDRLEN
#define NVOCTP_ITEMHDRLEN 7
Referenced by NVOCTP_compactPage(), NVOCTP_findItem(), NVOCTP_initNvApi(), NVOCTP_newItem(), NVOCTP_readHeader(), and NVOCTP_writeItem().
NVOCTP_LOCK
#define NVOCTP_LOCK () IArg key = GateMutexPri_enter(NVOCTP_gMutexPri);
Referenced by NVOCTP_compactNvApi(), NVOCTP_createItemApi(), NVOCTP_deleteItemApi(), NVOCTP_doNextApi(), NVOCTP_getItemLenApi(), NVOCTP_readItemApi(), and NVOCTP_writeItemApi().
NVOCTP_MAXCYCLE
#define NVOCTP_MAXCYCLE 0xFE
Referenced by NVOCTP_initNvApi(), and NVOCTP_setPageActive().
NVOCTP_MAXITEMID
#define NVOCTP_MAXITEMID 0x03FF
Referenced by NVOCTP_checkItem().
NVOCTP_MAXLEN
#define NVOCTP_MAXLEN 0x0FFF
Referenced by NVOCTP_checkItem().
NVOCTP_MAXSUBID
#define NVOCTP_MAXSUBID 0x03FF
Referenced by NVOCTP_checkItem().
NVOCTP_MAXSYSID
#define NVOCTP_MAXSYSID 0x003F
Referenced by NVOCTP_checkItem().
NVOCTP_MINCYCLE
#define NVOCTP_MINCYCLE 0x01
Referenced by NVOCTP_initNvApi(), and NVOCTP_setPageActive().
NVOCTP_NULLPAGE
#define NVOCTP_NULLPAGE 0
Referenced by NVOCTP_initNvApi().
NVOCTP_NVS_INDEX
#define NVOCTP_NVS_INDEX 0
Referenced by NVOCTP_initNvApi().
NVOCTP_ONEBYTE
#define NVOCTP_ONEBYTE 1
Referenced by NVOCTP_readByte(), and NVOCTP_readHeader().
NVOCTP_PGACTIVE
#define NVOCTP_PGACTIVE 0xA5
Referenced by NVOCTP_initNvApi(), and NVOCTP_setPageActive().
NVOCTP_PGCLEAR
#define NVOCTP_PGCLEAR 0xFF
NVOCTP_PGDATAEND
#define NVOCTP_PGDATAEND (FLASH_PAGE_SIZE - 1)
NVOCTP_PGDATALEN
#define NVOCTP_PGDATALEN (FLASH_PAGE_SIZE - NVOCTP_PGHDRLEN)
NVOCTP_PGDATAOFS
#define NVOCTP_PGDATAOFS (NVOCTP_PGHDRLEN)
Referenced by NVOCTP_compactPage(), and NVOCTP_initNvApi().
NVOCTP_PGERASED
#define NVOCTP_PGERASED 0xB7
Referenced by NVOCTP_initNvApi().
NVOCTP_PGHDRCYC
#define NVOCTP_PGHDRCYC 1
Referenced by NVOCTP_setPageActive().
NVOCTP_PGHDRLEN
#define NVOCTP_PGHDRLEN (sizeof(NVOCTP_pageHdr_t))
Referenced by NVOCTP_compactPage(), NVOCTP_findItem(), NVOCTP_initNvApi(), and NVOCTP_setPageActive().
NVOCTP_PGHDROFS
#define NVOCTP_PGHDROFS 0
Referenced by NVOCTP_compactPage(), and NVOCTP_initNvApi().
NVOCTP_PGHDRPST
#define NVOCTP_PGHDRPST 0
Referenced by NVOCTP_setPageActive().
NVOCTP_PGHDRSIG
#define NVOCTP_PGHDRSIG 3
Referenced by NVOCTP_setPageActive().
NVOCTP_PGHDRVER
#define NVOCTP_PGHDRVER 2
Referenced by NVOCTP_setPageActive().
NVOCTP_PGXFER
#define NVOCTP_PGXFER 0x24
Referenced by NVOCTP_compactPage(), and NVOCTP_initNvApi().
NVOCTP_SIGNATURE
#define NVOCTP_SIGNATURE 0x96
Referenced by NVOCTP_checkItem(), NVOCTP_compactPage(), NVOCTP_initNvApi(), NVOCTP_readHeader(), NVOCTP_setPageActive(), and NVOCTP_writeItem().
NVOCTP_SMALLITEM
#define NVOCTP_SMALLITEM 12
Referenced by NVOCTP_writeItem().
NVOCTP_UNLOCK
#define NVOCTP_UNLOCK (err)
Value:
{ \
    GateMutexPri_leave(NVOCTP_gMutexPri, key); return (err); }
Referenced by NVOCTP_compactNvApi(), NVOCTP_createItemApi(), NVOCTP_deleteItemApi(), NVOCTP_doNextApi(), NVOCTP_getItemLenApi(), NVOCTP_readItemApi(), and NVOCTP_writeItemApi().
NVOCTP_VALIDIDBIT
#define NVOCTP_VALIDIDBIT 0x1
Referenced by NVOCTP_compactPage(), NVOCTP_findItem(), and NVOCTP_readHeader().
NVOCTP_VERSION
#define NVOCTP_VERSION 0x02
Referenced by NVOCTP_initNvApi(), and NVOCTP_setPageActive().
NVOCTP_XFERBLKMAX
#define NVOCTP_XFERBLKMAX 32
Referenced by NVOCTP_compactPage(), NVOCTP_copyItem(), and NVOCTP_doNVCRC().
Typedef Documentation
cmpIH_t
typedef uint8_t cmpIH_t[NVOCTP_ITEMHDRLEN]
Function Documentation
NVOCTP_checkItem()
static uint8_t NVOCTP_checkItem (NVINTF_itemID_t * id, uint16_t len, NVOCTP_itemHdr_t * iHdr, uint8_t flag) static
References NVOCTP_itemHdr_t::cmpid, NVOCTP_itemHdr_t::hofs, nvintf_itemid_t::itemID, NVOCTP_itemHdr_t::itemid, len, NVOCTP_itemHdr_t::len, NVINTF_BADITEMID, NVINTF_BADLENGTH, NVINTF_BADSUBID, NVINTF_BADSYSID, NVINTF_NOTFOUND, NVINTF_NOTREADY, NVINTF_SUCCESS, NVOCTP_ALERT, NVOCTP_ASSERT, NVOCTP_CMPRID, NVOCTP_findItem(), NVOCTP_MAXITEMID, NVOCTP_MAXLEN, NVOCTP_MAXSUBID, NVOCTP_MAXSYSID, NVOCTP_readHeader(), NVOCTP_SIGNATURE, NVOCTP_itemHdr_t::sig, nvintf_itemid_t::subID, NVOCTP_itemHdr_t::subid, NVOCTP_itemHdr_t::sysid, and nvintf_itemid_t::systemID.
Referenced by NVOCTP_createItemApi(), NVOCTP_deleteItemApi(), NVOCTP_getItemLenApi(), NVOCTP_readItemApi(), and NVOCTP_writeItemApi().
NVOCTP_compactNvApi()
static uint8_t NVOCTP_compactNvApi (uint16_t min) static
References FLASH_PAGE_SIZE, NVINTF_BADPARAM, NVINTF_SUCCESS, NVOCTP_ALERT, NVOCTP_compactPage(), NVOCTP_failF, NVOCTP_failW, NVOCTP_LOCK, NVOCTP_pgOff, and NVOCTP_UNLOCK.
Referenced by NVOCTP_loadApiPtrs(), NVOCTP_loadApiPtrsExt(), and NVOCTP_loadApiPtrsMin().
NVOCTP_compactPage()
static int16_t NVOCTP_compactPage (uint8_t srcPg) static
References NVOCTP_diag_t::active, NVOCTP_diag_t::available, NVOCTP_diag_t::badCRC, NVOCTP_itemHdr_t::cmpid, NVOCTP_diag_t::compacts, NVOCTP_itemHdr_t::crc8, NVOCTP_diag_t::deleted, FLASH_PAGE_SIZE, NVOCTP_itemHdr_t::hofs, nvintf_itemid_t::itemID, NVOCTP_itemHdr_t::itemid, NVOCTP_itemHdr_t::len, NVINTF_BADLENGTH, NVINTF_FAILURE, NVINTF_SUCCESS, NVINTF_SYSID_NVDRVR, NVOCTP_ACTIVEIDBIT, NVOCTP_ALERT, NVOCTP_ASSERT, NVOCTP_CMPRID, NVOCTP_copyItem(), NVOCTP_erase(), NVOCTP_ITEMHDRLEN, NVOCTP_nvBegPage, NVOCTP_PGDATAOFS, NVOCTP_PGHDRLEN, NVOCTP_PGHDROFS, NVOCTP_pgOff, NVOCTP_PGXFER, NVOCTP_read(), NVOCTP_readHeader(), NVOCTP_setPageActive(), NVOCTP_SIGNATURE, NVOCTP_VALIDIDBIT, NVOCTP_verifyCRC(), NVOCTP_writeByte(), NVOCTP_writeItem(), NVOCTP_XFERBLKMAX, NVOCTP_itemHdr_t::sig, NVOCTP_itemHdr_t::stats, nvintf_itemid_t::subID, NVOCTP_itemHdr_t::subid, NVOCTP_itemHdr_t::sysid, and nvintf_itemid_t::systemID.
Referenced by NVOCTP_compactNvApi(), NVOCTP_findItem(), NVOCTP_initNvApi(), and NVOCTP_newItem().
NVOCTP_copyItem()
static void NVOCTP_copyItem (uint8_t xPg, uint16_t sOfs, uint16_t dOfs, uint16_t len) static
References NVOCTP_read(), NVOCTP_write(), and NVOCTP_XFERBLKMAX.
Referenced by NVOCTP_compactPage().
NVOCTP_createItemApi()
static uint8_t NVOCTP_createItemApi (NVINTF_itemID_t id, uint32_t len, void * buf) static
References NVINTF_BADPARAM, NVINTF_FAILURE, NVINTF_NOTFOUND, NVINTF_SUCCESS, NVOCTP_ALERT, NVOCTP_checkItem(), NVOCTP_FINDSTRICT, NVOCTP_LOCK, NVOCTP_newItem(), and NVOCTP_UNLOCK.
Referenced by NVOCTP_loadApiPtrs(), and NVOCTP_loadApiPtrsExt().
NVOCTP_deleteItemApi()
static uint8_t NVOCTP_deleteItemApi (NVINTF_itemID_t id) static
References NVOCTP_itemHdr_t::cmpid, NVOCTP_itemHdr_t::hofs, NVINTF_BADSYSID, NVINTF_FAILURE, NVINTF_SUCCESS, NVOCTP_ALERT, NVOCTP_checkItem(), NVOCTP_findItem(), NVOCTP_FINDSTRICT, NVOCTP_LOCK, NVOCTP_setItemInactive(), and NVOCTP_UNLOCK.
Referenced by NVOCTP_loadApiPtrs(), and NVOCTP_loadApiPtrsExt().
NVOCTP_doNextApi()
static uint8_t NVOCTP_doNextApi (NVINTF_nvProxy_t * prx) static
References nvintf_nvproxy_t::buffer, nvintf_nvproxy_t::flag, FLASH_PAGE_SIZE, nvintf_nvproxy_t::itemid, NVOCTP_itemHdr_t::itemid, nvintf_nvproxy_t::len, NVOCTP_itemHdr_t::len, NVINTF_BADPARAM, NVINTF_DOANYID, NVINTF_DODELETE, NVINTF_DOFIND, NVINTF_DOITMID, NVINTF_DOREAD, NVINTF_DOSTART, NVINTF_DOSYSID, NVINTF_NOTFOUND, NVINTF_SUCCESS, NVINTF_SYSID_NVDRVR, NVOCTP_ALERT, NVOCTP_CMPRID, NVOCTP_FINDANY, NVOCTP_findItem(), NVOCTP_FINDITMID, NVOCTP_FINDSYSID, NVOCTP_LOCK, NVOCTP_pgOff, NVOCTP_readHeader(), NVOCTP_readItem(), NVOCTP_setItemInactive(), NVOCTP_UNLOCK, nvintf_nvproxy_t::subid, NVOCTP_itemHdr_t::subid, nvintf_nvproxy_t::sysid, and NVOCTP_itemHdr_t::sysid.
Referenced by NVOCTP_loadApiPtrsExt().
NVOCTP_doNVCRC()
static uint8_t NVOCTP_doNVCRC (uint8_t pg, uint16_t ofs, uint16_t len, uint8_t crc) static
References crc_update(), NVOCTP_read(), and NVOCTP_XFERBLKMAX.
Referenced by NVOCTP_verifyCRC().
NVOCTP_doRAMCRC()
static uint8_t NVOCTP_doRAMCRC (uint8_t * input, uint16_t len, uint8_t crc) static
References crc_update().
Referenced by NVOCTP_verifyCRC(), and NVOCTP_writeItem().
NVOCTP_erase()
static uint8_t NVOCTP_erase (uint8_t dstPg) static
References NVINTF_FAILURE, NVINTF_LOWPOWER, NVINTF_SUCCESS, NVOCTP_ALERT, NVOCTP_FLASHACCESS, and NVOCTP_FLASHOFFSET.
Referenced by NVOCTP_compactPage(), and NVOCTP_initNvApi().
NVOCTP_findItem()
static int16_t NVOCTP_findItem (uint8_t pg, uint16_t ofs, uint32_t cid, uint8_t flag) static
References NVOCTP_itemHdr_t::cmpid, NVOCTP_itemHdr_t::itemid, NVOCTP_itemHdr_t::len, NVINTF_BADPARAM, NVOCTP_ACTIVEIDBIT, NVOCTP_ALERT, NVOCTP_ASSERT, NVOCTP_compactPage(), NVOCTP_EXCEPTION, NVOCTP_FINDANY, NVOCTP_FINDITMID, NVOCTP_FINDSTRICT, NVOCTP_FINDSYSID, NVOCTP_FOLLOWBIT, NVOCTP_ITEMHDRLEN, NVOCTP_PGHDRLEN, NVOCTP_readHeader(), NVOCTP_setItemInactive(), NVOCTP_VALIDIDBIT, NVOCTP_itemHdr_t::stats, and NVOCTP_itemHdr_t::sysid.
Referenced by NVOCTP_checkItem(), NVOCTP_deleteItemApi(), and NVOCTP_doNextApi().
NVOCTP_findOffset()
static uint16_t NVOCTP_findOffset (uint8_t pg, uint16_t ofs) static
References NVOCTP_ERASEDBYTE, NVOCTP_ERASEDWORD, and NVOCTP_read().
Referenced by NVOCTP_initNvApi().
NVOCTP_getItemLenApi()
static uint32_t NVOCTP_getItemLenApi (NVINTF_itemID_t id) static
References len, NVOCTP_itemHdr_t::len, NVINTF_SUCCESS, NVOCTP_checkItem(), NVOCTP_FINDSTRICT, NVOCTP_LOCK, and NVOCTP_UNLOCK.
Referenced by NVOCTP_loadApiPtrs(), and NVOCTP_loadApiPtrsExt().
NVOCTP_initNvApi()
static uint8_t NVOCTP_initNvApi (void * param) static
References NVOCTP_diag_t::available, NVOCTP_pageHdr_t::cycle, FLASH_PAGE_SIZE, NVINTF_BADVERSION, NVINTF_FAILURE, NVINTF_NOTFOUND, NVINTF_NOTREADY, NVINTF_SUCCESS, NVOCTP_ALERT, NVOCTP_ASSERT, NVOCTP_compactPage(), NVOCTP_erase(), NVOCTP_EXCEPTION, NVOCTP_failF, NVOCTP_findOffset(), NVOCTP_ITEMHDRLEN, NVOCTP_MAXCYCLE, NVOCTP_MINCYCLE, NVOCTP_NULLPAGE, NVOCTP_nvEndPage, NVOCTP_NVS_INDEX, NVOCTP_PGACTIVE, NVOCTP_PGDATAOFS, NVOCTP_PGERASED, NVOCTP_PGHDRLEN, NVOCTP_PGHDROFS, NVOCTP_PGXFER, NVOCTP_read(), NVOCTP_readItemApi(), NVOCTP_setPageActive(), NVOCTP_SIGNATURE, NVOCTP_VERSION, NVOCTP_writeItemApi(), NVOCTP_diag_t::resets, NVOCTP_pageHdr_t::signature, NVOCTP_pageHdr_t::state, and NVOCTP_pageHdr_t::version.
Referenced by NVOCTP_loadApiPtrs(), NVOCTP_loadApiPtrsExt(), and NVOCTP_loadApiPtrsMin().
NVOCTP_loadApiPtrs()
void NVOCTP_loadApiPtrs (NVINTF_nvFuncts_t * pfn)
References nvintf_nvfuncts_t::compactNV, nvintf_nvfuncts_t::createItem, nvintf_nvfuncts_t::deleteItem, nvintf_nvfuncts_t::doNext, nvintf_nvfuncts_t::getItemLen, nvintf_nvfuncts_t::initNV, nvintf_nvfuncts_t::lockNV, NVOCTP_compactNvApi(), NVOCTP_createItemApi(), NVOCTP_deleteItemApi(), NVOCTP_getItemLenApi(), NVOCTP_initNvApi(), NVOCTP_readItemApi(), NVOCTP_writeItemApi(), nvintf_nvfuncts_t::readItem, nvintf_nvfuncts_t::unlockNV, and nvintf_nvfuncts_t::writeItem.
NVOCTP_loadApiPtrsExt()
void NVOCTP_loadApiPtrsExt (NVINTF_nvFuncts_t * pfn)
References nvintf_nvfuncts_t::compactNV, nvintf_nvfuncts_t::createItem, nvintf_nvfuncts_t::deleteItem, nvintf_nvfuncts_t::doNext, nvintf_nvfuncts_t::getItemLen, nvintf_nvfuncts_t::initNV, nvintf_nvfuncts_t::lockNV, NVOCTP_compactNvApi(), NVOCTP_createItemApi(), NVOCTP_deleteItemApi(), NVOCTP_doNextApi(), NVOCTP_getItemLenApi(), NVOCTP_initNvApi(), NVOCTP_lockNvApi(), NVOCTP_readItemApi(), NVOCTP_unlockNvApi(), NVOCTP_writeItemApi(), nvintf_nvfuncts_t::readItem, nvintf_nvfuncts_t::unlockNV, and nvintf_nvfuncts_t::writeItem.
Referenced by otPlatSettingsInit().
NVOCTP_loadApiPtrsMin()
void NVOCTP_loadApiPtrsMin (NVINTF_nvFuncts_t * pfn)
References nvintf_nvfuncts_t::compactNV, nvintf_nvfuncts_t::createItem, nvintf_nvfuncts_t::deleteItem, nvintf_nvfuncts_t::doNext, nvintf_nvfuncts_t::getItemLen, nvintf_nvfuncts_t::initNV, nvintf_nvfuncts_t::lockNV, NVOCTP_compactNvApi(), NVOCTP_initNvApi(), NVOCTP_readItemApi(), NVOCTP_writeItemApi(), nvintf_nvfuncts_t::readItem, nvintf_nvfuncts_t::unlockNV, and nvintf_nvfuncts_t::writeItem.
NVOCTP_lockNvApi()
static IArg NVOCTP_lockNvApi (void) static
Global function to lock the NV semaphore.
Returns
bool indicating success or failure
Referenced by NVOCTP_loadApiPtrsExt().
NVOCTP_newItem()
static uint8_t NVOCTP_newItem (NVOCTP_itemHdr_t * iHdr, uint8_t * pBuf) static
References FLASH_PAGE_SIZE, NVOCTP_itemHdr_t::len, NVINTF_BADLENGTH, NVINTF_SUCCESS, NVOCTP_ALERT, NVOCTP_compactPage(), NVOCTP_ITEMHDRLEN, and NVOCTP_writeItem().
Referenced by NVOCTP_createItemApi(), and NVOCTP_writeItemApi().
NVOCTP_read()
static void NVOCTP_read (uint8_t pg, uint16_t off, uint8_t * pBuf, uint16_t len) inline static
References NVOCTP_FLASHOFFSET.
Referenced by NVOCTP_compactPage(), NVOCTP_copyItem(), NVOCTP_doNVCRC(), NVOCTP_findOffset(), NVOCTP_initNvApi(), NVOCTP_readByte(), NVOCTP_readHeader(), and NVOCTP_readItem().
NVOCTP_readByte()
static uint8_t NVOCTP_readByte (uint8_t pg, uint16_t ofs) static
References NVOCTP_ONEBYTE, and NVOCTP_read().
Referenced by NVOCTP_setItemInactive().
NVOCTP_readHeader()
static void NVOCTP_readHeader (uint8_t pg, uint16_t ofs, NVOCTP_itemHdr_t * iHdr) static
References NVOCTP_itemHdr_t::cmpid, NVOCTP_itemHdr_t::crc8, NVOCTP_itemHdr_t::hofs, NVOCTP_itemHdr_t::itemid, NVOCTP_itemHdr_t::len, NVOCTP_ACTIVEIDBIT, NVOCTP_ALERT, NVOCTP_CMPRID, NVOCTP_FOLLOWBIT, NVOCTP_ITEMHDRLEN, NVOCTP_ONEBYTE, NVOCTP_read(), NVOCTP_SIGNATURE, NVOCTP_VALIDIDBIT, NVOCTP_itemHdr_t::sig, NVOCTP_itemHdr_t::stats, NVOCTP_itemHdr_t::subid, and NVOCTP_itemHdr_t::sysid.
Referenced by NVOCTP_checkItem(), NVOCTP_compactPage(), NVOCTP_doNextApi(), and NVOCTP_findItem().
NVOCTP_readItem()
static uint8_t NVOCTP_readItem (NVOCTP_itemHdr_t * iHdr, uint16_t ofs, uint16_t len, void * pBuf) static
References NVOCTP_itemHdr_t::crc8, NVOCTP_itemHdr_t::hofs, NVOCTP_itemHdr_t::len, NVINTF_BADLENGTH, NVINTF_BADOFFSET, NVINTF_SUCCESS, NVOCTP_CRCONREAD, NVOCTP_read(), and NVOCTP_verifyCRC().
Referenced by NVOCTP_doNextApi(), and NVOCTP_readItemApi().
NVOCTP_readItemApi()
static uint8_t NVOCTP_readItemApi (NVINTF_itemID_t id, uint16_t ofs, uint16_t len, void * buf) static
References NVINTF_BADPARAM, NVINTF_SUCCESS, NVOCTP_checkItem(), NVOCTP_FINDSTRICT, NVOCTP_LOCK, NVOCTP_readItem(), and NVOCTP_UNLOCK.
Referenced by NVOCTP_initNvApi(), NVOCTP_loadApiPtrs(), NVOCTP_loadApiPtrsExt(), and NVOCTP_loadApiPtrsMin().
NVOCTP_setCheckVoltage()
void NVOCTP_setCheckVoltage (void * funcPtr)
References NVOCTP_voltCheckFptr.
NVOCTP_setItemInactive()
static void NVOCTP_setItemInactive (uint16_t hOfs) static
References NVOCTP_ACTIVEIDBIT, NVOCTP_HDRVLDOFS, NVOCTP_readByte(), and NVOCTP_writeByte().
Referenced by NVOCTP_deleteItemApi(), NVOCTP_doNextApi(), NVOCTP_findItem(), NVOCTP_writeItem(), and NVOCTP_writeItemApi().
NVOCTP_setPageActive()
static void NVOCTP_setPageActive (uint8_t pg) static
References NVINTF_SUCCESS, NVOCTP_MAXCYCLE, NVOCTP_MINCYCLE, NVOCTP_PGACTIVE, NVOCTP_PGHDRCYC, NVOCTP_PGHDRLEN, NVOCTP_PGHDRPST, NVOCTP_PGHDRSIG, NVOCTP_PGHDRVER, NVOCTP_SIGNATURE, NVOCTP_VERSION, and NVOCTP_write().
Referenced by NVOCTP_compactPage(), and NVOCTP_initNvApi().
NVOCTP_unlockNvApi()
static void NVOCTP_unlockNvApi (IArg key) static
Referenced by NVOCTP_loadApiPtrsExt().
NVOCTP_verifyCRC()
static uint8_t NVOCTP_verifyCRC (uint16_t iOfs, uint16_t len, uint8_t crc) static
References NVINTF_CORRUPT, NVINTF_SUCCESS, NVOCTP_ALERT, NVOCTP_doNVCRC(), NVOCTP_doRAMCRC(), and NVOCTP_HDRCRCINC.
Referenced by NVOCTP_compactPage(), and NVOCTP_readItem().
NVOCTP_write()
static uint8_t NVOCTP_write (uint8_t dstPg, uint16_t off, uint8_t * pBuf, uint16_t len) static
References NVINTF_FAILURE, NVINTF_LOWPOWER, NVINTF_SUCCESS, NVOCTP_ALERT, NVOCTP_FLASHACCESS, and NVOCTP_FLASHOFFSET.
Referenced by NVOCTP_copyItem(), NVOCTP_setPageActive(), NVOCTP_writeByte(), and NVOCTP_writeItem().
NVOCTP_writeByte()
static void NVOCTP_writeByte (uint8_t pg, uint16_t ofs, uint8_t bwv) static
References NVOCTP_write().
Referenced by NVOCTP_compactPage(), and NVOCTP_setItemInactive().
NVOCTP_writeItem()
static void NVOCTP_writeItem (NVOCTP_itemHdr_t * iHdr, uint8_t dstPg, uint8_t * pBuf) static
References FLASH_PAGE_SIZE, NVOCTP_itemHdr_t::itemid, NVOCTP_itemHdr_t::len, NVINTF_BADLENGTH, NVOCTP_ACTIVEIDBIT, NVOCTP_ALERT, NVOCTP_ASSERT, NVOCTP_doRAMCRC(), NVOCTP_ERASEDBYTE, NVOCTP_HDRCRCINC, NVOCTP_ITEMHDRLEN, NVOCTP_setItemInactive(), NVOCTP_SIGNATURE, NVOCTP_SMALLITEM, NVOCTP_write(), NVOCTP_itemHdr_t::subid, and NVOCTP_itemHdr_t::sysid.
Referenced by NVOCTP_compactPage(), and NVOCTP_newItem().
NVOCTP_writeItemApi()
static uint8_t NVOCTP_writeItemApi (NVINTF_itemID_t id, uint16_t len, void * buf) static
References NVOCTP_itemHdr_t::hofs, len, NVOCTP_itemHdr_t::len, NVINTF_BADPARAM, NVINTF_NOTFOUND, NVINTF_SUCCESS, NVOCTP_checkItem(), NVOCTP_failW, NVOCTP_FINDSTRICT, NVOCTP_FLASHACCESS, NVOCTP_LOCK, NVOCTP_newItem(), NVOCTP_setItemInactive(), and NVOCTP_UNLOCK.
Referenced by NVOCTP_initNvApi(), NVOCTP_loadApiPtrs(), NVOCTP_loadApiPtrsExt(), and NVOCTP_loadApiPtrsMin().
Variable Documentation
NVOCTP_activePg
uint8_t NVOCTP_activePg static
NVOCTP_failF
uint8_t NVOCTP_failF = NVINTF_NOTREADY static
Referenced by NVOCTP_compactNvApi(), and NVOCTP_initNvApi().
NVOCTP_failW
uint8_t NVOCTP_failW static
Referenced by NVOCTP_compactNvApi(), and NVOCTP_writeItemApi().
NVOCTP_gMutexPri
GateMutexPri_Handle NVOCTP_gMutexPri static
NVOCTP_itemBuffer
uint8_t NVOCTP_itemBuffer[NVOCTP_SMALLITEM] static
NVOCTP_nvBegPage
uint8_t NVOCTP_nvBegPage static
Referenced by NVOCTP_compactPage().
NVOCTP_nvEndPage
uint8_t NVOCTP_nvEndPage static
Referenced by NVOCTP_initNvApi().
NVOCTP_nvsAttrs
NVS_Attrs NVOCTP_nvsAttrs static
NVOCTP_nvsHandle
NVS_Handle NVOCTP_nvsHandle static
NVOCTP_pgCycle
uint8_t NVOCTP_pgCycle static
NVOCTP_pgOff
uint16_t NVOCTP_pgOff static
Referenced by NVOCTP_compactNvApi(), NVOCTP_compactPage(), and NVOCTP_doNextApi().
NVOCTP_voltCheckFptr
bool(* NVOCTP_voltCheckFptr) (void) static
Referenced by NVOCTP_setCheckVoltage().
© Copyright 1995-2018, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale