TI Thread API Documentation: examples/sensors/opt3001.c File Reference
opt3001.c File Reference
Macros
#define CONVERSION_MODE 0xC000
#define LUX_BASE_RES 00.01F
#define RANGE_BASE 00040.95F
#define RANGE_BITS 0xF000
#define RANGE_MAX 83865.60F
#define READ_BUF_SIZE 2
#define WRITE_BUF_SIZE 3
Functions
static float convertToLux (uint16_t reg)
static bool i2cTransferFxn (I2C_Handle handle, I2C_Transaction transaction)
bool OPT3001_close (OPT3001_Handle handle)
Function to close a OPT3001 sensor specified by the OPT3001 handle.
bool OPT3001_disableInterrupt (OPT3001_Handle handle)
Function to disable the GPIO interrupt.
bool OPT3001_enableInterrupt (OPT3001_Handle handle)
Enable interrupts from the specified OPT3001.
bool OPT3001_getLux (OPT3001_Handle handle, float *data)
Function to get the sensor's lux reading.
bool OPT3001_getLuxLimits (OPT3001_Handle handle, float *high, float *low)
Function to get the sensor's lux limits.
void OPT3001_init ()
Function to initialize OPT3001 driver.
OPT3001_Handle OPT3001_open (unsigned int index, I2C_Handle i2cHandle, OPT3001_Params *params)
Function to open a given OPT3001 sensor.
void OPT3001_Params_init (OPT3001_Params *params)
Function to initialize a OPT3001_Params struct to its defaults.
bool OPT3001_readRegister (OPT3001_Handle handle, uint16_t *data, uint8_t registerAddress)
Read the specified register from a OPT3001 sensor.
bool OPT3001_setConversionMode (OPT3001_Handle handle, OPT3001_ConversionMode mode)
Function to change the conversion mode.
bool OPT3001_setLuxLimits (OPT3001_Handle handle, float high, float low)
Function to get the sensor's lux limits.
bool OPT3001_setRange (OPT3001_Handle handle, OPT3001_FullRange range)
Set the lux measurement result range.
bool OPT3001_writeRegister (OPT3001_Handle handle, uint16_t data, uint8_t registerAddress)
Write the specified data to a OPT3001 sensor.
Variables
OPT3001_Config OPT3001_config []
const OPT3001_Params OPT3001_defaultParams
Macro Definition Documentation
CONVERSION_MODE
#define CONVERSION_MODE 0xC000
LUX_BASE_RES
#define LUX_BASE_RES 00.01F
Referenced by convertToLux(), and OPT3001_setLuxLimits().
RANGE_BASE
#define RANGE_BASE 00040.95F
Referenced by OPT3001_setLuxLimits().
RANGE_BITS
#define RANGE_BITS 0xF000
Referenced by OPT3001_setRange().
RANGE_MAX
#define RANGE_MAX 83865.60F
Referenced by OPT3001_close(), and OPT3001_setLuxLimits().
READ_BUF_SIZE
#define READ_BUF_SIZE 2
Referenced by OPT3001_readRegister().
WRITE_BUF_SIZE
#define WRITE_BUF_SIZE 3
Referenced by OPT3001_writeRegister().
Function Documentation
convertToLux()
static float convertToLux (uint16_t reg) static
References LUX_BASE_RES.
Referenced by OPT3001_getLux(), and OPT3001_getLuxLimits().
i2cTransferFxn()
static bool i2cTransferFxn (I2C_Handle handle, I2C_Transaction transaction) static
Referenced by OPT3001_readRegister(), and OPT3001_writeRegister().
OPT3001_close()
bool OPT3001_close (OPT3001_Handle handle)
Function to close a OPT3001 sensor specified by the OPT3001 handle.
The OPT3001 hardware will be placed in a low power state in which ADC conversions are disabled. If the pin is configured to interrupt, the GPIO pin interrupts will be disabled. The I2C handle is not affected.
Precondition
OPT3001_open() had to be called first.
Parameters
handle A OPT3001_Handle returned from OPT3001_open()
Returns
true on success or false upon failure.
References OPT3001_Object::callback, OPT3001_Object::i2cHandle, OPT3001_Config::object, OPT3001_disableInterrupt(), OPT3001_setConversionMode(), OPT3001_setLuxLimits(), OPT3001_SHUTDOWN, and RANGE_MAX.
OPT3001_disableInterrupt()
bool OPT3001_disableInterrupt (OPT3001_Handle handle)
Function to disable the GPIO interrupt.
Interrupts on the OPT3001 specific GPIO index will be disabled. The lux limits set are unaffected.
See also
OPT3001_enableInterrupt()
Precondition
Had to call OPT3001_enableInterrupt() first for this function to have an effect.
Parameters
handle A OPT3001_Handle
Returns
true on success or false upon failure.
References OPT3001_Config::hwAttrs, and OPT3001_Config::object.
Referenced by OPT3001_close().
OPT3001_enableInterrupt()
bool OPT3001_enableInterrupt (OPT3001_Handle handle)
Enable interrupts from the specified OPT3001.
Interrupts on the OPT3001 specific GPIO index will be enabled.
See also
OPT3001_disableInterrupt()
Precondition
OPT3001_setLuxLimits() must have been called first to recieve interrupts from the OPT3001 INT pin.
Parameters
handle A OPT3001_Handle
Returns
true on success or false upon failure.
References OPT3001_Config::hwAttrs, OPT3001_Config::object, OPT3001_CONFIG, and OPT3001_readRegister().
OPT3001_getLux()
bool OPT3001_getLux (OPT3001_Handle handle, float * data)
Function to get the sensor's lux reading.
Parameters
handle A OPT3001_Handle
data A pointer to a float to store the lux value.
Returns
true on success, false on failure
References convertToLux(), OPT3001_readRegister(), and OPT3001_RESULT.
Referenced by coapHandleLuminosity().
OPT3001_getLuxLimits()
bool OPT3001_getLuxLimits (OPT3001_Handle handle, float * high, float * low)
Function to get the sensor's lux limits.
Parameters
handle A OPT3001_Handle
high A pointer to a float to store the high limit
low A pointer to a float to store the low limit
Returns
true on success, false on failure
References convertToLux(), OPT3001_HILIMIT, OPT3001_LOLIMIT, and OPT3001_readRegister().
OPT3001_init()
void OPT3001_init ()
Function to initialize OPT3001 driver.
This function will initialize the OPT3001 driver. This should be called before BIOS_start().
References i2cHandle, and OPT3001_Config::object.
Referenced by initOPT().
OPT3001_open()
OPT3001_Handle OPT3001_open (unsigned int index, I2C_Handle i2cHandle, OPT3001_Params * params)
Function to open a given OPT3001 sensor.
Function to initialize a given OPT3001 sensor specified by the particular index value. This function must be called from a task context. If one intends to use the INT pin, a callback function must be specified in the OPT3001_Params structure. Additionally, a gpioIndex must be setup and specified in the OPT3001_HWAttrs structure.
The I2C controller must be operating in BLOCKING mode. Failure to ensure the I2C_Handle is in BLOCKING mode will result in undefined behavior.
The user should ensure that each sensor has its own slaveAddress, gpioIndex (if alarming) and OPT3001Index.
Precondition
OPT3001_init() has to be called first
Parameters
OPT3001Index Logical sensor number for the OPT3001 indexed into the OPT3001_config table
i2cHandle An I2C_Handle opened in BLOCKING mode
params A pointer to OPT3001_Params structure. If NULL, it will use default values.
Returns
A OPT3001_Handle on success, or a NULL on failure.
See also
OPT3001_init()
OPT3001_Params_init()
OPT3001_close()
References OPT3001_Object::callback, OPT3001_Params::callback, OPT3001_Params::conversionMode, OPT3001_Params::conversionReady, OPT3001_Params::conversionTime, OPT3001_Params::faultCount, OPT3001_HWAttrs::gpioIndex, i2cHandle, OPT3001_Object::i2cHandle, OPT3001_Params::interruptMode, OPT3001_CONFIG, OPT3001_LOLIMIT, OPT3001_writeRegister(), and OPT3001_Params::range.
Referenced by initOPT().
OPT3001_Params_init()
void OPT3001_Params_init (OPT3001_Params * params)
Function to initialize a OPT3001_Params struct to its defaults.
Parameters
params A pointer to OPT3001_Params structure for initialization.
Default values are:
 conversionMode    = OPT3001_CONTINUOUS
 conversionReady   = OPT3001_CONVRD_DIS
 conversionTime    = OPT3001_800MS
 faultCount        = OPT3001_FAULT1
 range             = OPT3001_AUTO
 interruptMode     = OPT3001_LATCH
 callback          = NULL
References OPT3001_defaultParams.
Referenced by initOPT().
OPT3001_readRegister()
bool OPT3001_readRegister (OPT3001_Handle handle, uint16_t * data, uint8_t registerAddress)
Read the specified register from a OPT3001 sensor.
Parameters
handle A OPT3001_Handle
registerAddress Register address
data A pointer to a data register in which received data will be written to. Must be 16 bits.
Returns
true on success or false upon failure.
References OPT3001_Config::hwAttrs, i2cTransferFxn(), OPT3001_Config::object, and READ_BUF_SIZE.
Referenced by OPT3001_enableInterrupt(), OPT3001_getLux(), OPT3001_getLuxLimits(), OPT3001_setConversionMode(), and OPT3001_setRange().
OPT3001_setConversionMode()
bool OPT3001_setConversionMode (OPT3001_Handle handle, OPT3001_ConversionMode mode)
Function to change the conversion mode.
This function will set the OPT3001 hardware to operate in the coversion mode specified by OPT3001_ConversionMode.
Precondition
OPT3001_open has to be called first.
Parameters
handle A OPT3001_Handle
mode A OPT3001_ConversionMode specifying the mode to operate in.
Returns
true on success or false upon failure.
References OPT3001_CONFIG, OPT3001_readRegister(), OPT3001_SINGLESHOT, and OPT3001_writeRegister().
Referenced by OPT3001_close().
OPT3001_setLuxLimits()
bool OPT3001_setLuxLimits (OPT3001_Handle handle, float high, float low)
Function to get the sensor's lux limits.
Parameters
handle A OPT3001_Handle
high A float specifying the high limit. Use OPT3001_IGNORE if a h storingigh limit is not desired.
low A float specifying the low limit. Use OPT3001_IGNORE if a low limit is not desired.
Returns
true on success, false on failure
References LUX_BASE_RES, OPT3001_HILIMIT, OPT3001_IGNORE, OPT3001_LOLIMIT, OPT3001_writeRegister(), RANGE_BASE, and RANGE_MAX.
Referenced by OPT3001_close().
OPT3001_setRange()
bool OPT3001_setRange (OPT3001_Handle handle, OPT3001_FullRange range)
Set the lux measurement result range.
Parameters
handle A OPT3001_Handle
OPT3001_FullRange A range value specifying max possible result
Returns
true on success or false upon failure.
References OPT3001_CONFIG, OPT3001_readRegister(), OPT3001_writeRegister(), and RANGE_BITS.
OPT3001_writeRegister()
bool OPT3001_writeRegister (OPT3001_Handle handle, uint16_t data, uint8_t registerAddress)
Write the specified data to a OPT3001 sensor.
This function is not thread safe. When writing to a handle, it is possible to overwrite data written by another task.
For example: Task A and B are writing to the configuration register. Task A has a higher priority than Task B. Task B is running and reads the configuration register. Task A then preempts Task B and reads the configuration register, performs a logical OR and writes to the configuration register. Task B then resumes execution and performs its logical OR and writes to the configuration register–overwriting the data written by Task A.
Such instances can be prevented through the use of Semaphores. Below is an example which utilizes an initialized Semaphore_handle, OPT3001Lock.
if (Semaphore_pend(OPT3001Lock, BIOS_NO_WAIT)) {
    //Perform read/write operations
}
else {
    Task_sleep(1000);
}
Semaphore_post(OPT3001Lock);
Parameters
handle A OPT3001_Handle
data A uint16_t to be written to the OPT3001 sensor
registerAddress OPT3001 register address
Returns
true on success or false upon failure.
References OPT3001_Config::hwAttrs, i2cTransferFxn(), OPT3001_Config::object, and WRITE_BUF_SIZE.
Referenced by OPT3001_open(), OPT3001_setConversionMode(), OPT3001_setLuxLimits(), and OPT3001_setRange().
Variable Documentation
OPT3001_config
OPT3001_Config OPT3001_config[]
OPT3001_defaultParams
const OPT3001_Params OPT3001_defaultParams
Initial value:
= {
        OPT3001_CONTINUOUS,
        OPT3001_CONVRD_DIS,
        OPT3001_800MS,
        OPT3001_FAULT1,
        OPT3001_AUTO,
        OPT3001_LATCH,
        NULL
}
Referenced by OPT3001_Params_init().
© Copyright 1995-2018, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale