TI Thread API Documentation: examples/sensors/opt3001.h File Reference
opt3001.h File Reference
Detailed Description
OPT3001 Ambient Light Sensor Driver.
============================================================================
The OPT3001 is a sensor that measures the intensity of visible light. The spectral response of the sensor tightly matches the photopic response of the human eye and includes significant infrared rejection.
The OPT3001 header file should be included in an application as follows:
#include <opt3001.h>
Operation
The OPT3001 driver simplifies using a OPT3001 sensor to perform lux readings. The board's I2C peripheral and pins must be configured and then initialized by using Board_initI2C(). Similarly, any GPIO pins must be configured and then initialized by using Board_initGPIO(). A OPT3001_config array should be defined by the application. The OPT3001_config array should contain pointers to a defined OPT3001_HwAttrs and allocated array for the OPT3001_Object structures. OPT3001_init() must be called prior to using OPT3001_open().
The APIs in this driver serve as an interface to a DPL(Driver Porting Layer) The specific implementations are responsible for creating all the RTOS specific primitives to allow for thread-safe operation.
This driver has no dynamic memory allocation.
Defining OPT3001_Config, OPT3001_Object and OPT3001_HwAttrs
Each structure must be defined by the application. The following example is for a MSP432 in which an OPT3001 sensor is setup. The following declarations are placed in "MSP_EXP432P401R.h" and "MSP_EXP432P401R.c" respectively. How the gpioIndex is defined is detailed in the next example.
"MSP_EXP432P401R.h"
typedef enum MSP_EXP432P401R_OPT3001Name {
    OPT3001_AMBIENT = 0, // Sensor measuring ambient light
    MSP_EXP432P401R_OPT3001COUNT
} MSP_EXP432P401R_OPT3001Name;
"MSP_EXP432P401R.c"
#include <opt3001.h>
OPT3001_Object OPT3001_object[MSP_EXP432P401R_OPT3001COUNT];
const OPT3001_HWAttrs OPT3001_hwAttrs[MSP_EXP432P401R_OPT3001COUNT] = {
    {
        .slaveAddress = OPT3001_SA1, // 0x42
        .gpioIndex = MSP_EXP432P401R_OPT3001_0,
    },
};
const OPT3001_Config OPT3001_config[] = {
    {
        .hwAttrs = &OPT3001_hwAttrs[0],
        .objects = &OPT3001_object[0],
    },
    {NULL, NULL},
};
Setting up GPIO configurations
The following example is for a MSP432 in which an OPT3001 sensors needs a GPIO pin for alarming. The following definitions are in "MSP_EXP432P401R.h" and "MSP_EXP432P401R.c" respectively. This example uses GPIO pin 1.5. The GPIO_CallbackFxn table must contain as many indices as GPIO_CallbackFxns that will be specified by the application. For each INT pin used, an index should be allocated as NULL.
"MSP_EXP432P401R.h"
typedef enum MSP_EXP432P401R_GPIOName {
    MSP_EXP432P401R_OPT3001_0, // Pin for sensor measuring ambient light
    MSP_EXP432P401R_GPIOCOUNT
} MSP_EXP432P401R_GPIOName;
"MSP_EXP432P401R.c"
#include <gpio.h>
GPIO_PinConfig gpioPinConfigs[] = {
    GPIOMSP432_P1_5 | GPIO_CFG_INPUT | GPIO_CFG_IN_INT_FALLING
};
GPIO_CallbackFxn gpioCallbackFunctions[] = {
    NULL
};
Opening a I2C Handle
The I2C controller must be in blocking mode. This will seamlessly allow for multiple I2C endpoints without conflicting callback functions. The I2C_open() call requires a configured index. This index must be defined by the application in accordance to the I2C driver. The default transfer mode for an I2C_Params structure is I2C_MODE_BLOCKING. In the example below, the transfer mode is set explicitly for clarity. Additionally, the OPT3001 hardware is capable of communicating at 400kHz. The default bit rate for an I2C_Params structure is I2C_100kHz.
#include <ti/drivers/I2C.h>
I2C_Handle      i2cHandle;
I2C_Params      i2cParams;
I2C_Params_init(&i2cParams);
i2cParams.transferMode = I2C_MODE_BLOCKING;
i2cParams.bitRate = I2C_400kHz;
i2cHandle = I2C_open(someI2C_configIndexValue, &i2cParams);
Opening a OPT3001 sensor with default parameters
The OPT3001_open() call must be made in a task context.
#include <opt3001.h>
OPT3001_Handle opt3001Handle;
OPT3001_init();
opt3001Handle = OPT3001_open(OPT3001_AMBIENT, i2cHandle, NULL);
Opening a OPT3001 sensor to ALERT
In the following example, a callback function is specified in the opt3001Params structure. This indicates to the module that the INT pin will be used. The sensor will assert the INT pin whenever the lux exceeds 44178.8 (lx). The low limit is ignored. No interrupt will be generated until OPT3001_enableInterrupt() is called.
#include <opt3001.h>
OPT3001_Handle opt3001Handle;
OPT3001_Params opt3001Params;
OPT3001_Params_init(&opt3001Params);
opt3001Params.callback = gpioCallbackFxn;
opt3001Handle = OPT3001_open(OPT3001_ROOMTEMP, i2cHandle, &opt3001Params);
OPT3001_setLuxLimits(opt3001Handle, 44178.8, OPT3001_IGNORE);
OPT3001_enableInterrupt(opt3001Handle);
Data Structures
struct OPT3001_Config
OPT3001 configuration.
struct OPT3001_HWAttrs
Hardware specific settings for a OPT3001 sensor.
struct OPT3001_Object
Members should not be accessed by the application.
struct OPT3001_Params
OPT3001 Parameters.
Macros
#define OPT3001_CONFIG 0x0001 /* Configuration Register */
#define OPT3001_CRF 0x0080 /* Conversion Ready Field */
#define OPT3001_DEVICEID 0x007F /* Device ID Register */
#define OPT3001_FH 0x0040 /* Flag High Field */
#define OPT3001_FL 0x0020 /* Flag Low Field */
#define OPT3001_HILIMIT 0x0003 /* High-Limit Register */
#define OPT3001_IGNORE 0xFFFF
Ignore lux limit define.
#define OPT3001_LOLIMIT 0x0002 /* Low-Limit Register */
#define OPT3001_MFTID 0x007E /* Manufacturer ID Register */
#define OPT3001_OVF 0x0100 /* Overflow Flag Field */
#define OPT3001_RESULT 0x0000 /* Result Register (Read-Only) */
Typedefs
typedef struct OPT3001_Config OPT3001_Config
OPT3001 configuration.
typedef enum OPT3001_ConversionMode OPT3001_ConversionMode
OPT3001 ADC conversion mode.
typedef enum OPT3001_ConversionReady OPT3001_ConversionReady
OPT3001 Conversion Ready Interrupt Mode.
typedef enum OPT3001_ConversionTime OPT3001_ConversionTime
OPT3001 Conversion Time.
typedef enum OPT3001_FaultCount OPT3001_FaultCount
OPT3001 Fault Count.
typedef enum OPT3001_FullRange OPT3001_FullRange
OPT3001 Result Register Range.
typedef struct OPT3001_Config * OPT3001_Handle
A handle that is returned from a OPT3001_open() call.
typedef struct OPT3001_HWAttrs OPT3001_HWAttrs
Hardware specific settings for a OPT3001 sensor.
typedef enum OPT3001_InterruptMode OPT3001_InterruptMode
OPT3001 Interrupt Mode.
typedef struct OPT3001_Object OPT3001_Object
Members should not be accessed by the application.
typedef struct OPT3001_Params OPT3001_Params
OPT3001 Parameters.
typedef enum OPT3001_SlaveAddress OPT3001_SlaveAddress
OPT3001 I2C slave addresses.
Enumerations
enum OPT3001_ConversionMode { OPT3001_SHUTDOWN = 0x0000, OPT3001_SINGLESHOT = 0x0200, OPT3001_CONTINUOUS = 0x0600 }
OPT3001 ADC conversion mode.
enum OPT3001_ConversionReady { OPT3001_CONVRD_DIS = 0x000, OPT3001_CONVRD_EN = 0xC000 }
OPT3001 Conversion Ready Interrupt Mode.
enum OPT3001_ConversionTime { OPT3001_100MS = 0, OPT3001_800MS = 0x0800 }
OPT3001 Conversion Time.
enum OPT3001_FaultCount { OPT3001_FAULT1 = 0x0000, OPT3001_FAULT2 = 0x0001, OPT3001_FAULT4 = 0x0002, OPT3001_FAULT8 = 0x0003 }
OPT3001 Fault Count.
enum OPT3001_FullRange {
OPT3001_RANGE0 = 0x0000, OPT3001_RANGE1 = 0x1000, OPT3001_RANGE2 = 0x2000, OPT3001_RANGE3 = 0x3000,
OPT3001_RANGE4 = 0x4000, OPT3001_RANGE5 = 0x5000, OPT3001_RANGE6 = 0x6000, OPT3001_RANGE7 = 0x7000,
OPT3001_RANGE8 = 0x8000, OPT3001_RANGE9 = 0x9000, OPT3001_RANGE10 = 0xA000, OPT3001_RANGE11 = 0xB000,
OPT3001_AUTO = 0xC000
}
OPT3001 Result Register Range.
enum OPT3001_InterruptMode { OPT3001_NOLATCH = 0, OPT3001_LATCH = 0x0010 }
OPT3001 Interrupt Mode.
enum OPT3001_SlaveAddress { OPT3001_SA1 = 0x44, OPT3001_SA2 = 0x45, OPT3001_SA3 = 0x46, OPT3001_SA4 = 0x47 }
OPT3001 I2C slave addresses.
Functions
bool OPT3001_close (OPT3001_Handle handle)
Function to close a OPT3001 sensor specified by the OPT3001 handle.
bool OPT3001_disableInterrupt (OPT3001_Handle handle)
Function to disable the GPIO interrupt.
bool OPT3001_enableInterrupt (OPT3001_Handle handle)
Enable interrupts from the specified OPT3001.
bool OPT3001_getLux (OPT3001_Handle handle, float *data)
Function to get the sensor's lux reading.
bool OPT3001_getLuxLimits (OPT3001_Handle handle, float *high, float *low)
Function to get the sensor's lux limits.
void OPT3001_init ()
Function to initialize OPT3001 driver.
OPT3001_Handle OPT3001_open (unsigned int index, I2C_Handle i2cHandle, OPT3001_Params *params)
Function to open a given OPT3001 sensor.
void OPT3001_Params_init (OPT3001_Params *params)
Function to initialize a OPT3001_Params struct to its defaults.
bool OPT3001_readRegister (OPT3001_Handle handle, uint16_t *data, uint8_t registerAddress)
Read the specified register from a OPT3001 sensor.
bool OPT3001_setConversionMode (OPT3001_Handle handle, OPT3001_ConversionMode mode)
Function to change the conversion mode.
bool OPT3001_setLuxLimits (OPT3001_Handle handle, float high, float low)
Function to get the sensor's lux limits.
bool OPT3001_setRange (OPT3001_Handle handle, OPT3001_FullRange range)
Set the lux measurement result range.
bool OPT3001_writeRegister (OPT3001_Handle handle, uint16_t data, uint8_t registerAddress)
Write the specified data to a OPT3001 sensor.
Macro Definition Documentation
OPT3001_CONFIG
#define OPT3001_CONFIG 0x0001 /* Configuration Register */
Referenced by OPT3001_enableInterrupt(), OPT3001_open(), OPT3001_setConversionMode(), and OPT3001_setRange().
OPT3001_CRF
#define OPT3001_CRF 0x0080 /* Conversion Ready Field */
OPT3001_DEVICEID
#define OPT3001_DEVICEID 0x007F /* Device ID Register */
OPT3001_FH
#define OPT3001_FH 0x0040 /* Flag High Field */
OPT3001_FL
#define OPT3001_FL 0x0020 /* Flag Low Field */
OPT3001_HILIMIT
#define OPT3001_HILIMIT 0x0003 /* High-Limit Register */
Referenced by OPT3001_getLuxLimits(), and OPT3001_setLuxLimits().
OPT3001_IGNORE
#define OPT3001_IGNORE 0xFFFF
Ignore lux limit define.
OPT3001_IGNORE should be used to ignore or unset a lux limit.
In the following example, the lux limits are set and reset:
OPT3001_setLuxLimits(handle, 43210, 76543.7);
OPT3001_enableInterrupt(handle);
//Additional application code...
OPT3001_setLuxLimits(handle, OPT3001_IGNORE, OPT3001_IGNORE);
Referenced by OPT3001_setLuxLimits().
OPT3001_LOLIMIT
#define OPT3001_LOLIMIT 0x0002 /* Low-Limit Register */
Referenced by OPT3001_getLuxLimits(), OPT3001_open(), and OPT3001_setLuxLimits().
OPT3001_MFTID
#define OPT3001_MFTID 0x007E /* Manufacturer ID Register */
OPT3001_OVF
#define OPT3001_OVF 0x0100 /* Overflow Flag Field */
OPT3001_RESULT
#define OPT3001_RESULT 0x0000 /* Result Register (Read-Only) */
Referenced by OPT3001_getLux().
Typedef Documentation
OPT3001_Config
typedef struct OPT3001_Config OPT3001_Config
OPT3001 configuration.
The OPT3001_Config structure contains a set of pointers used to characterize the OPT3001 driver implementation.
This structure needs to be defined and provided by the application.
OPT3001_ConversionMode
typedef enum OPT3001_ConversionMode OPT3001_ConversionMode
OPT3001 ADC conversion mode.
The conversion mode controls whether the device is operating in continuous conversion, single-shot, or low-power shutdown mode. The hardware default is shutdown mode such that upon power-up, the device does not perform conversions. When single-shot mode is selected, the device performs a conversion and then enters shutdown mode upon completion.
OPT3001_ConversionReady
typedef enum OPT3001_ConversionReady OPT3001_ConversionReady
OPT3001 Conversion Ready Interrupt Mode.
Using OPT3001_CONV_EN generates an interrupt when the conversion ready field indicates a conversion is complete. The conversion ready field is set to 1 at the end of a conversion and cleared when the configuration register is subsequuently read or written with any value except one containing the OPT3001_SHUTDOWN field command. This mode can be used in conjuction with OPT3001_LATCH or OPT3001_NOLATCH.
OPT3001_ConversionTime
typedef enum OPT3001_ConversionTime OPT3001_ConversionTime
OPT3001 Conversion Time.
The conversion time determines the length of the light to digital conversion process. A longer conversion time allows for a lower noise measurement. The conversion time also relates to the effective resolution of the data conversion process. Using 800ms ensures full resolution of the result register while 100ms may limit the resolution based upon the range.
OPT3001_FaultCount
typedef enum OPT3001_FaultCount OPT3001_FaultCount
OPT3001 Fault Count.
The fault count field instructs the device as to how many consecutive fault events are required to trigger the interrupt reporting mechanism: the INT pin, the flag high field, and flag low field. When the fault count is reached, the INT pin is asserted.
OPT3001_FullRange
typedef enum OPT3001_FullRange OPT3001_FullRange
OPT3001 Result Register Range.
The range field selects the full-scale lux range of the device. The result register may contain a value up to that specified by the range. Greater range constitutes lower resolution while less range consitutes higher resolution.
Automatic scaling will determine the optimum range based on a 10-ms measurement of current lighting conditions. With every measurement there after, the range is automatically adjusted based on the result (E.g If the result is towards the upper side of the range, the full-scale range is increased. If the result is towards the lower side of the range, the full-scale range is decreased). If the result is outside of the automatically set range, the current result is aborted and a 10-ms measurement is taken to re-assess and properly reset the full-scale range. Therefore, during fast optical transients in automatic mode, a measurement can possibly take 10 ms rather the time set in OPT3001_ConversionTime.
OPT3001_Handle
typedef struct OPT3001_Config* OPT3001_Handle
A handle that is returned from a OPT3001_open() call.
OPT3001_HWAttrs
typedef struct OPT3001_HWAttrs OPT3001_HWAttrs
Hardware specific settings for a OPT3001 sensor.
This structure should be defined and provided by the application. The gpioIndex should be defined in accordance of the GPIO driver. The pin must be configured as GPIO_CFG_INPUT and GPIO_CFG_IN_INT_FALLING.
OPT3001_InterruptMode
typedef enum OPT3001_InterruptMode OPT3001_InterruptMode
OPT3001 Interrupt Mode.
Interrupt mode controls the behavior of the INT pin.
If no latch (0), the INT pin is asserted whenever the enabled alert conditions are met. The INT pin will de-assert automatically when the condition clears.
In latched mode (1), the INT pin is asserted whenever the appropriate conditions are met. The INT pin will remain asserted until the application performs a clearing event (E.g reading the configuration register).
OPT3001_Object
typedef struct OPT3001_Object OPT3001_Object
Members should not be accessed by the application.
OPT3001_Params
typedef struct OPT3001_Params OPT3001_Params
OPT3001 Parameters.
OPT3001 parameters are used with the OPT3001_open() call. Default values for these parameters are set using OPT3001_Params_init(). The GPIO_CallbackFxn should be defined by the application only if the ALERT functionality is desired. A gpioIndex must be defined in the OPT3001_HWAttrs for the corresponding OPT3001Index. The GPIO_CallbackFxn is in the context of an interrupt handler.
See also
OPT3001_Params_init()
OPT3001_SlaveAddress
typedef enum OPT3001_SlaveAddress OPT3001_SlaveAddress
OPT3001 I2C slave addresses.
The OPT3001 Slave Address is determined by the input to the ADDR pin. In two cases, the ADDR pin may be coupled with the SDA or SCL bus. OPT3001 sensors on the same I2C bus cannot share the same slave address.
Enumeration Type Documentation
OPT3001_ConversionMode
enum OPT3001_ConversionMode
OPT3001 ADC conversion mode.
The conversion mode controls whether the device is operating in continuous conversion, single-shot, or low-power shutdown mode. The hardware default is shutdown mode such that upon power-up, the device does not perform conversions. When single-shot mode is selected, the device performs a conversion and then enters shutdown mode upon completion.
Enumerator
OPT3001_SHUTDOWN
No conversions (hardware default)
OPT3001_SINGLESHOT
One conversion, then shutdown
OPT3001_CONTINUOUS
Continuous conversions
OPT3001_ConversionReady
enum OPT3001_ConversionReady
OPT3001 Conversion Ready Interrupt Mode.
Using OPT3001_CONV_EN generates an interrupt when the conversion ready field indicates a conversion is complete. The conversion ready field is set to 1 at the end of a conversion and cleared when the configuration register is subsequuently read or written with any value except one containing the OPT3001_SHUTDOWN field command. This mode can be used in conjuction with OPT3001_LATCH or OPT3001_NOLATCH.
Enumerator
OPT3001_CONVRD_DIS
OPT3001_CONVRD_EN
OPT3001_ConversionTime
enum OPT3001_ConversionTime
OPT3001 Conversion Time.
The conversion time determines the length of the light to digital conversion process. A longer conversion time allows for a lower noise measurement. The conversion time also relates to the effective resolution of the data conversion process. Using 800ms ensures full resolution of the result register while 100ms may limit the resolution based upon the range.
Enumerator
OPT3001_100MS
100 ms conversion time (0.1 s)
OPT3001_800MS
800 ms conversion time (0.8 s)
OPT3001_FaultCount
enum OPT3001_FaultCount
OPT3001 Fault Count.
The fault count field instructs the device as to how many consecutive fault events are required to trigger the interrupt reporting mechanism: the INT pin, the flag high field, and flag low field. When the fault count is reached, the INT pin is asserted.
Enumerator
OPT3001_FAULT1
One fault count (default)
OPT3001_FAULT2
Two fault counts
OPT3001_FAULT4
Four fault counts
OPT3001_FAULT8
Eight fault counts
OPT3001_FullRange
enum OPT3001_FullRange
OPT3001 Result Register Range.
The range field selects the full-scale lux range of the device. The result register may contain a value up to that specified by the range. Greater range constitutes lower resolution while less range consitutes higher resolution.
Automatic scaling will determine the optimum range based on a 10-ms measurement of current lighting conditions. With every measurement there after, the range is automatically adjusted based on the result (E.g If the result is towards the upper side of the range, the full-scale range is increased. If the result is towards the lower side of the range, the full-scale range is decreased). If the result is outside of the automatically set range, the current result is aborted and a 10-ms measurement is taken to re-assess and properly reset the full-scale range. Therefore, during fast optical transients in automatic mode, a measurement can possibly take 10 ms rather the time set in OPT3001_ConversionTime.
Enumerator
OPT3001_RANGE0
Range = 00040.95, lux per LSB = 00.01
OPT3001_RANGE1
Range = 00081.90, lux per LSB = 00.02
OPT3001_RANGE2
Range = 00163.80, lux per LSB = 00.04
OPT3001_RANGE3
Range = 00327.60, lux per LSB = 00.08
OPT3001_RANGE4
Range = 00665.20, lux per LSB = 00.16
OPT3001_RANGE5
Range = 01310.40, lux per LSB = 00.32
OPT3001_RANGE6
Range = 02620.80, lux per LSB = 00.64
OPT3001_RANGE7
Range = 05241.60, lux per LSB = 01.28
OPT3001_RANGE8
Range = 10483.20, lux per LSB = 02.56
OPT3001_RANGE9
Range = 20966.40, lux per LSB = 05.12
OPT3001_RANGE10
Range = 41932.80, lux per LSB = 10.24
OPT3001_RANGE11
Range = 83865.60, lux per LSB = 20.48
OPT3001_AUTO
Automatic Scaling
OPT3001_InterruptMode
enum OPT3001_InterruptMode
OPT3001 Interrupt Mode.
Interrupt mode controls the behavior of the INT pin.
If no latch (0), the INT pin is asserted whenever the enabled alert conditions are met. The INT pin will de-assert automatically when the condition clears.
In latched mode (1), the INT pin is asserted whenever the appropriate conditions are met. The INT pin will remain asserted until the application performs a clearing event (E.g reading the configuration register).
Enumerator
OPT3001_NOLATCH
Non-Latch Mode
OPT3001_LATCH
Latch Mode
OPT3001_SlaveAddress
enum OPT3001_SlaveAddress
OPT3001 I2C slave addresses.
The OPT3001 Slave Address is determined by the input to the ADDR pin. In two cases, the ADDR pin may be coupled with the SDA or SCL bus. OPT3001 sensors on the same I2C bus cannot share the same slave address.
Enumerator
OPT3001_SA1
ADDR = GND
OPT3001_SA2
ADDR = VDD
OPT3001_SA3
ADDR = SDA
OPT3001_SA4
ADDR = SCL
Function Documentation
OPT3001_close()
bool OPT3001_close (OPT3001_Handle handle)
Function to close a OPT3001 sensor specified by the OPT3001 handle.
The OPT3001 hardware will be placed in a low power state in which ADC conversions are disabled. If the pin is configured to interrupt, the GPIO pin interrupts will be disabled. The I2C handle is not affected.
Precondition
OPT3001_open() had to be called first.
Parameters
handle A OPT3001_Handle returned from OPT3001_open()
Returns
true on success or false upon failure.
References OPT3001_Object::callback, OPT3001_Object::i2cHandle, OPT3001_Config::object, OPT3001_disableInterrupt(), OPT3001_setConversionMode(), OPT3001_setLuxLimits(), OPT3001_SHUTDOWN, and RANGE_MAX.
OPT3001_disableInterrupt()
bool OPT3001_disableInterrupt (OPT3001_Handle handle)
Function to disable the GPIO interrupt.
Interrupts on the OPT3001 specific GPIO index will be disabled. The lux limits set are unaffected.
See also
OPT3001_enableInterrupt()
Precondition
Had to call OPT3001_enableInterrupt() first for this function to have an effect.
Parameters
handle A OPT3001_Handle
Returns
true on success or false upon failure.
References OPT3001_Config::hwAttrs, and OPT3001_Config::object.
Referenced by OPT3001_close().
OPT3001_enableInterrupt()
bool OPT3001_enableInterrupt (OPT3001_Handle handle)
Enable interrupts from the specified OPT3001.
Interrupts on the OPT3001 specific GPIO index will be enabled.
See also
OPT3001_disableInterrupt()
Precondition
OPT3001_setLuxLimits() must have been called first to recieve interrupts from the OPT3001 INT pin.
Parameters
handle A OPT3001_Handle
Returns
true on success or false upon failure.
References OPT3001_Config::hwAttrs, OPT3001_Config::object, OPT3001_CONFIG, and OPT3001_readRegister().
OPT3001_getLux()
bool OPT3001_getLux (OPT3001_Handle handle, float * data)
Function to get the sensor's lux reading.
Parameters
handle A OPT3001_Handle
data A pointer to a float to store the lux value.
Returns
true on success, false on failure
References convertToLux(), OPT3001_readRegister(), and OPT3001_RESULT.
Referenced by coapHandleLuminosity().
OPT3001_getLuxLimits()
bool OPT3001_getLuxLimits (OPT3001_Handle handle, float * high, float * low)
Function to get the sensor's lux limits.
Parameters
handle A OPT3001_Handle
high A pointer to a float to store the high limit
low A pointer to a float to store the low limit
Returns
true on success, false on failure
References convertToLux(), OPT3001_HILIMIT, OPT3001_LOLIMIT, and OPT3001_readRegister().
OPT3001_init()
void OPT3001_init ()
Function to initialize OPT3001 driver.
This function will initialize the OPT3001 driver. This should be called before BIOS_start().
References i2cHandle, and OPT3001_Config::object.
Referenced by initOPT().
OPT3001_open()
OPT3001_Handle OPT3001_open (unsigned int index, I2C_Handle i2cHandle, OPT3001_Params * params)
Function to open a given OPT3001 sensor.
Function to initialize a given OPT3001 sensor specified by the particular index value. This function must be called from a task context. If one intends to use the INT pin, a callback function must be specified in the OPT3001_Params structure. Additionally, a gpioIndex must be setup and specified in the OPT3001_HWAttrs structure.
The I2C controller must be operating in BLOCKING mode. Failure to ensure the I2C_Handle is in BLOCKING mode will result in undefined behavior.
The user should ensure that each sensor has its own slaveAddress, gpioIndex (if alarming) and OPT3001Index.
Precondition
OPT3001_init() has to be called first
Parameters
OPT3001Index Logical sensor number for the OPT3001 indexed into the OPT3001_config table
i2cHandle An I2C_Handle opened in BLOCKING mode
params A pointer to OPT3001_Params structure. If NULL, it will use default values.
Returns
A OPT3001_Handle on success, or a NULL on failure.
See also
OPT3001_init()
OPT3001_Params_init()
OPT3001_close()
References OPT3001_Object::callback, OPT3001_Params::callback, OPT3001_Params::conversionMode, OPT3001_Params::conversionReady, OPT3001_Params::conversionTime, OPT3001_Params::faultCount, OPT3001_HWAttrs::gpioIndex, i2cHandle, OPT3001_Object::i2cHandle, OPT3001_Params::interruptMode, OPT3001_CONFIG, OPT3001_LOLIMIT, OPT3001_writeRegister(), and OPT3001_Params::range.
Referenced by initOPT().
OPT3001_Params_init()
void OPT3001_Params_init (OPT3001_Params * params)
Function to initialize a OPT3001_Params struct to its defaults.
Parameters
params A pointer to OPT3001_Params structure for initialization.
Default values are:
 conversionMode    = OPT3001_CONTINUOUS
 conversionReady   = OPT3001_CONVRD_DIS
 conversionTime    = OPT3001_800MS
 faultCount        = OPT3001_FAULT1
 range             = OPT3001_AUTO
 interruptMode     = OPT3001_LATCH
 callback          = NULL
References OPT3001_defaultParams.
Referenced by initOPT().
OPT3001_readRegister()
bool OPT3001_readRegister (OPT3001_Handle handle, uint16_t * data, uint8_t registerAddress)
Read the specified register from a OPT3001 sensor.
Parameters
handle A OPT3001_Handle
registerAddress Register address
data A pointer to a data register in which received data will be written to. Must be 16 bits.
Returns
true on success or false upon failure.
References OPT3001_Config::hwAttrs, i2cTransferFxn(), OPT3001_Config::object, and READ_BUF_SIZE.
Referenced by OPT3001_enableInterrupt(), OPT3001_getLux(), OPT3001_getLuxLimits(), OPT3001_setConversionMode(), and OPT3001_setRange().
OPT3001_setConversionMode()
bool OPT3001_setConversionMode (OPT3001_Handle handle, OPT3001_ConversionMode mode)
Function to change the conversion mode.
This function will set the OPT3001 hardware to operate in the coversion mode specified by OPT3001_ConversionMode.
Precondition
OPT3001_open has to be called first.
Parameters
handle A OPT3001_Handle
mode A OPT3001_ConversionMode specifying the mode to operate in.
Returns
true on success or false upon failure.
References OPT3001_CONFIG, OPT3001_readRegister(), OPT3001_SINGLESHOT, and OPT3001_writeRegister().
Referenced by OPT3001_close().
OPT3001_setLuxLimits()
bool OPT3001_setLuxLimits (OPT3001_Handle handle, float high, float low)
Function to get the sensor's lux limits.
Parameters
handle A OPT3001_Handle
high A float specifying the high limit. Use OPT3001_IGNORE if a h storingigh limit is not desired.
low A float specifying the low limit. Use OPT3001_IGNORE if a low limit is not desired.
Returns
true on success, false on failure
References LUX_BASE_RES, OPT3001_HILIMIT, OPT3001_IGNORE, OPT3001_LOLIMIT, OPT3001_writeRegister(), RANGE_BASE, and RANGE_MAX.
Referenced by OPT3001_close().
OPT3001_setRange()
bool OPT3001_setRange (OPT3001_Handle handle, OPT3001_FullRange range)
Set the lux measurement result range.
Parameters
handle A OPT3001_Handle
OPT3001_FullRange A range value specifying max possible result
Returns
true on success or false upon failure.
References OPT3001_CONFIG, OPT3001_readRegister(), OPT3001_writeRegister(), and RANGE_BITS.
OPT3001_writeRegister()
bool OPT3001_writeRegister (OPT3001_Handle handle, uint16_t data, uint8_t registerAddress)
Write the specified data to a OPT3001 sensor.
This function is not thread safe. When writing to a handle, it is possible to overwrite data written by another task.
For example: Task A and B are writing to the configuration register. Task A has a higher priority than Task B. Task B is running and reads the configuration register. Task A then preempts Task B and reads the configuration register, performs a logical OR and writes to the configuration register. Task B then resumes execution and performs its logical OR and writes to the configuration register–overwriting the data written by Task A.
Such instances can be prevented through the use of Semaphores. Below is an example which utilizes an initialized Semaphore_handle, OPT3001Lock.
if (Semaphore_pend(OPT3001Lock, BIOS_NO_WAIT)) {
    //Perform read/write operations
}
else {
    Task_sleep(1000);
}
Semaphore_post(OPT3001Lock);
Parameters
handle A OPT3001_Handle
data A uint16_t to be written to the OPT3001 sensor
registerAddress OPT3001 register address
Returns
true on success or false upon failure.
References OPT3001_Config::hwAttrs, i2cTransferFxn(), OPT3001_Config::object, and WRITE_BUF_SIZE.
Referenced by OPT3001_open(), OPT3001_setConversionMode(), OPT3001_setLuxLimits(), and OPT3001_setRange().
© Copyright 1995-2018, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale