TI Thread API Documentation: examples/otsupport/otinstance.h File Reference
otinstance.h File Reference
Functions
otInstance * OtInstance_get (void)
Function Documentation
OtInstance_get()
otInstance* OtInstance_get (void)
Get a pointer to the OpenThread instance object.
Returns
Pointer to the OpenThread instance object.
Documented in otsupport/otinstance.h.
References OtStack_instance.
Referenced by cli_task(), DoorLock_task(), ncp_task(), processEvents(), Shade_task(), TempSensor_task(), tempSensorReport(), and Thermostat_task().
© Copyright 1995-2018, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale