TI Thread API Documentation: examples/otsupport/otrtosapi.c File Reference
otrtosapi.c File Reference
Detailed Description
This file contains the implementation of the stack protective mutex.
Functions
void OtRtosApi_init (void)
void OtRtosApi_lock (void)
void OtRtosApi_unlock (void)
Variables
static pthread_mutex_t OtRtosApi_mutexHandle
Function Documentation
OtRtosApi_init()
void OtRtosApi_init (void)
Initialize the RTOS mutex protecting the OpenThread APIs.
Documented in ot_rtos_api.h.
References OtRtosApi_mutexHandle.
Referenced by OtStack_task().
OtRtosApi_lock()
void OtRtosApi_lock (void)
Lock the OpenThread Stack mutex.
Documented in ot_rtos_api.h.
References OtRtosApi_mutexHandle.
Referenced by cli_task(), DoorLock_task(), ncp_task(), otPlatLog(), OtStack_joinNetwork(), OtStack_setupNetwork(), OtStack_task(), setupCoapServer(), Shade_task(), TempSensor_task(), tempSensorReport(), and Thermostat_task().
OtRtosApi_unlock()
void OtRtosApi_unlock (void)
Unlock the OpenThread Stack mutex.
Documented in ot_rtos_api.h.
References OtRtosApi_mutexHandle.
Referenced by cli_task(), DoorLock_task(), ncp_task(), otPlatLog(), OtStack_joinNetwork(), OtStack_setupNetwork(), OtStack_task(), setupCoapServer(), Shade_task(), TempSensor_task(), tempSensorReport(), and Thermostat_task().
Variable Documentation
OtRtosApi_mutexHandle
pthread_mutex_t OtRtosApi_mutexHandle static
Referenced by OtRtosApi_init(), OtRtosApi_lock(), and OtRtosApi_unlock().
© Copyright 1995-2018, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale