TI Thread API Documentation: examples/platform/platform.h File Reference
platform.h File Reference
Functions
void platformAlarmInit (void)
void platformAlarmMicroInit (void)
void platformAlarmMicroProcess (otInstance *aInstance)
void platformAlarmMicroSignal (void)
void platformAlarmProcess (otInstance *aInstance)
void platformAlarmSignal (void)
void platformDebugUartInit (void)
void PlatformInit (int argc, char *argv[])
void platformRadioInit (void)
void platformRadioProcess (otInstance *aInstance)
void platformRadioSignal (void)
void platformRandomInit (void)
void platformRandomProcess (void)
void platformRandomSignal (void)
void platformUartProcess (void)
void platformUartSignal (void)
Variables
otInstance * sInstance
Function Documentation
platformAlarmInit()
void platformAlarmInit (void)
This method initializes the alarm service used by OpenThread.
Function documented in platform.h
References Alarm_handler(), Alarm_running, and Alarm_timerid.
Referenced by PlatformInit().
platformAlarmMicroInit()
void platformAlarmMicroInit (void)
This method initializes the alarm service used by OpenThread.
Function documented in platform.h
References AlarmMicro_handler(), AlarmMicro_running, and AlarmMicro_timerid.
Referenced by PlatformInit().
platformAlarmMicroProcess()
void platformAlarmMicroProcess (otInstance * aInstance)
This method performs alarm driver processing.
Function documented in platform.h
References AlarmMicro_running, AlarmMicro_time, AlarmMicro_time0, AlarmMicro_timerid, otPlatAlarmMicroGetNow(), and platformAlarmMicroSignal().
Referenced by OtStack_task().
platformAlarmMicroSignal()
void platformAlarmMicroSignal (void)
Signal the processing loop to process the alarm module.
Callback from the alarm module indicating need for processing.
References OT_STACK_EVENT_SIGNAL_ALARMU_PROCESS, and OtStack_events.
Referenced by AlarmMicro_handler(), otPlatAlarmMicroStartAt(), and platformAlarmMicroProcess().
platformAlarmProcess()
void platformAlarmProcess (otInstance * aInstance)
This method performs alarm driver processing.
Function documented in platform.h
References Alarm_running, Alarm_time, Alarm_time0, Alarm_timerid, otPlatAlarmMilliGetNow(), otPlatDiagModeGet(), and platformAlarmSignal().
Referenced by OtStack_task().
platformAlarmSignal()
void platformAlarmSignal (void)
Signal the processing loop to process the alarm module.
Callback from the alarm module indicating need for processing.
References OT_STACK_EVENT_SIGNAL_ALARM_PROCESS, and OtStack_events.
Referenced by Alarm_handler(), otPlatAlarmMilliStartAt(), and platformAlarmProcess().
platformDebugUartInit()
void platformDebugUartInit (void)
Initialize the debug uart
Referenced by PlatformInit().
PlatformInit()
void PlatformInit (int argc, char * argv[])
Initialize the platform support modules.
Function documented in platform.h
References platformAlarmInit(), platformAlarmMicroInit(), platformDebugUartInit(), platformRadioInit(), and platformRandomInit().
Referenced by OtStack_task().
platformRadioInit()
void platformRadioInit (void)
This method initializes the radio service used by OpenThread.
Referenced by PlatformInit().
platformRadioProcess()
void platformRadioProcess (otInstance * aInstance)
This method performs radio driver processing.
Referenced by OtStack_task().
platformRadioSignal()
void platformRadioSignal (void)
Callback from the radio module indicating need for processing.
References OT_STACK_EVENT_SIGNAL_RADIO_PROCESS, and OtStack_events.
platformRandomInit()
void platformRandomInit (void)
This method initializes the random number service used by OpenThread.
Function documented in platform.h
References fillRandomPool(), and RING_BUFFER_SIZE.
Referenced by PlatformInit().
platformRandomProcess()
void platformRandomProcess (void)
This method performs random driver processing.
Function documented in platform.h
References fillRandomPool().
Referenced by OtStack_task().
platformRandomSignal()
void platformRandomSignal (void)
Callback from random module indicating need for processing.
Callback from the random generator module indicating need for processing.
References OT_STACK_EVENT_SIGNAL_RANDOM_PROCESS, and OtStack_events.
Referenced by getRandom().
platformUartProcess()
void platformUartProcess (void)
This method performs radio driver processing.
Function documented in platform.h
References otPlatUartReceived(), otPlatUartSendDone(), PLATFORM_UART_EVENT_RX_DONE, PLATFORM_UART_EVENT_TX_DONE, PlatformUart_events, PlatformUart_receiveBuffer, PlatformUart_receiveLen, and PlatformUart_uartHandle.
Referenced by OtStack_task().
platformUartSignal()
void platformUartSignal (void)
Signal the processing loop to process the uart module.
Callback from the alarm module indicating need for processing.
References OT_STACK_EVENT_SIGNAL_UART_PROCESS, and OtStack_events.
Referenced by uartReadCallback(), and uartWriteCallback().
Variable Documentation
sInstance
otInstance* sInstance
© Copyright 1995-2018, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale