TI Thread API Documentation: examples/platform/radio.h File Reference
radio.h File Reference
Data Structures
struct ext_src_match_data_s
struct short_src_match_data_s
Macros
#define DATA_ENTRY_LENSZ_BYTE 1
#define IEEE802154_A_TURNAROUND_TIME (12)
#define IEEE802154_A_UINT_BACKOFF_PERIOD (20)
#define IEEE802154_ACK_LENGTH (5)
#define IEEE802154_ACK_REQUEST (1<<5)
#define IEEE802154_DSN_OFFSET (2)
#define IEEE802154_FRAME_PENDING (1<<4)
#define IEEE802154_FRAME_TYPE_ACK (0x2)
#define IEEE802154_FRAME_TYPE_MASK (0x7)
#define IEEE802154_MAC_ACK_WAIT_DURATION
#define IEEE802154_MAC_MAX_BE (5)
#define IEEE802154_MAC_MAX_CSMA_BACKOFFS (4)
#define IEEE802154_MAC_MAX_FRAMES_RETRIES (3)
#define IEEE802154_MAC_MIN_BE (3)
#define IEEE802154_PHY_SHR_DURATION (10)
#define IEEE802154_PHY_SYMBOLS_PER_OCTET (2)
#define IEEE802154_SYMBOLS_PER_SEC (62500)
#define PLATFORM_RADIO_EXTADD_SRC_MATCH_NUM 10
#define PLATFORM_RADIO_INVALID_RSSI (127)
#define PLATFORM_RADIO_RAT_TICKS_PER_SEC (4000000)
#define PLATFORM_RADIO_SHORTADD_SRC_MATCH_NUM 10
#define PLATFORM_RADIO_SRC_MATCH_NONE 0xFF
#define RF_DRIVER_ABORT 0
#define RF_EVENT_ED_SCAN_DONE Event_Id_01
#define RF_EVENT_RX_ACK_DONE Event_Id_03
#define RF_EVENT_RX_DONE Event_Id_02
#define RF_EVENT_SLEEP_YIELD Event_Id_04
#define RF_EVENT_TX_DONE Event_Id_00
#define RX_BUF_SIZE 144
Typedefs
typedef struct __RFC_STRUCT ext_src_match_data_s ext_src_match_data_t
typedef enum platformRadio_address platformRadio_address
typedef enum platformRadio_phyState platformRadio_phyState
typedef struct __RFC_STRUCT short_src_match_data_s short_src_match_data_t
Enumerations
enum platformRadio_address { platformRadio_address_short = 0, platformRadio_address_ext = 1 }
enum platformRadio_phyState {
platformRadio_phyState_Disabled = 0, platformRadio_phyState_Sleep, platformRadio_phyState_Receive, platformRadio_phyState_EdScan,
platformRadio_phyState_Transmit
}
Functions
otError otPlatDiagRadioToneStart (otInstance *aInstance, bool aModulated)
otError otPlatDiagRadioToneStop (otInstance *aInstance)
void rfCoreDiagChannelDisable (uint8_t aChannel)
void rfCoreDiagChannelEnable (uint8_t aChannel)
Variables
struct __RFC_STRUCT ext_src_match_data_s __RFC_STRUCT_ATTR
Macro Definition Documentation
DATA_ENTRY_LENSZ_BYTE
#define DATA_ENTRY_LENSZ_BYTE 1
size of length field in receive struct.
defined in Table 23-10 of the cc13xx and cc26xx TRM.
IEEE802154_A_TURNAROUND_TIME
#define IEEE802154_A_TURNAROUND_TIME (12)
(IEEE 802.15.4-2006 6.4.1) PHY constants.
IEEE802154_A_UINT_BACKOFF_PERIOD
#define IEEE802154_A_UINT_BACKOFF_PERIOD (20)
(IEEE 802.15.4-2006 7.4.1) MAC constants.
IEEE802154_ACK_LENGTH
#define IEEE802154_ACK_LENGTH (5)
(IEEE 802.15.4-2006) Length of an ack frame.
IEEE802154_ACK_REQUEST
#define IEEE802154_ACK_REQUEST (1<<5)
(IEEE 802.15.4-2006) PSDU.FCF.bAR.
IEEE802154_DSN_OFFSET
#define IEEE802154_DSN_OFFSET (2)
(IEEE 802.15.4-2006) PSDU.sequenceNumber.
IEEE802154_FRAME_PENDING
#define IEEE802154_FRAME_PENDING (1<<4)
(IEEE 802.15.4-2006) PSDU.FCF.bFramePending.
IEEE802154_FRAME_TYPE_ACK
#define IEEE802154_FRAME_TYPE_ACK (0x2)
(IEEE 802.15.4-2006) frame type: ACK.
IEEE802154_FRAME_TYPE_MASK
#define IEEE802154_FRAME_TYPE_MASK (0x7)
(IEEE 802.15.4-2006) PSDU.FCF.frameType.
IEEE802154_MAC_ACK_WAIT_DURATION
#define IEEE802154_MAC_ACK_WAIT_DURATION
Value:
(IEEE802154_A_UINT_BACKOFF_PERIOD + IEEE802154_A_TURNAROUND_TIME       \
         + IEEE802154_PHY_SHR_DURATION                                         \
         + ( 6 * IEEE802154_PHY_SYMBOLS_PER_OCTET))
(IEEE 802.15.4-2006 7.4.2) macAckWaitDuration PIB attribute.
IEEE802154_MAC_MAX_BE
#define IEEE802154_MAC_MAX_BE (5)
(IEEE 802.15.4-2006) macMaxBE.
IEEE802154_MAC_MAX_CSMA_BACKOFFS
#define IEEE802154_MAC_MAX_CSMA_BACKOFFS (4)
(IEEE 802.15.4-2006) macMaxCSMABackoffs.
IEEE802154_MAC_MAX_FRAMES_RETRIES
#define IEEE802154_MAC_MAX_FRAMES_RETRIES (3)
(IEEE 802.15.4-2006) macMaxFrameRetries.
IEEE802154_MAC_MIN_BE
#define IEEE802154_MAC_MIN_BE (3)
(IEEE 802.15.4-2006) macMinBE.
IEEE802154_PHY_SHR_DURATION
#define IEEE802154_PHY_SHR_DURATION (10)
(IEEE 802.15.4-2006 6.4.2) PHY PIB attribute, specifically the O-QPSK PHY.
IEEE802154_PHY_SYMBOLS_PER_OCTET
#define IEEE802154_PHY_SYMBOLS_PER_OCTET (2)
(IEEE 802.15.4-2006 6.4.2) PHY PIB attribute, specifically the O-QPSK PHY.
IEEE802154_SYMBOLS_PER_SEC
#define IEEE802154_SYMBOLS_PER_SEC (62500)
(IEEE 802.15.4-2006 6.5.3.2) O-QPSK symbol rate.
PLATFORM_RADIO_EXTADD_SRC_MATCH_NUM
#define PLATFORM_RADIO_EXTADD_SRC_MATCH_NUM 10
Number of extended addresses in sSrcMatchExtData.
PLATFORM_RADIO_INVALID_RSSI
#define PLATFORM_RADIO_INVALID_RSSI (127)
Invalid RSSI value returned from an ED scan.
PLATFORM_RADIO_RAT_TICKS_PER_SEC
#define PLATFORM_RADIO_RAT_TICKS_PER_SEC (4000000)
Frequency of the Radio Timer module.
4MHz clock.
PLATFORM_RADIO_SHORTADD_SRC_MATCH_NUM
#define PLATFORM_RADIO_SHORTADD_SRC_MATCH_NUM 10
Number of short addresses in sSrcMatchShortData.
PLATFORM_RADIO_SRC_MATCH_NONE
#define PLATFORM_RADIO_SRC_MATCH_NONE 0xFF
Return value used when searching the source match array.
Returned if an address could not be found or if an empty element could not be found.
RF_DRIVER_ABORT
#define RF_DRIVER_ABORT 0
Value to pass to RF_cancelCmd to signify aborting the command.
documented in source/ti/drivers/rf/RF.h
RF_EVENT_ED_SCAN_DONE
#define RF_EVENT_ED_SCAN_DONE Event_Id_01
RF_EVENT_RX_ACK_DONE
#define RF_EVENT_RX_ACK_DONE Event_Id_03
RF_EVENT_RX_DONE
#define RF_EVENT_RX_DONE Event_Id_02
RF_EVENT_SLEEP_YIELD
#define RF_EVENT_SLEEP_YIELD Event_Id_04
RF_EVENT_TX_DONE
#define RF_EVENT_TX_DONE Event_Id_00
Event flags marked in rfEvents.
RX_BUF_SIZE
#define RX_BUF_SIZE 144
Size of the receive buffers in the receive queue.
Typedef Documentation
ext_src_match_data_t
typedef struct __RFC_STRUCT ext_src_match_data_s ext_src_match_data_t
Structure for source matching extended addresses.
Defined in Table 23-73 of the cc13xx and cc26xx TRM.
platformRadio_address
typedef enum platformRadio_address platformRadio_address
Address type for rfCoreModifySourceMatchEntry().
platformRadio_phyState
typedef enum platformRadio_phyState platformRadio_phyState
This enum represents the state of a radio.
Initially, a radio is in the Disabled state.
The following are valid radio state transitions for the platform
+----------+  Enable()  +-------+  Receive()   +---------+   Transmit()  +----------+
|          |----------->|       |------------->|         |-------------->|          |
| Disabled |            | Sleep |              | Receive |               | Transmit |
|          |<-----------|       |<-------------|         |<--------------|          |
+----------+  Disable() |       |   Sleep()    +---------+ Receive() or  +----------+
  ^                     |       |                          Transmit complete
  |                     |       | EnergyScan()  +--------+
  |                     |       |-------------->|        |
Init()                  |       |               | EdScan |
                        |       |<--------------|        |
                        +-------+ scan complete +--------+
These states slightly differ from the states in include/platform/radio.h. The additional states the phy can be in are due to the asynchronous nature of the CM0 radio core.
state description
Disabled The rfcore powerdomain is off and the RFCPE is off
Sleep The RFCORE PD is on, and the RFCPE is in IEEE mode
Receive The RFCPE is running a CMD_IEEE_RX
EdScan The RFCPE is running a CMD_IEEE_ED_SCAN
Transmit The RFCPE is running a transmit command string
short_src_match_data_t
typedef struct __RFC_STRUCT short_src_match_data_s short_src_match_data_t
Structure for source matching short addresses.
Defined in Table 23-74 of the cc13xx and cc26xx TRM.
Enumeration Type Documentation
platformRadio_address
enum platformRadio_address
Address type for rfCoreModifySourceMatchEntry().
Enumerator
platformRadio_address_short
platformRadio_address_ext
platformRadio_phyState
enum platformRadio_phyState
This enum represents the state of a radio.
Initially, a radio is in the Disabled state.
The following are valid radio state transitions for the platform
+----------+  Enable()  +-------+  Receive()   +---------+   Transmit()  +----------+
|          |----------->|       |------------->|         |-------------->|          |
| Disabled |            | Sleep |              | Receive |               | Transmit |
|          |<-----------|       |<-------------|         |<--------------|          |
+----------+  Disable() |       |   Sleep()    +---------+ Receive() or  +----------+
  ^                     |       |                          Transmit complete
  |                     |       | EnergyScan()  +--------+
  |                     |       |-------------->|        |
Init()                  |       |               | EdScan |
                        |       |<--------------|        |
                        +-------+ scan complete +--------+
These states slightly differ from the states in include/platform/radio.h. The additional states the phy can be in are due to the asynchronous nature of the CM0 radio core.
state description
Disabled The rfcore powerdomain is off and the RFCPE is off
Sleep The RFCORE PD is on, and the RFCPE is in IEEE mode
Receive The RFCPE is running a CMD_IEEE_RX
EdScan The RFCPE is running a CMD_IEEE_ED_SCAN
Transmit The RFCPE is running a transmit command string
Enumerator
platformRadio_phyState_Disabled
platformRadio_phyState_Sleep
platformRadio_phyState_Receive
platformRadio_phyState_EdScan
platformRadio_phyState_Transmit
Function Documentation
otPlatDiagRadioToneStart()
otError otPlatDiagRadioToneStart (otInstance * aInstance, bool aModulated)
The diagnostic module calls this function to begin transmitting a continuous tone. The tone will be transmitted on the current receive channel.
Parameters
[in] aInstance The OpenThread instance structure.
[in] aModulated Indicates whether or not the tone was modulated or not.
Return values
OT_ERROR_NONE Successfully started sending the RF tone.
OT_ERROR_NOT_IMPLEMENTED The radio doesn't support sending a test tone.
Referenced by PlatDiag_processTone().
otPlatDiagRadioToneStop()
otError otPlatDiagRadioToneStop (otInstance * aInstance)
The diagnostic module calls this to stop transmitting a continuous tone.
Parameters
[in] aInstance The OpenThread instance structure.
Return values
OT_ERROR_NONE Successfully stopped sending the RF tone.
OT_ERROR_NOT_IMPLEMENTED The radio doesn't support sending a test tone.
Referenced by PlatDiag_processTone().
rfCoreDiagChannelDisable()
void rfCoreDiagChannelDisable (uint8_t aChannel)
The diagnostic module calls this to set the channel and disable channel switching.
This function was added to support automated Thread Test Harness execution. It is intended to simulate the device being placed within a shield box by switching the radio to an unused channel and disallowing the stack switching back to the set channel.
Parameters
[in] aChannel The new (empty) channel.
Referenced by PlatDiag_processShield().
rfCoreDiagChannelEnable()
void rfCoreDiagChannelEnable (uint8_t aChannel)
The diagnostic module calls this to reset the channel and re-enable channel switching.
See also
rfCoreDiagChannelDisable
Parameters
[in] aChannel The original channel.
Referenced by PlatDiag_processShield().
Variable Documentation
__RFC_STRUCT_ATTR
struct __RFC_STRUCT short_src_match_data_s __RFC_STRUCT_ATTR
© Copyright 1995-2018, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale