TI Thread API Documentation: examples/platform/random.c File Reference
random.c File Reference
Macros
#define RING_BUFFER_SIZE 32
Enumerations
enum { PLATFORM_TRNG_MIN_SAMPLES_PER_CYCLE = (1 << 8), PLATFORM_TRNG_MAX_SAMPLES_PER_CYCLE = (1 << 8), PLATFORM_TRNG_CLOCKS_PER_SAMPLE = 1 }
Functions
static uint32_t fillRandomPool (void)
static int getRandom (unsigned char *aOutput, size_t aLen, size_t *oLen)
static void initTRNG (void)
uint32_t otPlatRandomGet (void)
otError otPlatRandomGetTrue (uint8_t *aOutput, uint16_t aOutputLength)
otError otPlatRandomSecureGet (uint16_t aInputLength, uint8_t *aOutput, uint16_t *aOutputLength)
void platformRandomInit (void)
void platformRandomProcess (void)
static int TRNGPoll (unsigned char *aOutput, size_t aLen, size_t *oLen)
Variables
static unsigned char ringBuf [RING_BUFFER_SIZE]
static RingBuf_Object ringBufObject
Macro Definition Documentation
RING_BUFFER_SIZE
#define RING_BUFFER_SIZE 32
Size of the buffer allocation for the ring buffer.
Please note Larger buffer pool size will impact the start up time.
Referenced by fillRandomPool(), and platformRandomInit().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PLATFORM_TRNG_MIN_SAMPLES_PER_CYCLE
PLATFORM_TRNG_MAX_SAMPLES_PER_CYCLE
PLATFORM_TRNG_CLOCKS_PER_SAMPLE
Function Documentation
fillRandomPool()
static uint32_t fillRandomPool (void) static
References initTRNG(), and RING_BUFFER_SIZE.
Referenced by platformRandomInit(), and platformRandomProcess().
getRandom()
static int getRandom (unsigned char * aOutput, size_t aLen, size_t * oLen) static
References initTRNG(), platformRandomSignal(), and TRNGPoll().
Referenced by otPlatRandomGet(), otPlatRandomGetTrue(), and otPlatRandomSecureGet().
initTRNG()
static void initTRNG (void) static
References PLATFORM_TRNG_CLOCKS_PER_SAMPLE, PLATFORM_TRNG_MAX_SAMPLES_PER_CYCLE, and PLATFORM_TRNG_MIN_SAMPLES_PER_CYCLE.
Referenced by fillRandomPool(), and getRandom().
otPlatRandomGet()
uint32_t otPlatRandomGet (void)
Function documented in platform/random.h
References getRandom().
otPlatRandomGetTrue()
otError otPlatRandomGetTrue (uint8_t * aOutput, uint16_t aOutputLength)
Function documented in platform/random.h
References getRandom().
otPlatRandomSecureGet()
otError otPlatRandomSecureGet (uint16_t aInputLength, uint8_t * aOutput, uint16_t * aOutputLength)
Function documented in platform/random.h
References getRandom().
platformRandomInit()
void platformRandomInit (void)
Function documented in platform.h
References fillRandomPool(), and RING_BUFFER_SIZE.
Referenced by PlatformInit().
platformRandomProcess()
void platformRandomProcess (void)
Function documented in platform.h
References fillRandomPool().
Referenced by OtStack_task().
TRNGPoll()
static int TRNGPoll (unsigned char * aOutput, size_t aLen, size_t * oLen) static
Fill an arbitrary area with random data
Parameters
[out] aOutput area to place the random data
[in] aLen size of the area to place random data
[out] oLen how much of the output was written to
Returns
indication of error
Return values
0 no error occured
Referenced by getRandom().
Variable Documentation
ringBuf
unsigned char ringBuf[RING_BUFFER_SIZE] static
ringBufObject
RingBuf_Object ringBufObject static
© Copyright 1995-2018, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale