TI Thread API Documentation: examples/sensors/otstack.c File Reference
otstack.c File Reference
Functions
static otError createIid (otInstance *aInstance, otNetifAddress *aAddress, void *aContext)
Creates the interface identifier.
void handleNetifStateChanged (uint32_t aFlags, void *aContext)
Callback function registered with the netif.
otInstance * OtInstance_get (void)
void otSetupNetwork (otInstance *aInstance)
Initialize and start the Thread operation.
void * OtStack_task (void *arg0)
void OtStack_taskCreate (void)
void otTaskletsSignalPending (otInstance *aInstance)
static void resetPriority (void)
Variables
static otNetifAddress addresses [OT_MAX_ADDRESSES]
static otInstance * OtStack_instance
static char OtStack_stack [TASK_CONFIG_OT_TASK_STACK_SIZE]
Function Documentation
createIid()
static otError createIid (otInstance * aInstance, otNetifAddress * aAddress, void * aContext) static
Creates the interface identifier.
Parameters
aInstance A pointer to the context information.
aAddress A pointer to structure containing IPv6 address for which IID is being created.
aContext A pointer to creator-specific context.
Returns
OT_ERROR_NONE
References OT_IID_ADDRESS_LSB.
Referenced by handleNetifStateChanged().
handleNetifStateChanged()
void handleNetifStateChanged (uint32_t aFlags, void * aContext)
Callback function registered with the netif.
Parameters
aFlags A bit-field indicating specific state that has changed.
aContext A pointer to application-specific context.
Returns
None
References addresses, and createIid().
Referenced by otSetupNetwork(), OtStack_setupNetwork(), and OtStack_task().
OtInstance_get()
otInstance* OtInstance_get (void)
Documented in otsupport/otinstance.h.
References OtStack_instance.
otSetupNetwork()
void otSetupNetwork (otInstance * aInstance)
Initialize and start the Thread operation.
Parameters
aInstance open thread instance.
Returns
None
References extPanId, handleNetifStateChanged(), OT_NWK_CHANNEL, and OT_NWK_PAN_ID.
Referenced by OtStack_task().
OtStack_task()
void* OtStack_task (void * arg0)
Main processing thread for OpenThread Stack.
References OtRtosApi_init(), OtRtosApi_lock(), OtRtosApi_unlock(), otSetupNetwork(), OtStack_instance, PlatformInit(), resetPriority(), sensors_evtNwkSetup, and Sensors_postEvt().
OtStack_taskCreate()
void OtStack_taskCreate (void)
Documented in task_config.h.
References OtStack_stack, OtStack_task(), and TASK_CONFIG_OT_TASK_STACK_SIZE.
otTaskletsSignalPending()
void otTaskletsSignalPending (otInstance * aInstance)
Callback from OpenThread stack to indicate tasklets are pending processing.
resetPriority()
static void resetPriority (void) static
Return thread priority after initialization.
References TASK_CONFIG_OT_TASK_PRIORITY.
Referenced by OtStack_task().
Variable Documentation
addresses
otNetifAddress addresses[OT_MAX_ADDRESSES] static
Referenced by handleNetifStateChanged().
OtStack_instance
otInstance* OtStack_instance static
Referenced by OtInstance_get(), and OtStack_task().
OtStack_stack
char OtStack_stack[TASK_CONFIG_OT_TASK_STACK_SIZE] static
Referenced by OtStack_taskCreate().
© Copyright 1995-2018, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale