TI Thread API Documentation: examples/sensors/sensors.c File Reference
sensors.c File Reference
Data Structures
struct attrDesc_t
CoAP attribute descriptor.
Macros
#define AMB_TEMP_NUM 2
#define ATTR_COUNT 5
#define ATTR_READ 0x01
#define ATTR_WRITE 0x02
#define DATA_STRING_LENGTH 8
#define HUMIDITY_NUM 0
#define IR_TEMP_NUM 3
#define LUMINOSITY_NUM 4
#define PRESSURE_NUM 1
#define SENSOR_TASK_STACK_SIZE 2048
#define SENSORS_SAMPLE_TIME 500
Functions
int32_t bme280_data_readout_template (I2C_Handle i2cHndl)
static void coapHandleAmbTemp (void *aContext, otCoapHeader *aHeader, otMessage *aMessage, const otMessageInfo *aMessageInfo)
Wrapper on callback function registered with the Coap server. Locks and sends BME ambient temperature data.
static void coapHandleHumidity (void *aContext, otCoapHeader *aHeader, otMessage *aMessage, const otMessageInfo *aMessageInfo)
Wrapper on callback function registered with the Coap server. Locks and sends BME humidity data.
static void coapHandleIrTemp (void *aContext, otCoapHeader *aHeader, otMessage *aMessage, const otMessageInfo *aMessageInfo)
Wrapper on callback function registered with the Coap server. Locks and sends TMP IR temperature data.
static void coapHandleLuminosity (void *aContext, otCoapHeader *aHeader, otMessage *aMessage, const otMessageInfo *aMessageInfo)
Wrapper on callback function registered with the Coap server. Locks and sends OPT luminosity data.
static void coapHandlePressure (void *aContext, otCoapHeader *aHeader, otMessage *aMessage, const otMessageInfo *aMessageInfo)
Wrapper on callback function registered with the Coap server. Locks and sends BMD pressure data.
static void coapHandleServer (void *aContext, otCoapHeader *aHeader, otMessage *aMessage, const otMessageInfo *aMessageInfo, char *sensorValue)
Callback function registered with the Coap server. Processes the coap request from the clients.
static void display_if (char *message)
Wrapper for Display_print0.
static void initBME (I2C_Handle i2cHandle)
Inits BME280 Sensor.
static void initDisplay (void)
Inits the UART Display.
static void initEvent (void)
Initialize and construct the TIRTOS events.
static void initOPT (I2C_Handle i2cHandle)
Inits OPT3001 Sensor.
static void initTMP (I2C_Handle i2cHandle)
Inits TMP007 Sensor.
void otPlatLog (otLogLevel aLogLevel, otLogRegion aLogRegion, const char *aFormat,...)
void otPlatUartReceived (const uint8_t *aBuf, uint16_t aBufLength)
void otPlatUartSendDone (void)
static void processEvents (void)
Processes the events.
static void resetPriority (void)
Return thread priority after initialization.
void Sensors_postEvt (sensors_evt event)
Posts an event to the sensors task.
void * Sensors_task (void *arg0)
void Sensors_taskCreate (void)
static otError setupCoapServer (otInstance *aInstance, const attrDesc_t *attr)
sets up the application coap server.
static bool taskInit (void)
Inits I2C, UART, sensors.
Variables
static attrDesc_t coapAttrs [ATTR_COUNT]
static otCoapResource coapResourceAmbTemp
static otCoapResource coapResourceHumidity
static otCoapResource coapResourceIrTemp
static otCoapResource coapResourceLuminosity
static otCoapResource coapResourcePressure
static Display_Handle display = NULL
static OPT3001_Handle opt3001Handle = NULL
static char sensorsAmbTemp [DATA_STRING_LENGTH] = "22"
static Event_Struct sensorsEvents
static char sensorsHumidity [DATA_STRING_LENGTH] = "54"
static char sensorsIrTemp [DATA_STRING_LENGTH] = "22"
static char sensorsLuminosity [DATA_STRING_LENGTH] = "300"
static char sensorsPressure [DATA_STRING_LENGTH] = "100"
static char stack [TASK_CONFIG_SENSORS_TASK_STACK_SIZE]
static TMP007_Handle tmp007Handle = NULL
Macro Definition Documentation
AMB_TEMP_NUM
#define AMB_TEMP_NUM 2
Referenced by processEvents().
ATTR_COUNT
#define ATTR_COUNT 5
Referenced by processEvents().
ATTR_READ
#define ATTR_READ 0x01
Referenced by setupCoapServer().
ATTR_WRITE
#define ATTR_WRITE 0x02
Referenced by setupCoapServer().
DATA_STRING_LENGTH
#define DATA_STRING_LENGTH 8
Referenced by coapHandleAmbTemp(), coapHandleHumidity(), coapHandleIrTemp(), coapHandleLuminosity(), and coapHandlePressure().
HUMIDITY_NUM
#define HUMIDITY_NUM 0
Referenced by processEvents().
IR_TEMP_NUM
#define IR_TEMP_NUM 3
Referenced by processEvents().
LUMINOSITY_NUM
#define LUMINOSITY_NUM 4
Referenced by processEvents().
PRESSURE_NUM
#define PRESSURE_NUM 1
Referenced by processEvents().
SENSOR_TASK_STACK_SIZE
#define SENSOR_TASK_STACK_SIZE 2048
SENSORS_SAMPLE_TIME
#define SENSORS_SAMPLE_TIME 500
Function Documentation
bme280_data_readout_template()
int32_t bme280_data_readout_template (I2C_Handle i2cHndl)
References bme280, bme280_compensate_humidity_int32(), bme280_compensate_pressure_int32(), bme280_compensate_temperature_int32(), bme280_get_standby_durn(), bme280_init(), BME280_INIT_VALUE, BME280_NORMAL_MODE, BME280_OVERSAMP_1X, BME280_OVERSAMP_2X, BME280_OVERSAMP_4X, bme280_read_pressure_temperature_humidity(), bme280_read_uncomp_humidity(), bme280_read_uncomp_pressure(), bme280_read_uncomp_pressure_temperature_humidity(), bme280_read_uncomp_temperature(), bme280_set_oversamp_humidity(), bme280_set_oversamp_pressure(), bme280_set_oversamp_temperature(), bme280_set_power_mode(), bme280_set_standby_durn(), BME280_SLEEP_MODE, BME280_STANDBY_TIME_1_MS, ERROR, I2C_routine(), and i2cHandle.
Referenced by initBME().
coapHandleAmbTemp()
static void coapHandleAmbTemp (void * aContext, otCoapHeader * aHeader, otMessage * aMessage, const otMessageInfo * aMessageInfo) static
Wrapper on callback function registered with the Coap server. Locks and sends BME ambient temperature data.
Parameters
aContext A pointer to the context information.
aHeader A pointer to the CoAP header.
aMessage A pointer to the message.
aMessageInfo A pointer to the message info.
Returns
None
References bme280_read_pressure_temperature_humidity(), coapHandleServer(), DATA_STRING_LENGTH, and sensorsAmbTemp.
Referenced by processEvents().
coapHandleHumidity()
static void coapHandleHumidity (void * aContext, otCoapHeader * aHeader, otMessage * aMessage, const otMessageInfo * aMessageInfo) static
Wrapper on callback function registered with the Coap server. Locks and sends BME humidity data.
Parameters
aContext A pointer to the context information.
aHeader A pointer to the CoAP header.
aMessage A pointer to the message.
aMessageInfo A pointer to the message info.
Returns
None
References bme280_read_pressure_temperature_humidity(), coapHandleServer(), DATA_STRING_LENGTH, and sensorsHumidity.
Referenced by processEvents().
coapHandleIrTemp()
static void coapHandleIrTemp (void * aContext, otCoapHeader * aHeader, otMessage * aMessage, const otMessageInfo * aMessageInfo) static
Wrapper on callback function registered with the Coap server. Locks and sends TMP IR temperature data.
Parameters
aContext A pointer to the context information.
aHeader A pointer to the CoAP header.
aMessage A pointer to the message.
aMessageInfo A pointer to the message info.
Returns
None
References coapHandleServer(), DATA_STRING_LENGTH, sensorsIrTemp, TMP007_CELSIUS, and TMP007_getObjTemp().
Referenced by processEvents().
coapHandleLuminosity()
static void coapHandleLuminosity (void * aContext, otCoapHeader * aHeader, otMessage * aMessage, const otMessageInfo * aMessageInfo) static
Wrapper on callback function registered with the Coap server. Locks and sends OPT luminosity data.
Parameters
aContext A pointer to the context information.
aHeader A pointer to the CoAP header.
aMessage A pointer to the message.
aMessageInfo A pointer to the message info.
Returns
None
References coapHandleServer(), DATA_STRING_LENGTH, OPT3001_getLux(), and sensorsLuminosity.
Referenced by processEvents().
coapHandlePressure()
static void coapHandlePressure (void * aContext, otCoapHeader * aHeader, otMessage * aMessage, const otMessageInfo * aMessageInfo) static
Wrapper on callback function registered with the Coap server. Locks and sends BMD pressure data.
Parameters
aContext A pointer to the context information.
aHeader A pointer to the CoAP header.
aMessage A pointer to the message.
aMessageInfo A pointer to the message info.
Returns
None
References bme280_read_pressure_temperature_humidity(), coapHandleServer(), DATA_STRING_LENGTH, and sensorsPressure.
Referenced by processEvents().
coapHandleServer()
static void coapHandleServer (void * aContext, otCoapHeader * aHeader, otMessage * aMessage, const otMessageInfo * aMessageInfo, char * sensorValue) static
Callback function registered with the Coap server. Processes the coap request from the clients.
Parameters
aContext A pointer to the context information.
aHeader A pointer to the CoAP header.
aMessage A pointer to the message.
aMessageInfo A pointer to the message info.
Returns
None
Referenced by coapHandleAmbTemp(), coapHandleHumidity(), coapHandleIrTemp(), coapHandleLuminosity(), and coapHandlePressure().
display_if()
static void display_if (char * message) static
Wrapper for Display_print0.
Returns
None
References display.
Referenced by processEvents(), Sensors_task(), and taskInit().
initBME()
static void initBME (I2C_Handle i2cHandle) static
Inits BME280 Sensor.
Parameters
i2cHandle Handle to I2C
Returns
None
References bme280_data_readout_template(), BME280_NORMAL_MODE, and bme280_set_power_mode().
Referenced by taskInit().
initDisplay()
static void initDisplay (void) static
Inits the UART Display.
Returns
None
References display.
Referenced by Sensors_task().
initEvent()
static void initEvent (void) static
Initialize and construct the TIRTOS events.
Returns
None
References sensorsEvents.
Referenced by Sensors_task().
initOPT()
static void initOPT (I2C_Handle i2cHandle) static
Inits OPT3001 Sensor.
Parameters
i2cHandle Handle to I2C
Returns
None
References OPT3001_init(), OPT3001_open(), and OPT3001_Params_init().
Referenced by taskInit().
initTMP()
static void initTMP (I2C_Handle i2cHandle) static
Inits TMP007 Sensor.
Parameters
i2cHandle Handle to I2C
Returns
None
References TMP007_Params::conversions, TMP007_4CONV, TMP007_init(), TMP007_open(), and TMP007_Params_init().
Referenced by taskInit().
otPlatLog()
void otPlatLog (otLogLevel aLogLevel, otLogRegion aLogRegion, const char * aFormat, ...)
Documented in openthread/platform/logging.h.
otPlatUartReceived()
void otPlatUartReceived (const uint8_t * aBuf, uint16_t aBufLength)
Documented in openthread/platform/uart.h.
Referenced by platformUartProcess().
otPlatUartSendDone()
void otPlatUartSendDone (void)
Documented in openthread/platform/uart.h.
Referenced by platformUartProcess().
processEvents()
static void processEvents (void) static
Processes the events.
Returns
None
References AMB_TEMP_NUM, ATTR_COUNT, coapHandleAmbTemp(), coapHandleHumidity(), coapHandleIrTemp(), coapHandleLuminosity(), coapHandlePressure(), display_if(), HUMIDITY_NUM, IR_TEMP_NUM, LUMINOSITY_NUM, OtInstance_get(), attrDesc_t::pAttrHandlerCB, PRESSURE_NUM, sensors_evtNwkSetup, sensorsEvents, and setupCoapServer().
Referenced by Sensors_task().
resetPriority()
static void resetPriority (void) static
Return thread priority after initialization.
Returns
None
References TASK_CONFIG_SENSORS_TASK_PRIORITY.
Referenced by Sensors_task().
Sensors_postEvt()
void Sensors_postEvt (sensors_evt event)
Posts an event to the sensors task.
Parameters
event event to post.
Returns
None
References sensorsEvents.
Referenced by OtStack_task().
Sensors_task()
void * Sensors_task (void * arg0)
Sensors processing thread.
References display_if(), initDisplay(), initEvent(), processEvents(), resetPriority(), and taskInit().
Referenced by Sensors_taskCreate().
Sensors_taskCreate()
void Sensors_taskCreate (void)
Documented in task_config.h.
References Sensors_task(), stack, and TASK_CONFIG_SENSORS_TASK_STACK_SIZE.
Referenced by main().
setupCoapServer()
static otError setupCoapServer (otInstance * aInstance, const attrDesc_t * attr) static
sets up the application coap server.
Parameters
aInstance A pointer to the context information.
attr Attribute data
Returns
OT_ERROR_NONE if successful, else error code
References ATTR_READ, ATTR_WRITE, OtRtosApi_lock(), OtRtosApi_unlock(), attrDesc_t::pAttrCoapResource, attrDesc_t::pAttrHandlerCB, attrDesc_t::type, and attrDesc_t::uriPath.
Referenced by processEvents().
taskInit()
static bool taskInit (void) static
Inits I2C, UART, sensors.
Returns
None
References display_if(), i2cHandle, initBME(), initOPT(), and initTMP().
Referenced by Sensors_task().
Variable Documentation
coapAttrs
attrDesc_t coapAttrs[ATTR_COUNT] static
coapResourceAmbTemp
otCoapResource coapResourceAmbTemp static
coapResourceHumidity
otCoapResource coapResourceHumidity static
coapResourceIrTemp
otCoapResource coapResourceIrTemp static
coapResourceLuminosity
otCoapResource coapResourceLuminosity static
coapResourcePressure
otCoapResource coapResourcePressure static
display
Display_Handle display = NULL static
Referenced by display_if(), and initDisplay().
opt3001Handle
OPT3001_Handle opt3001Handle = NULL static
sensorsAmbTemp
char sensorsAmbTemp[DATA_STRING_LENGTH] = "22" static
Referenced by coapHandleAmbTemp().
sensorsEvents
Event_Struct sensorsEvents static
Referenced by initEvent(), processEvents(), and Sensors_postEvt().
sensorsHumidity
char sensorsHumidity[DATA_STRING_LENGTH] = "54" static
Referenced by coapHandleHumidity().
sensorsIrTemp
char sensorsIrTemp[DATA_STRING_LENGTH] = "22" static
Referenced by coapHandleIrTemp().
sensorsLuminosity
char sensorsLuminosity[DATA_STRING_LENGTH] = "300" static
Referenced by coapHandleLuminosity().
sensorsPressure
char sensorsPressure[DATA_STRING_LENGTH] = "100" static
Referenced by coapHandlePressure().
stack
char stack[TASK_CONFIG_SENSORS_TASK_STACK_SIZE] static
Referenced by Sensors_taskCreate().
tmp007Handle
TMP007_Handle tmp007Handle = NULL static
© Copyright 1995-2018, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale