TI Thread API Documentation: examples/shade/shade.h File Reference
shade.h File Reference
Macros
#define SHADE_STATE_CLOSED "closed"
#define SHADE_STATE_DRAWN "drawn"
#define SHADE_STATE_OPEN "open"
#define SHADE_STATE_URI "blinds/state"
#define SHADE_URI "blinds/"
Enumerations
enum Shade_evt_t {
Shade_evtOpen = Event_Id_00, Shade_evtClosed = Event_Id_01, Shade_evtDrawn = Event_Id_02, Shade_evtNwkSetup = Event_Id_03,
Shade_evtKeyLeft = Event_Id_04, Shade_evtKeyRight = Event_Id_05, Shade_evtNwkJoined = Event_Id_06, Shade_evtNwkJoinFailure = Event_Id_07
}
Functions
void Shade_postEvt (Shade_evt_t event)
Posts an event to the Shade task.
Macro Definition Documentation
SHADE_STATE_CLOSED
#define SHADE_STATE_CLOSED "closed"
Shade closed state string
Referenced by coapHandleServer().
SHADE_STATE_DRAWN
#define SHADE_STATE_DRAWN "drawn"
Shade drawn state string
Referenced by coapHandleServer().
SHADE_STATE_OPEN
#define SHADE_STATE_OPEN "open"
Shade open state string
Referenced by coapHandleServer().
SHADE_STATE_URI
#define SHADE_STATE_URI "blinds/state"
Shade state string
SHADE_URI
#define SHADE_URI "blinds/"
Shade uri string
Enumeration Type Documentation
Shade_evt_t
enum Shade_evt_t
Shade events.
Enumerator
Shade_evtOpen
Shade_evtClosed
Shade_evtDrawn
Shade_evtNwkSetup
Shade_evtKeyLeft
Shade_evtKeyRight
Shade_evtNwkJoined
Shade_evtNwkJoinFailure
Function Documentation
Shade_postEvt()
void Shade_postEvt (Shade_evt_t event)
Posts an event to the Shade task.
Parameters
event event to post.
Returns
None
References shadeEvents.
Referenced by coapHandleServer(), processKeyChangeCB(), and processOtStackEvents().
© Copyright 1995-2018, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale