TI Thread API Documentation: examples/shade/shade.c File Reference
shade.c File Reference
Data Structures
struct attrDesc_t
CoAP attribute descriptor.
Macros
#define ATTR_READ 0x01
#define ATTR_REPORT 0x04
#define ATTR_WRITE 0x02
Functions
static void coapHandleServer (void *aContext, otCoapHeader *aHeader, otMessage *aMessage, const otMessageInfo *aMessageInfo)
Callback function registered with the Coap server. Processes the coap request from the clients.
static void initEvent (void)
Initialize and construct the TIRTOS events.
void otPlatLog (otLogLevel aLogLevel, otLogRegion aLogRegion, const char *aFormat,...)
void otPlatUartReceived (const uint8_t *aBuf, uint16_t aBufLength)
void otPlatUartSendDone (void)
static void processEvents (void)
Processes the events.
static void processKeyChangeCB (uint8_t keysPressed)
Handles the key press events.
static void processOtStackEvents (uint8_t evt)
Processes the OT stack events.
static void resetPriority (void)
static otError setupCoapServer (otInstance *aInstance, const attrDesc_t *attr)
sets up the application coap server.
void Shade_postEvt (Shade_evt_t event)
Posts an event to the Shade task.
void * Shade_task (void *arg0)
void Shade_taskCreate (void)
Variables
static uint8_t attrState [15] = SHADE_STATE_OPEN
const attrDesc_t coapAttr
static otCoapResource coapResource
const uint8_t pskd [] = "SHADEEX1"
static bool serverSetup
static Event_Struct shadeEvents
static char stack [TASK_CONFIG_SHADE_TASK_STACK_SIZE]
Macro Definition Documentation
ATTR_READ
#define ATTR_READ 0x01
Referenced by setupCoapServer().
ATTR_REPORT
#define ATTR_REPORT 0x04
ATTR_WRITE
#define ATTR_WRITE 0x02
Referenced by setupCoapServer().
Function Documentation
coapHandleServer()
static void coapHandleServer (void * aContext, otCoapHeader * aHeader, otMessage * aMessage, const otMessageInfo * aMessageInfo) static
Callback function registered with the Coap server. Processes the coap request from the clients.
Parameters
aContext A pointer to the context information.
aHeader A pointer to the CoAP header.
aMessage A pointer to the message.
aMessageInfo A pointer to the message info.
Returns
None
References attrState, Shade_evtClosed, Shade_evtDrawn, Shade_evtOpen, Shade_postEvt(), SHADE_STATE_CLOSED, SHADE_STATE_DRAWN, and SHADE_STATE_OPEN.
Referenced by setupCoapServer().
initEvent()
static void initEvent (void) static
Initialize and construct the TIRTOS events.
Returns
None
References shadeEvents.
Referenced by Shade_task().
otPlatLog()
void otPlatLog (otLogLevel aLogLevel, otLogRegion aLogRegion, const char * aFormat, ...)
Documented in openthread/platform/logging.h.
otPlatUartReceived()
void otPlatUartReceived (const uint8_t * aBuf, uint16_t aBufLength)
Documented in openthread/platform/uart.h.
otPlatUartSendDone()
void otPlatUartSendDone (void)
Documented in openthread/platform/uart.h.
processEvents()
static void processEvents (void) static
Processes the events.
Returns
None
References coapAttr, DISPUTILS_LCDPRINTF, DISPUTILS_SERIALPRINTF, Images_shadeClosed, Images_shadeDrawn, Images_shadeOpen, OT_STACK_EVENT_NWK_JOIN_IN_PROGRESS, OtInstance_get(), OtStack_joinNetwork(), OtStack_joinState(), OtStack_setupNetwork(), pskd, serverSetup, setupCoapServer(), Shade_evtClosed, Shade_evtDrawn, Shade_evtKeyRight, Shade_evtNwkJoined, Shade_evtNwkJoinFailure, Shade_evtNwkSetup, Shade_evtOpen, and shadeEvents.
Referenced by Shade_task().
processKeyChangeCB()
static void processKeyChangeCB (uint8_t keysPressed) static
Handles the key press events.
Parameters
keysPressed identifies which keys were pressed
Returns
None
References KEYS_RIGHT, Shade_evtKeyRight, and Shade_postEvt().
Referenced by Shade_task().
processOtStackEvents()
static void processOtStackEvents (uint8_t evt) static
Processes the OT stack events.
Parameters
evt Event identifier.
Returns
None
References OT_STACK_EVENT_NWK_DATA_CHANGED, OT_STACK_EVENT_NWK_JOINED, OT_STACK_EVENT_NWK_JOINED_FAILURE, Shade_evtNwkJoined, Shade_evtNwkJoinFailure, Shade_evtNwkSetup, and Shade_postEvt().
Referenced by Shade_task().
resetPriority()
static void resetPriority (void) static
Return thread priority after initialization.
References TASK_CONFIG_SHADE_TASK_PRIORITY.
Referenced by Shade_task().
setupCoapServer()
static otError setupCoapServer (otInstance * aInstance, const attrDesc_t * attr) static
sets up the application coap server.
Parameters
aInstance A pointer to the context information.
attr Attribute data
Returns
OT_ERROR_NONE if successful, else error code
References ATTR_READ, ATTR_WRITE, coapHandleServer(), coapResource, OtRtosApi_lock(), OtRtosApi_unlock(), attrDesc_t::type, and attrDesc_t::uriPath.
Referenced by processEvents().
Shade_postEvt()
void Shade_postEvt (Shade_evt_t event)
Posts an event to the Shade task.
Parameters
event event to post.
Returns
None
References shadeEvents.
Referenced by coapHandleServer(), processKeyChangeCB(), and processOtStackEvents().
Shade_task()
void * Shade_task (void * arg0)
Shade processing thread.
References DISPUTILS_LCDPRINTF, DispUtils_open(), DISPUTILS_SERIALPRINTF, initEvent(), KeysUtils_initialize(), OtInstance_get(), OtRtosApi_lock(), OtRtosApi_unlock(), OtStack_registerCallback(), processEvents(), processKeyChangeCB(), processOtStackEvents(), pskd, and resetPriority().
Referenced by Shade_taskCreate().
Shade_taskCreate()
void Shade_taskCreate (void)
Documented in task_config.h.
References Shade_task(), stack, and TASK_CONFIG_SHADE_TASK_STACK_SIZE.
Referenced by main().
Variable Documentation
attrState
uint8_t attrState[15] = SHADE_STATE_OPEN static
Referenced by coapHandleServer().
coapAttr
const attrDesc_t coapAttr
Initial value:
= {
    SHADE_STATE_URI,
    (ATTR_READ|ATTR_WRITE),
    attrState,
}
Referenced by processEvents().
coapResource
otCoapResource coapResource static
Referenced by setupCoapServer().
pskd
const uint8_t pskd[] = "SHADEEX1"
Pre shared key of the device used during the commissioning stage.
Referenced by processEvents(), and Shade_task().
serverSetup
bool serverSetup static
Referenced by processEvents().
shadeEvents
Event_Struct shadeEvents static
Referenced by initEvent(), processEvents(), and Shade_postEvt().
stack
char stack[TASK_CONFIG_SHADE_TASK_STACK_SIZE] static
Referenced by Shade_taskCreate().
© Copyright 1995-2018, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale