TI Thread API Documentation: examples/shade/otstack.c File Reference
otstack.c File Reference
Macros
#define OT_STACK_EVENT_SIGNAL_ALARM_PROCESS Event_Id_00
#define OT_STACK_EVENT_SIGNAL_ALARMU_PROCESS Event_Id_05
#define OT_STACK_EVENT_SIGNAL_RADIO_PROCESS Event_Id_01
#define OT_STACK_EVENT_SIGNAL_RANDOM_PROCESS Event_Id_04
#define OT_STACK_EVENT_SIGNAL_TASLETS_PENDING Event_Id_02
#define OT_STACK_EVENT_SIGNAL_UART_PROCESS Event_Id_03
Functions
static otError createIid (otInstance *aInstance, otNetifAddress *aAddress, void *aContext)
Creates the interface identifier.
void handleNetifStateChanged (uint32_t aFlags, void *aContext)
Callback function registered with the netif.
void joinerCallback (otError aError, void *aContext)
callback function registered with the OpenThread to get the joining network status.
otInstance * OtInstance_get (void)
void OtStack_joinNetwork (const char *pskd)
Allows the application to start the network join process via the commissioner.
uint8_t OtStack_joinState (void)
Returns the current network join event of the OpenThread stack.
void OtStack_registerCallback (OtStack_EventsCallback_t appCB)
Allows the application to register callback for ot stack events.
bool OtStack_setupNetwork (void)
Allows the application to setup the thread network(thread protocol operation) after the device has successfully joined the network.
void * OtStack_task (void *arg0)
void OtStack_taskCreate (void)
void otTaskletsSignalPending (otInstance *aInstance)
void platformAlarmMicroSignal ()
void platformAlarmSignal ()
void platformRadioSignal ()
void platformRandomSignal (void)
void platformUartSignal ()
static void resetPriority (void)
Variables
static otNetifAddress addresses [OT_STACK_MAX_ADDRESSES]
static OtStack_EventsCallback_t appEventHandler = NULL
static Event_Struct OtStack_events
static otInstance * OtStack_instance
static char OtStack_stack [TASK_CONFIG_OT_TASK_STACK_SIZE]
static volatile uint8_t otStackEvents = OT_STACK_EVENT_NWK_NOT_JOINED
Macro Definition Documentation
OT_STACK_EVENT_SIGNAL_ALARM_PROCESS
#define OT_STACK_EVENT_SIGNAL_ALARM_PROCESS Event_Id_00
Referenced by OtStack_task(), and platformAlarmSignal().
OT_STACK_EVENT_SIGNAL_ALARMU_PROCESS
#define OT_STACK_EVENT_SIGNAL_ALARMU_PROCESS Event_Id_05
Referenced by OtStack_task(), and platformAlarmMicroSignal().
OT_STACK_EVENT_SIGNAL_RADIO_PROCESS
#define OT_STACK_EVENT_SIGNAL_RADIO_PROCESS Event_Id_01
Referenced by OtStack_task(), and platformRadioSignal().
OT_STACK_EVENT_SIGNAL_RANDOM_PROCESS
#define OT_STACK_EVENT_SIGNAL_RANDOM_PROCESS Event_Id_04
Referenced by OtStack_task(), and platformRandomSignal().
OT_STACK_EVENT_SIGNAL_TASLETS_PENDING
#define OT_STACK_EVENT_SIGNAL_TASLETS_PENDING Event_Id_02
Referenced by OtStack_task(), and otTaskletsSignalPending().
OT_STACK_EVENT_SIGNAL_UART_PROCESS
#define OT_STACK_EVENT_SIGNAL_UART_PROCESS Event_Id_03
Referenced by OtStack_task(), and platformUartSignal().
Function Documentation
createIid()
static otError createIid (otInstance * aInstance, otNetifAddress * aAddress, void * aContext) static
Creates the interface identifier.
Parameters
aInstance A pointer to the context information.
aAddress A pointer to structure containing IPv6 address for which IID is being created.
aContext A pointer to creator-specific context.
Returns
OT_ERROR_NONE
References OT_STACK_IID_ADDRESS_LSB.
Referenced by handleNetifStateChanged().
handleNetifStateChanged()
void handleNetifStateChanged (uint32_t aFlags, void * aContext)
Callback function registered with the netif.
Parameters
aFlags A bit-field indicating specific state that has changed.
aContext A pointer to application-specific context.
Returns
None
References addresses, appEventHandler, createIid(), OT_STACK_EVENT_NWK_DATA_CHANGED, and otStackEvents.
joinerCallback()
void joinerCallback (otError aError, void * aContext)
callback function registered with the OpenThread to get the joining network status.
Parameters
aError error value returned during the joining process.
aContext context if any (ignored).
Returns
None
References appEventHandler, OT_STACK_EVENT_NWK_JOINED, OT_STACK_EVENT_NWK_JOINED_FAILURE, and otStackEvents.
Referenced by OtStack_joinNetwork().
OtInstance_get()
otInstance* OtInstance_get (void)
Documented in otsupport/otinstance.h.
References OtStack_instance.
OtStack_joinNetwork()
void OtStack_joinNetwork (const char * pskd)
Allows the application to start the network join process via the commissioner.
Parameters
pskd Pre-shared key of the device.
Returns
None
Referenced by processEvents().
OtStack_joinState()
uint8_t OtStack_joinState (void)
Returns the current network join event of the OpenThread stack.
Returns
uint8_t event value.
Referenced by processEvents().
OtStack_registerCallback()
void OtStack_registerCallback (OtStack_EventsCallback_t appCB)
Allows the application to register callback for ot stack events.
Parameters
appCB application callback function.
Returns
None
Referenced by DoorLock_task(), Shade_task(), TempSensor_task(), and Thermostat_task().
OtStack_setupNetwork()
bool OtStack_setupNetwork (void)
Allows the application to setup the thread network(thread protocol operation) after the device has successfully joined the network.
Returns
bool true if succesful in starting the threead protocol operation.
Referenced by processEvents().
OtStack_task()
void* OtStack_task (void * arg0)
Main processing thread for OpenThread Stack.
References extPanId, handleNetifStateChanged(), OT_STACK_EVENT_SIGNAL_ALARM_PROCESS, OT_STACK_EVENT_SIGNAL_ALARMU_PROCESS, OT_STACK_EVENT_SIGNAL_RADIO_PROCESS, OT_STACK_EVENT_SIGNAL_RANDOM_PROCESS, OT_STACK_EVENT_SIGNAL_TASLETS_PENDING, OT_STACK_EVENT_SIGNAL_UART_PROCESS, OtRtosApi_init(), OtRtosApi_lock(), OtRtosApi_unlock(), OtStack_events, OtStack_instance, platformAlarmMicroProcess(), platformAlarmProcess(), PlatformInit(), platformRadioProcess(), platformRandomProcess(), platformUartProcess(), and resetPriority().
OtStack_taskCreate()
void OtStack_taskCreate (void)
Documented in task_config.h.
References OtStack_stack, OtStack_task(), and TASK_CONFIG_OT_TASK_STACK_SIZE.
otTaskletsSignalPending()
void otTaskletsSignalPending (otInstance * aInstance)
Callback from OpenThread stack to indicate tasklets are pending processing.
References OT_STACK_EVENT_SIGNAL_TASLETS_PENDING, and OtStack_events.
platformAlarmMicroSignal()
void platformAlarmMicroSignal (void)
Callback from the alarm module indicating need for processing.
References OT_STACK_EVENT_SIGNAL_ALARMU_PROCESS, and OtStack_events.
platformAlarmSignal()
void platformAlarmSignal (void)
Callback from the alarm module indicating need for processing.
References OT_STACK_EVENT_SIGNAL_ALARM_PROCESS, and OtStack_events.
platformRadioSignal()
void platformRadioSignal (void)
Callback from the radio module indicating need for processing.
References OT_STACK_EVENT_SIGNAL_RADIO_PROCESS, and OtStack_events.
platformRandomSignal()
void platformRandomSignal (void)
Callback from the random generator module indicating need for processing.
References OT_STACK_EVENT_SIGNAL_RANDOM_PROCESS, and OtStack_events.
platformUartSignal()
void platformUartSignal (void)
Callback from the alarm module indicating need for processing.
References OT_STACK_EVENT_SIGNAL_UART_PROCESS, and OtStack_events.
resetPriority()
static void resetPriority (void) static
Return thread priority after initialization.
References TASK_CONFIG_OT_TASK_PRIORITY.
Referenced by OtStack_task().
Variable Documentation
addresses
otNetifAddress addresses[OT_STACK_MAX_ADDRESSES] static
Referenced by handleNetifStateChanged().
appEventHandler
OtStack_EventsCallback_t appEventHandler = NULL static
Referenced by handleNetifStateChanged(), joinerCallback(), and OtStack_registerCallback().
OtStack_events
Event_Struct OtStack_events static
Referenced by OtStack_task(), otTaskletsSignalPending(), platformAlarmMicroSignal(), platformAlarmSignal(), platformRadioSignal(), platformRandomSignal(), and platformUartSignal().
OtStack_instance
otInstance* OtStack_instance static
Referenced by OtInstance_get(), OtStack_joinNetwork(), OtStack_setupNetwork(), and OtStack_task().
OtStack_stack
char OtStack_stack[TASK_CONFIG_OT_TASK_STACK_SIZE] static
Referenced by OtStack_taskCreate().
otStackEvents
volatile uint8_t otStackEvents = OT_STACK_EVENT_NWK_NOT_JOINED static
Referenced by handleNetifStateChanged(), joinerCallback(), OtStack_joinNetwork(), and OtStack_joinState().
© Copyright 1995-2018, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale