TI Thread API Documentation: examples/tempsensor/tempsensor.h File Reference
tempsensor.h File Reference
Macros
#define TEMPSENSOR_TEMP_URI "tempsensor/temperature"
#define THERMOSTAT_ADDRESS_LSB 7
#define THERMOSTAT_TEMP_URI "thermostat/temperature"
Enumerations
enum TempSensor_evt {
TempSensor_evtReportTemp = Event_Id_00, TempSensor_evtNwkSetup = Event_Id_01, TempSensor_evtAddressValid = Event_Id_02, TempSensor_evtKeyRight = Event_Id_03,
TempSensor_evtNwkJoined = Event_Id_04, TempSensor_evtNwkJoinFailure = Event_Id_05
}
Functions
void TempSensor_notifyGUA (otNetifAddress *aAddress)
Sets the reporting address for the temp sensor task.
void TempSensor_postEvt (TempSensor_evt event)
Posts an event to the Temperature Sensor task.
Macro Definition Documentation
TEMPSENSOR_TEMP_URI
#define TEMPSENSOR_TEMP_URI "tempsensor/temperature"
THERMOSTAT_ADDRESS_LSB
#define THERMOSTAT_ADDRESS_LSB 7
Referenced by TempSensor_notifyGUA().
THERMOSTAT_TEMP_URI
#define THERMOSTAT_TEMP_URI "thermostat/temperature"
Referenced by tempSensorReport().
Enumeration Type Documentation
TempSensor_evt
enum TempSensor_evt
Temperature Sensor events.
Enumerator
TempSensor_evtReportTemp
TempSensor_evtNwkSetup
TempSensor_evtAddressValid
TempSensor_evtKeyRight
TempSensor_evtNwkJoined
TempSensor_evtNwkJoinFailure
Function Documentation
TempSensor_notifyGUA()
void TempSensor_notifyGUA (otNetifAddress * aAddress)
Sets the reporting address for the temp sensor task.
Parameters
[in] aAddress address with prefix to copy.
Note
The reporting address least significant byte will be set to THERMOSTAT_ADDRESS_LSB. The address passed into this function is only used for the prefix assignment.
References TempSensor_evtAddressValid, tempSensorEvents, THERMOSTAT_ADDRESS_LSB, and thermostatAddress.
Referenced by createIid().
TempSensor_postEvt()
void TempSensor_postEvt (TempSensor_evt event)
Posts an event to the Temperature Sensor task.
Parameters
event event to post.
Returns
None
References tempSensorEvents.
Referenced by processKeyChangeCB(), processOtStackEvents(), and reportingTimeoutCB().
© Copyright 1995-2018, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale