TI Thread API Documentation: examples/tempsensor/tempsensor.c File Reference
tempsensor.c File Reference
Data Structures
struct attrDesc_t
CoAP attribute descriptor.
Macros
#define ATTR_READ 0x01
#define ATTR_REPORT 0x04
#define ATTR_WRITE 0x02
#define DEFAULT_COAP_HEADER_TOKEN_LEN 2
#define REPORTING_INTERVAL 10000
Functions
static void coapHandleServer (void *aContext, otCoapHeader *aHeader, otMessage *aMessage, const otMessageInfo *aMessageInfo)
Callback function registered with the Coap server. Processes the coap request from the clients.
static void configureReportingTimer (uint32_t timeout)
Configure the timer.
static void initEvent (void)
Initialize and construct the TIRTOS events.
void otPlatLog (otLogLevel aLogLevel, otLogRegion aLogRegion, const char *aFormat,...)
void otPlatUartReceived (const uint8_t *aBuf, uint16_t aBufLength)
void otPlatUartSendDone (void)
static int processEvents (void)
Processes the events.
static void processKeyChangeCB (uint8_t keysPressed)
Handles the key press events.
static void processOtStackEvents (uint8_t evt)
Processes the OT stack events.
static void reportingTimeoutCB (UArg a0)
Callback function registered with the Coap server. Processes the coap request from the clients.
static void resetPriority (void)
static otError setupCoapServer (otInstance *aInstance, const attrDesc_t *attr)
sets up the application coap server.
static void startReportingTimer (void)
void TempSensor_notifyGUA (otNetifAddress *aAddress)
Sets the reporting address for the temp sensor task.
void TempSensor_postEvt (TempSensor_evt event)
Posts an event to the Temperature Sensor task.
static void * TempSensor_task (void *arg0)
void TempSensor_taskCreate (void)
static void tempSensorReport (void)
Reports the temperature to another coap device.
Variables
static uint8_t attrTemperature [5] = "70"
const attrDesc_t coapAttr
static otCoapResource coapResource
uint16_t peerPort = OT_DEFAULT_COAP_PORT
const uint8_t pskd [] = "TMPSENS1"
Clock_Handle reportClkHandle
Clock_Struct reportClkStruct
static bool serverSetup
static char stack [TASK_CONFIG_TEMPSENSOR_TASK_STACK_SIZE]
static int temperatureValue = 70
static Event_Struct tempSensorEvents
otIp6Address thermostatAddress
Macro Definition Documentation
ATTR_READ
#define ATTR_READ 0x01
Referenced by setupCoapServer().
ATTR_REPORT
#define ATTR_REPORT 0x04
ATTR_WRITE
#define ATTR_WRITE 0x02
Referenced by setupCoapServer().
DEFAULT_COAP_HEADER_TOKEN_LEN
#define DEFAULT_COAP_HEADER_TOKEN_LEN 2
Referenced by tempSensorReport().
REPORTING_INTERVAL
#define REPORTING_INTERVAL 10000
Referenced by TempSensor_task().
Function Documentation
coapHandleServer()
static void coapHandleServer (void * aContext, otCoapHeader * aHeader, otMessage * aMessage, const otMessageInfo * aMessageInfo) static
Callback function registered with the Coap server. Processes the coap request from the clients.
Parameters
aContext A pointer to the context information.
aHeader A pointer to the CoAP header.
aMessage A pointer to the message.
aMessageInfo A pointer to the message info.
Returns
None
References attrTemperature.
Referenced by setupCoapServer().
configureReportingTimer()
static void configureReportingTimer (uint32_t timeout) static
Configure the timer.
Parameters
timeout time in milliseconds.
Returns
None
References reportClkHandle, reportClkStruct, and reportingTimeoutCB().
Referenced by TempSensor_task().
initEvent()
static void initEvent (void) static
Initialize and construct the TIRTOS events.
Returns
None
References tempSensorEvents.
Referenced by TempSensor_task().
otPlatLog()
void otPlatLog (otLogLevel aLogLevel, otLogRegion aLogRegion, const char * aFormat, ...)
Documented in openthread/platform/logging.h.
otPlatUartReceived()
void otPlatUartReceived (const uint8_t * aBuf, uint16_t aBufLength)
Documented in openthread/platform/uart.h.
otPlatUartSendDone()
void otPlatUartSendDone (void)
Documented in openthread/platform/uart.h.
processEvents()
static int processEvents (void) static
Processes the events.
Returns
None
References coapAttr, DISPUTILS_SERIALPRINTF, OT_STACK_EVENT_NWK_JOIN_IN_PROGRESS, OtInstance_get(), OtStack_joinNetwork(), OtStack_joinState(), OtStack_setupNetwork(), pskd, serverSetup, setupCoapServer(), startReportingTimer(), TempSensor_evtAddressValid, TempSensor_evtKeyRight, TempSensor_evtNwkJoined, TempSensor_evtNwkJoinFailure, TempSensor_evtNwkSetup, TempSensor_evtReportTemp, tempSensorEvents, and tempSensorReport().
Referenced by TempSensor_task().
processKeyChangeCB()
static void processKeyChangeCB (uint8_t keysPressed) static
Handles the key press events.
Parameters
keysPressed identifies which keys were pressed
Returns
None
References KEYS_RIGHT, TempSensor_evtKeyRight, and TempSensor_postEvt().
Referenced by TempSensor_task().
processOtStackEvents()
static void processOtStackEvents (uint8_t evt) static
Processes the OT stack events.
Parameters
evt Event identifier.
Returns
None
References OT_STACK_EVENT_NWK_DATA_CHANGED, OT_STACK_EVENT_NWK_JOINED, OT_STACK_EVENT_NWK_JOINED_FAILURE, TempSensor_evtNwkJoined, TempSensor_evtNwkJoinFailure, TempSensor_evtNwkSetup, and TempSensor_postEvt().
Referenced by TempSensor_task().
reportingTimeoutCB()
static void reportingTimeoutCB (UArg a0) static
Callback function registered with the Coap server. Processes the coap request from the clients.
Parameters
a0 argument passed by the clock if set up.
Returns
None
References TempSensor_evtReportTemp, and TempSensor_postEvt().
Referenced by configureReportingTimer().
resetPriority()
static void resetPriority (void) static
Return thread priority after initialization.
References TASK_CONFIG_TEMPSENSOR_TASK_PRIORITY.
Referenced by TempSensor_task().
setupCoapServer()
static otError setupCoapServer (otInstance * aInstance, const attrDesc_t * attr) static
sets up the application coap server.
Parameters
aInstance A pointer to the context information.
attr Attribute data
Returns
OT_ERROR_NONE if successful, else error code
References ATTR_READ, ATTR_WRITE, coapHandleServer(), coapResource, OtRtosApi_lock(), OtRtosApi_unlock(), attrDesc_t::type, and attrDesc_t::uriPath.
Referenced by processEvents().
startReportingTimer()
static void startReportingTimer (void) static
Starts the reporting timer.
Should be called after the reporting timer has been created, and after the GUA has been registered.
References reportClkHandle.
Referenced by processEvents().
TempSensor_notifyGUA()
void TempSensor_notifyGUA (otNetifAddress * aAddress)
Sets the reporting address for the temp sensor task.
Parameters
[in] aAddress address with prefix to copy.
Note
The reporting address least significant byte will be set to THERMOSTAT_ADDRESS_LSB. The address passed into this function is only used for the prefix assignment.
References TempSensor_evtAddressValid, tempSensorEvents, THERMOSTAT_ADDRESS_LSB, and thermostatAddress.
Referenced by createIid().
TempSensor_postEvt()
void TempSensor_postEvt (TempSensor_evt event)
Posts an event to the Temperature Sensor task.
Parameters
event event to post.
Returns
None
References tempSensorEvents.
Referenced by processKeyChangeCB(), processOtStackEvents(), and reportingTimeoutCB().
TempSensor_task()
void * TempSensor_task (void * arg0) static
Temp Sensor processing thread.
References configureReportingTimer(), DispUtils_open(), DISPUTILS_SERIALPRINTF, initEvent(), KeysUtils_initialize(), OtInstance_get(), OtRtosApi_lock(), OtRtosApi_unlock(), OtStack_registerCallback(), processEvents(), processKeyChangeCB(), processOtStackEvents(), pskd, REPORTING_INTERVAL, and resetPriority().
Referenced by TempSensor_taskCreate().
TempSensor_taskCreate()
void TempSensor_taskCreate (void)
Creation funciton for the temperature sensor application task.
References stack, TASK_CONFIG_TEMPSENSOR_TASK_STACK_SIZE, and TempSensor_task().
Referenced by main().
tempSensorReport()
static void tempSensorReport (void) static
Reports the temperature to another coap device.
Returns
None
References attrTemperature, DEFAULT_COAP_HEADER_TOKEN_LEN, DISPUTILS_SERIALPRINTF, OtInstance_get(), OtRtosApi_lock(), OtRtosApi_unlock(), peerPort, reportClkHandle, temperatureValue, THERMOSTAT_TEMP_URI, and thermostatAddress.
Referenced by processEvents().
Variable Documentation
attrTemperature
uint8_t attrTemperature[5] = "70" static
Referenced by coapHandleServer(), and tempSensorReport().
coapAttr
const attrDesc_t coapAttr
Initial value:
= {
    TEMPSENSOR_TEMP_URI,
    (ATTR_READ|ATTR_REPORT),
    attrTemperature,
}
Referenced by processEvents().
coapResource
otCoapResource coapResource static
Referenced by setupCoapServer().
peerPort
uint16_t peerPort = OT_DEFAULT_COAP_PORT
Referenced by tempSensorReport().
pskd
const uint8_t pskd[] = "TMPSENS1"
Pre shared key of the device used during the commissioning stage.
Referenced by processEvents(), and TempSensor_task().
reportClkHandle
Clock_Handle reportClkHandle
Referenced by configureReportingTimer(), startReportingTimer(), and tempSensorReport().
reportClkStruct
Clock_Struct reportClkStruct
Referenced by configureReportingTimer().
serverSetup
bool serverSetup static
Referenced by processEvents().
stack
char stack[TASK_CONFIG_TEMPSENSOR_TASK_STACK_SIZE] static
Referenced by TempSensor_taskCreate().
temperatureValue
int temperatureValue = 70 static
Referenced by tempSensorReport().
tempSensorEvents
Event_Struct tempSensorEvents static
Referenced by initEvent(), processEvents(), TempSensor_notifyGUA(), and TempSensor_postEvt().
thermostatAddress
otIp6Address thermostatAddress
Referenced by TempSensor_notifyGUA(), and tempSensorReport().
© Copyright 1995-2018, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale