TI Thread API Documentation: examples/thermostat/thermostat.h File Reference
thermostat.h File Reference
Macros
#define THERMOSTAT_SET_PT_URI "thermostat/setpoint"
#define THERMOSTAT_TEMP_URI "thermostat/temperature"
Enumerations
enum Thermostat_evt {
Thermostat_evtTempChange = Event_Id_00, Thermostat_evtSetPtChange = Event_Id_01, Thermostat_evtNwkSetup = Event_Id_02, Thermostat_evtGraphicExt = Event_Id_03,
Thermostat_evtKeyRight = Event_Id_04, Thermostat_evtNwkJoined = Event_Id_05, Thermostat_evtNwkJoinFailure = Event_Id_06
}
Functions
void Thermostat_postEvt (Thermostat_evt event)
Posts an event to the Thermostat task.
Macro Definition Documentation
THERMOSTAT_SET_PT_URI
#define THERMOSTAT_SET_PT_URI "thermostat/setpoint"
THERMOSTAT_TEMP_URI
#define THERMOSTAT_TEMP_URI "thermostat/temperature"
Enumeration Type Documentation
Thermostat_evt
enum Thermostat_evt
Thermostat events.
Enumerator
Thermostat_evtTempChange
Thermostat_evtSetPtChange
Thermostat_evtNwkSetup
Thermostat_evtGraphicExt
Thermostat_evtKeyRight
Thermostat_evtNwkJoined
Thermostat_evtNwkJoinFailure
Function Documentation
Thermostat_postEvt()
void Thermostat_postEvt (Thermostat_evt event)
Posts an event to the Thermostat task.
Parameters
event event to post.
Returns
None
References thermostatEvents.
Referenced by coapHandleSetPt(), coapHandleTemp(), processKeyChangeCB(), and processOtStackEvents().
© Copyright 1995-2018, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale