TI Thread API Documentation: examples/thermostat/thermostat.c File Reference
thermostat.c File Reference
Data Structures
struct attrDesc_t
CoAP attribute descriptor.
Macros
#define ATTR_COUNT 2
#define ATTR_READ 0x01
#define ATTR_REPORT 0x04
#define ATTR_WRITE 0x02
#define FRAME_PERIOD 230
#define TEMP_MAX_CHARS 3
Enumerations
enum Thermostat_mode { Thermostat_modeCooling, Thermostat_modeHeating }
Functions
static void coapHandleSetPt (void *aContext, otCoapHeader *aHeader, otMessage *aMessage, const otMessageInfo *aMessageInfo)
Callback function registered with the Coap server. Processes the coap request from the clients.
static void coapHandleTemp (void *aContext, otCoapHeader *aHeader, otMessage *aMessage, const otMessageInfo *aMessageInfo)
Callback function registered with the Coap server. Processes the coap request from the clients.
static void flushLcd (void)
Display's the image on the LCD screen.
static uint32_t getCharOffset (uint8_t character, int charOffset)
Calculates the offset for the font sprite buffers based on a char.
static void initEvent (void)
Initialize and construct the TIRTOS events.
void otPlatLog (otLogLevel aLogLevel, otLogRegion aLogRegion, const char *aFormat,...)
void otPlatUartReceived (const uint8_t *aBuf, uint16_t aBufLength)
void otPlatUartSendDone (void)
static int processEvents (void)
Processes the events.
static void processKeyChangeCB (uint8_t keysPressed)
Handles the key press events.
static void processOtStackEvents (uint8_t evt)
Processes the OT stack events.
static void resetPriority (void)
static otError setupCoapServer (otInstance *aInstance, const attrDesc_t *attr)
sets up the application coap server.
void Thermostat_postEvt (Thermostat_evt event)
Posts an event to the Thermostat task.
void * Thermostat_task (void *arg0)
void Thermostat_taskCreate (void)
static void updateSetPtLcd (char *temperatureStr)
update the setpoint font buffers on the setpoint digit sprites.
static void updateTemperatureLcd (char *temperatureStr)
update the temperature font buffers on the temperature digit sprites.
static void updateThermostatMode (void)
update the mode of the thermostat by comparing the setpoint and temp.
Variables
static attrDesc_t coapAttrs [ATTR_COUNT]
static otCoapResource coapResourceSetPt
static otCoapResource coapResourceTemp
Display_Handle lcdHandle = NULL
const uint8_t pskd [] = "THERMSTAT1"
Display_Handle serialHandle = NULL
static bool serverSetup
static int setPoint = 34
static char stack [TASK_CONFIG_THERMOSTAT_TASK_STACK_SIZE]
static int temperature = 68
static Event_Struct thermostatEvents
static Thermostat_mode thermostatMode = Thermostat_modeCooling
static char thermostatSetPt [TEMP_MAX_CHARS] = "34"
static char thermostatTemp [TEMP_MAX_CHARS] = "68"
const uint8_t zeroCharOffset = '0'
Macro Definition Documentation
ATTR_COUNT
#define ATTR_COUNT 2
ATTR_READ
#define ATTR_READ 0x01
Referenced by setupCoapServer().
ATTR_REPORT
#define ATTR_REPORT 0x04
ATTR_WRITE
#define ATTR_WRITE 0x02
Referenced by setupCoapServer().
FRAME_PERIOD
#define FRAME_PERIOD 230
Referenced by Thermostat_task().
TEMP_MAX_CHARS
#define TEMP_MAX_CHARS 3
Referenced by coapHandleSetPt(), and coapHandleTemp().
Enumeration Type Documentation
Thermostat_mode
enum Thermostat_mode
Thermostat Modes.
Enumerator
Thermostat_modeCooling
Thermostat_modeHeating
Function Documentation
coapHandleSetPt()
static void coapHandleSetPt (void * aContext, otCoapHeader * aHeader, otMessage * aMessage, const otMessageInfo * aMessageInfo) static
Callback function registered with the Coap server. Processes the coap request from the clients.
Parameters
aContext A pointer to the context information.
aHeader A pointer to the CoAP header.
aMessage A pointer to the message.
aMessageInfo A pointer to the message info.
Returns
None
References TEMP_MAX_CHARS, Thermostat_evtSetPtChange, Thermostat_postEvt(), and thermostatSetPt.
Referenced by processEvents().
coapHandleTemp()
static void coapHandleTemp (void * aContext, otCoapHeader * aHeader, otMessage * aMessage, const otMessageInfo * aMessageInfo) static
Callback function registered with the Coap server. Processes the coap request from the clients.
Parameters
aContext A pointer to the context information.
aHeader A pointer to the CoAP header.
aMessage A pointer to the message.
aMessageInfo A pointer to the message info.
Returns
None
References TEMP_MAX_CHARS, Thermostat_evtTempChange, Thermostat_postEvt(), and thermostatTemp.
Referenced by processEvents().
flushLcd()
static void flushLcd (void) static
Display's the image on the LCD screen.
Parameters
image pointer to the Graphics Image data structure which has the information of the image data.
Returns
None
References GraphicExt_drawSprites(), SPRITE_COUNT, and thermostatSpriteList.
Referenced by processEvents().
getCharOffset()
static uint32_t getCharOffset (uint8_t character, int charOffset) static
Calculates the offset for the font sprite buffers based on a char.
Parameters
character character to map to font, any char from '0' to '9'.
charOffset offset for the font buffer.
Returns
None
References zeroCharOffset.
Referenced by updateSetPtLcd(), and updateTemperatureLcd().
initEvent()
static void initEvent (void) static
Initialize and construct the TIRTOS events.
Returns
None
References thermostatEvents.
Referenced by Thermostat_task().
otPlatLog()
void otPlatLog (otLogLevel aLogLevel, otLogRegion aLogRegion, const char * aFormat, ...)
Documented in openthread/platform/logging.h.
otPlatUartReceived()
void otPlatUartReceived (const uint8_t * aBuf, uint16_t aBufLength)
Documented in openthread/platform/uart.h.
otPlatUartSendDone()
void otPlatUartSendDone (void)
Documented in openthread/platform/uart.h.
processEvents()
static int processEvents (void) static
Processes the events.
Returns
None
References coapHandleSetPt(), coapHandleTemp(), COOL_ANIMATION_END, flushLcd(), GraphicExt_animateBackground(), GraphicExt_processEvt(), lcdHandle, OT_STACK_EVENT_NWK_JOIN_IN_PROGRESS, OtInstance_get(), OtStack_joinNetwork(), OtStack_joinState(), OtStack_setupNetwork(), attrDesc_t::pAttrHandlerCB, pskd, serialHandle, serverSetup, setPoint, setupCoapServer(), temperature, Thermostat_evtGraphicExt, Thermostat_evtKeyRight, Thermostat_evtNwkJoined, Thermostat_evtNwkJoinFailure, Thermostat_evtNwkSetup, Thermostat_evtSetPtChange, Thermostat_evtTempChange, thermostatBackgroundImage, thermostatEvents, thermostatSetPt, thermostatTemp, updateSetPtLcd(), updateTemperatureLcd(), and updateThermostatMode().
Referenced by Thermostat_task().
processKeyChangeCB()
static void processKeyChangeCB (uint8_t keysPressed) static
Handles the key press events.
Parameters
keysPressed identifies which keys were pressed
Returns
None
References KEYS_RIGHT, Thermostat_evtKeyRight, and Thermostat_postEvt().
Referenced by Thermostat_task().
processOtStackEvents()
static void processOtStackEvents (uint8_t evt) static
Processes the OT stack events.
Parameters
evt Event identifier.
Returns
None
References OT_STACK_EVENT_NWK_DATA_CHANGED, OT_STACK_EVENT_NWK_JOINED, OT_STACK_EVENT_NWK_JOINED_FAILURE, Thermostat_evtNwkJoined, Thermostat_evtNwkJoinFailure, Thermostat_evtNwkSetup, and Thermostat_postEvt().
Referenced by Thermostat_task().
resetPriority()
static void resetPriority (void) static
Return thread priority after initialization.
References TASK_CONFIG_THERMOSTAT_TASK_PRIORITY.
Referenced by Thermostat_task().
setupCoapServer()
static otError setupCoapServer (otInstance * aInstance, const attrDesc_t * attr) static
sets up the application coap server.
Parameters
aInstance A pointer to the context information.
attr Attribute data
Returns
OT_ERROR_NONE if successful, else error code
References ATTR_READ, ATTR_WRITE, OtRtosApi_lock(), OtRtosApi_unlock(), attrDesc_t::pAttrCoapResource, attrDesc_t::pAttrHandlerCB, attrDesc_t::type, and attrDesc_t::uriPath.
Referenced by processEvents().
Thermostat_postEvt()
void Thermostat_postEvt (Thermostat_evt event)
Posts an event to the Thermostat task.
Parameters
event event to post.
Returns
None
References thermostatEvents.
Referenced by coapHandleSetPt(), coapHandleTemp(), processKeyChangeCB(), and processOtStackEvents().
Thermostat_task()
void * Thermostat_task (void * arg0)
Thermostat processing thread.
References FRAME_PERIOD, GraphicExt_initAnimationModule(), initEvent(), KeysUtils_initialize(), lcdHandle, OtInstance_get(), OtRtosApi_lock(), OtRtosApi_unlock(), OtStack_registerCallback(), processEvents(), processKeyChangeCB(), processOtStackEvents(), pskd, resetPriority(), serialHandle, Thermostat_evtGraphicExt, and thermostatEvents.
Referenced by Thermostat_taskCreate().
Thermostat_taskCreate()
void Thermostat_taskCreate (void)
Documented in task_config.h.
References stack, TASK_CONFIG_THERMOSTAT_TASK_STACK_SIZE, and Thermostat_task().
Referenced by main().
updateSetPtLcd()
static void updateSetPtLcd (char * temperatureStr) static
update the setpoint font buffers on the setpoint digit sprites.
Parameters
temperatureStr current setpoint in string form.
Returns
None
References getCharOffset(), GraphicExt_sprite_t::image, SETPT_FONT_OFFSET, thermostatSetPtFontPix, and thermostatSpriteList.
Referenced by processEvents().
updateTemperatureLcd()
static void updateTemperatureLcd (char * temperatureStr) static
update the temperature font buffers on the temperature digit sprites.
Parameters
temperatureStr current temperature in string form.
Returns
None
References getCharOffset(), GraphicExt_sprite_t::image, TEMP_FONT_OFFSET, thermostatSpriteList, and thermostatTempFontPix.
Referenced by processEvents().
updateThermostatMode()
static void updateThermostatMode (void) static
update the mode of the thermostat by comparing the setpoint and temp.
Returns
None
References COOL_ANIMATION_END, GraphicExt_animateBackground(), HEAT_ANIMATION_END, GraphicExt_sprite_t::image, MODE_ICON_OFFSET, setPoint, temperature, Thermostat_modeCooling, Thermostat_modeHeating, thermostatBackgroundImage, thermostatMode, thermostatModePix, and thermostatSpriteList.
Referenced by processEvents().
Variable Documentation
coapAttrs
attrDesc_t coapAttrs[ATTR_COUNT] static
Initial value:
= {
{
    .uriPath = THERMOSTAT_TEMP_URI,
    .type = (ATTR_READ|ATTR_WRITE),
    .pValue = thermostatTemp,
    .pAttrCoapResource = &coapResourceTemp
},
{
    .uriPath = THERMOSTAT_SET_PT_URI,
    .type = (ATTR_READ|ATTR_WRITE),
    .pValue = thermostatSetPt,
    .pAttrCoapResource = &coapResourceSetPt
}
}
coapResourceSetPt
otCoapResource coapResourceSetPt static
coapResourceTemp
otCoapResource coapResourceTemp static
lcdHandle
Display_Handle lcdHandle = NULL
Referenced by GraphicExt_initAnimationModule(), processEvents(), and Thermostat_task().
pskd
const uint8_t pskd[] = "THERMSTAT1"
Pre shared key of the device used during the commissioning stage.
Referenced by processEvents(), and Thermostat_task().
serialHandle
Display_Handle serialHandle = NULL
Referenced by processEvents(), and Thermostat_task().
serverSetup
bool serverSetup static
Referenced by processEvents().
setPoint
int setPoint = 34 static
Referenced by processEvents(), and updateThermostatMode().
stack
char stack[TASK_CONFIG_THERMOSTAT_TASK_STACK_SIZE] static
Referenced by Thermostat_taskCreate().
temperature
int temperature = 68 static
Referenced by bme280_compensate_temperature_double(), bme280_compensate_temperature_int32(), bme280_compensate_temperature_int32_sixteen_bit_output(), processEvents(), and updateThermostatMode().
thermostatEvents
Event_Struct thermostatEvents static
Referenced by initEvent(), processEvents(), Thermostat_postEvt(), and Thermostat_task().
thermostatMode
Thermostat_mode thermostatMode = Thermostat_modeCooling static
Referenced by updateThermostatMode().
thermostatSetPt
char thermostatSetPt[TEMP_MAX_CHARS] = "34" static
Referenced by coapHandleSetPt(), and processEvents().
thermostatTemp
char thermostatTemp[TEMP_MAX_CHARS] = "68" static
Referenced by coapHandleTemp(), and processEvents().
zeroCharOffset
const uint8_t zeroCharOffset = '0'
Referenced by getCharOffset().
© Copyright 1995-2018, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale