TI Thread API Documentation: examples/sensors/tmp007.c File Reference
tmp007.c File Reference
Macros
#define CELSIUS_FAHREN_ADD 32 /* Celsius to Fahrenheit added factor */
#define CELSIUS_FAHREN_CONST 1.8F /* Multiplier for conversion */
#define CELSIUS_PER_LSB 0.03125F /* Degrees celsius per LSB */
#define CELSIUS_TO_KELVIN 273.15F /* Celsius to Kelvin addition factor */
#define CFG_ALRT 0x0100 /* Alert pin enable */
#define CFG_CONV_ON 0x1000 /* Conversion on mode */
#define CFG_SW_RST 0x8000 /* Software reset */
#define MAX_CELSIUS 256 /* Max degrees celsius */
#define MIN_CELSIUS -256 /* Min degrees celsius */
#define READ_BUF_SIZE 2
#define WAIT_POST_RESET 5 /* Wait time in ms after reset */
#define WRITE_BUF_SIZE 3
Functions
static bool i2cTransferFxn (I2C_Handle handle, I2C_Transaction transaction)
bool TMP007_close (TMP007_Handle handle)
Function to close a TMP007 sensor specified by the TMP007 handle.
bool TMP007_disableAlert (TMP007_Handle handle)
Function to disable the ALERT pin and GPIO interrupt.
bool TMP007_disableConversions (TMP007_Handle handle)
Function to put TMP007 sensor is low power state.
bool TMP007_enableAlert (TMP007_Handle handle)
Function to enable the ALERT pin and GPIO interrupt.
bool TMP007_enableConversions (TMP007_Handle handle)
Function to restore TMP007 to normal power operation.
bool TMP007_getTemp (TMP007_Handle handle, TMP007_TempScale scale, float *data, uint16_t registerAddress)
bool TMP007_getTempLimit (TMP007_Handle handle, TMP007_TempScale scale, float *data, uint16_t registerAddress)
void TMP007_init ()
Function to initialize TMP007 driver.
TMP007_Handle TMP007_open (unsigned int tmp007Index, I2C_Handle i2cHandle, TMP007_Params *params)
Function to open a given TMP007 sensor.
void TMP007_Params_init (TMP007_Params *params)
Function to initialize a TMP007_Params struct to its defaults.
bool TMP007_readRegister (TMP007_Handle handle, uint16_t *data, uint8_t registerAddress)
Read function for advanced users.
bool TMP007_setTempLimit (TMP007_Handle handle, TMP007_TempScale scale, float data, uint16_t bitMask, uint8_t registerAddress)
bool TMP007_writeRegister (TMP007_Handle handle, uint16_t data, uint8_t registerAddress)
Write function for advanced users. This is not thread safe.
Variables
TMP007_Config TMP007_config []
const TMP007_Params TMP007_defaultParams
Macro Definition Documentation
CELSIUS_FAHREN_ADD
#define CELSIUS_FAHREN_ADD 32 /* Celsius to Fahrenheit added factor */
Referenced by TMP007_getTemp(), TMP007_getTempLimit(), and TMP007_setTempLimit().
CELSIUS_FAHREN_CONST
#define CELSIUS_FAHREN_CONST 1.8F /* Multiplier for conversion */
Referenced by TMP007_getTemp(), TMP007_getTempLimit(), and TMP007_setTempLimit().
CELSIUS_PER_LSB
#define CELSIUS_PER_LSB 0.03125F /* Degrees celsius per LSB */
Referenced by TMP007_getTemp().
CELSIUS_TO_KELVIN
#define CELSIUS_TO_KELVIN 273.15F /* Celsius to Kelvin addition factor */
Referenced by TMP007_getTemp(), TMP007_getTempLimit(), and TMP007_setTempLimit().
CFG_ALRT
#define CFG_ALRT 0x0100 /* Alert pin enable */
Referenced by TMP007_disableAlert(), and TMP007_enableAlert().
CFG_CONV_ON
#define CFG_CONV_ON 0x1000 /* Conversion on mode */
Referenced by TMP007_disableConversions(), TMP007_enableConversions(), and TMP007_open().
CFG_SW_RST
#define CFG_SW_RST 0x8000 /* Software reset */
Referenced by TMP007_open().
MAX_CELSIUS
#define MAX_CELSIUS 256 /* Max degrees celsius */
Referenced by TMP007_setTempLimit().
MIN_CELSIUS
#define MIN_CELSIUS -256 /* Min degrees celsius */
Referenced by TMP007_setTempLimit().
READ_BUF_SIZE
#define READ_BUF_SIZE 2
Referenced by TMP007_readRegister().
WAIT_POST_RESET
#define WAIT_POST_RESET 5 /* Wait time in ms after reset */
Referenced by TMP007_open().
WRITE_BUF_SIZE
#define WRITE_BUF_SIZE 3
Referenced by TMP007_writeRegister().
Function Documentation
i2cTransferFxn()
static bool i2cTransferFxn (I2C_Handle handle, I2C_Transaction transaction) static
Referenced by TMP007_readRegister(), and TMP007_writeRegister().
TMP007_close()
bool TMP007_close (TMP007_Handle handle)
Function to close a TMP007 sensor specified by the TMP007 handle.
The TMP007 hardware will be placed in a low power state in which ADC conversions are disabled. If the pin is configured to alarm, the ALERT pin and GPIO pin interrupts will be disabled. The I2C handle is not affected.
Precondition
TMP007_open() had to be called first.
Parameters
handle A TMP007_Handle returned from TMP007_open()
Returns
true on success or false upon failure.
References TMP007_Object::callback, TMP007_Object::i2cHandle, TMP007_Config::object, TMP007_disableAlert(), and TMP007_disableConversions().
TMP007_disableAlert()
bool TMP007_disableAlert (TMP007_Handle handle)
Function to disable the ALERT pin and GPIO interrupt.
This function will disable the ALERT pin on the specified TMP007 sensor. Interrupts on the TMP007 specific GPIO index will be disabled. Any temperature limits set are not affected. This function is not thread safe when used in conjunction with TMP007_enableAlert() (ie. A task is executing TMP007_disableAlert() but preempted by a higher priority task that calls TMP007_enableAlert() on the same handle).
See also
TMP007_enableAlert()
Precondition
TMP007_enableAlert() had to be called first in order for this function to have an effect.
Parameters
handle A TMP007_Handle
Returns
true on success or false upon failure.
References CFG_ALRT, TMP007_Config::hwAttrs, TMP007_Config::object, TMP007_CONFIG, TMP007_readRegister(), and TMP007_writeRegister().
Referenced by TMP007_close().
TMP007_disableConversions()
bool TMP007_disableConversions (TMP007_Handle handle)
Function to put TMP007 sensor is low power state.
This function will place the specified TMP007 sensor in a low power state. All settings are retained. Temperature and voltage readings are invalid in this state. This function is not thread safe when used in conjunction with TMP007_enableConversions().
See also
TMP007_enableConversions()
Precondition
TMP007_open() had to be called first.
Parameters
handle A TMP007_Handle
Returns
true on success or false upon failure.
References CFG_CONV_ON, TMP007_CONFIG, TMP007_readRegister(), and TMP007_writeRegister().
Referenced by TMP007_close().
TMP007_enableAlert()
bool TMP007_enableAlert (TMP007_Handle handle)
Function to enable the ALERT pin and GPIO interrupt.
This function will enable the ALERT pin on the specified TMP007 sensor. Interrupts on the TMP007 specific GPIO index will be disabled. This function is not thread safe when used in conjunction with TMP007_disableAlert() (ie. A task is executing TMP007_enableAlert() but preempted by a higher priority task that calls TMP007_disableAlert() on the same handle).
See also
TMP007_disableAlert()
TMP007_setObjTempLimit()
TMP007_setDieTempLimit()
Precondition
TMP007_setObjTempLimit() or TMP007_setDieTempLimit() had to be called first. If not called first, the TMP007 sensor will never generate an interrupt.
Parameters
handle A TMP007_Handle
Returns
true on success or false upon failure.
References CFG_ALRT, TMP007_Config::hwAttrs, TMP007_Config::object, TMP007_CONFIG, TMP007_readRegister(), and TMP007_writeRegister().
TMP007_enableConversions()
bool TMP007_enableConversions (TMP007_Handle handle)
Function to restore TMP007 to normal power operation.
This function will restore ADC conversions on the specified TMP007 sensor. Temperature and voltage readings may be invalid up to 4 seconds following this function call. This function is not thread safe when used in conjunction with TMP007_disableConversions().
See also
TMP007_disableConversions
Precondition
TMP007_disableConversions() had to be called first.
Parameters
handle A TMP007_Handle
Returns
true on success or false upon failure.
References CFG_CONV_ON, TMP007_CONFIG, TMP007_readRegister(), and TMP007_writeRegister().
TMP007_getTemp()
bool TMP007_getTemp (TMP007_Handle handle, TMP007_TempScale scale, float * data, uint16_t registerAddress)
References CELSIUS_FAHREN_ADD, CELSIUS_FAHREN_CONST, CELSIUS_PER_LSB, CELSIUS_TO_KELVIN, TMP007_FAHREN, TMP007_KELVIN, and TMP007_readRegister().
Referenced by TMP007_getDieTemp(), and TMP007_getObjTemp().
TMP007_getTempLimit()
bool TMP007_getTempLimit (TMP007_Handle handle, TMP007_TempScale scale, float * data, uint16_t registerAddress)
References CELSIUS_FAHREN_ADD, CELSIUS_FAHREN_CONST, CELSIUS_TO_KELVIN, TMP007_FAHREN, TMP007_KELVIN, and TMP007_readRegister().
Referenced by TMP007_getDieTempLimit(), and TMP007_getObjTempLimit().
TMP007_init()
void TMP007_init ()
Function to initialize TMP007 driver.
This function will initialize the TMP007 driver. This should be called before BIOS_start().
References i2cHandle, and TMP007_Config::object.
Referenced by initTMP(), and TMP007_getObjTempLimit().
TMP007_open()
TMP007_Handle TMP007_open (unsigned int tmp007Index, I2C_Handle i2cHandle, TMP007_Params * params)
Function to open a given TMP007 sensor.
Function to initialize a given TMP007 sensor specified by the particular index value. This function must be called from a task context. If one intends to use the ALERT pin, a callBack function must be specified in the TMP007_Params structure. Additionally, a gpioIndex must be setup and specified in the TMP007_HWAttrs structure.
The I2C controller must be operating in BLOCKING mode. Failure to ensure the I2C_Handle is in BLOCKING mode will result in undefined behavior.
The user should ensure that each sensor has its own slaveAddress, gpioIndex (if alarming) and tmp007Index.
Precondition
TMP007_init() has to be called first
Parameters
tmp007Index Logical sensor number for the TMP007 indexed into the TMP007_config table
i2cHandle An I2C_Handle opened in BLOCKING mode
*params A pointer to TMP007_Params structure. If NULL, it will use default values.
Returns
A TMP007_Handle on success, or a NULL on failure.
See also
TMP007_init()
TMP007_Params_init()
TMP007_close()
References TMP007_Object::callback, TMP007_Params::callback, CFG_CONV_ON, CFG_SW_RST, TMP007_Params::conversions, TMP007_HWAttrs::gpioIndex, i2cHandle, TMP007_Object::i2cHandle, TMP007_Params::intComp, TMP007_CONFIG, TMP007_writeRegister(), TMP007_Params::transientCorrect, and WAIT_POST_RESET.
Referenced by initTMP(), and TMP007_getObjTempLimit().
TMP007_Params_init()
void TMP007_Params_init (TMP007_Params * params)
Function to initialize a TMP007_Params struct to its defaults.
Parameters
params A pointer to TMP007_Params structure for initialization.
Default values are: conversions = TMP007_4CONV intComp = TMP007_IntMode transientCorrect = TMP007_TCEnable callback = NULL
References TMP007_defaultParams.
Referenced by initTMP(), and TMP007_getObjTempLimit().
TMP007_readRegister()
bool TMP007_readRegister (TMP007_Handle handle, uint16_t * data, uint8_t registerAddress)
Read function for advanced users.
Parameters
handle A TMP007_Handle
registerAddress Register address
data A pointer to a data register in which received data will be written to. Must be 16 bits.
Returns
true on success or false upon failure.
References TMP007_Config::hwAttrs, i2cTransferFxn(), TMP007_Config::object, and READ_BUF_SIZE.
Referenced by TMP007_disableAlert(), TMP007_disableConversions(), TMP007_enableAlert(), TMP007_enableConversions(), TMP007_getObjTempLimit(), TMP007_getTemp(), TMP007_getTempLimit(), TMP007_readStatus(), TMP007_readVoltage(), and TMP007_setTempLimit().
TMP007_setTempLimit()
bool TMP007_setTempLimit (TMP007_Handle handle, TMP007_TempScale scale, float data, uint16_t bitMask, uint8_t registerAddress)
References CELSIUS_FAHREN_ADD, CELSIUS_FAHREN_CONST, CELSIUS_TO_KELVIN, MAX_CELSIUS, MIN_CELSIUS, TMP007_FAHREN, TMP007_IGNORE, TMP007_KELVIN, TMP007_MASK_ENABLE, TMP007_readRegister(), and TMP007_writeRegister().
Referenced by TMP007_readVoltage(), TMP007_setDieTempLimit(), and TMP007_setObjTempLimit().
TMP007_writeRegister()
bool TMP007_writeRegister (TMP007_Handle handle, uint16_t data, uint8_t registerAddress)
Write function for advanced users. This is not thread safe.
When writing to a handle, it is possible to overwrite data written by another task.
For example: Task A and B are writing to the configuration register. Task A has a higher priority than Task B. Task B is running and reads the configuration register. Task A then preempts Task B and reads the configuration register, performs a logical OR and writes to the configuration register. Task B then resumes execution and performs its logical OR and writes to the configuration register–overwriting the data written by Task A.
Such instances can be prevented through the use of Semaphores. Below is an example which utilizes an initialized Semaphore_handle, tmp007Lock.
if (Semaphore_pend(tmp007Lock, BIOS_NO_WAIT)) {
    //Perform read/write operations
}
else {
    Task_sleep(1000);
}
Semaphore_post(tmp007Lock);
Parameters
handle A TMP007_Handle
data A uint16_t containing the 2 bytes to be written to the TMP007 sensor.
registerAddress Register address.
Returns
true on success or false upon failure.
References TMP007_Config::hwAttrs, i2cTransferFxn(), TMP007_Config::object, and WRITE_BUF_SIZE.
Referenced by TMP007_disableAlert(), TMP007_disableConversions(), TMP007_enableAlert(), TMP007_enableConversions(), TMP007_open(), TMP007_setObjTempLimit(), and TMP007_setTempLimit().
Variable Documentation
TMP007_config
TMP007_Config TMP007_config[]
TMP007_defaultParams
const TMP007_Params TMP007_defaultParams
Initial value:
= {
        TMP007_4CONV,
        TMP007_IntMode,
        TMP007_TCEnable,
        NULL,
}
Referenced by TMP007_Params_init().
© Copyright 1995-2018, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale